### ISSUE TITLE
Preview text disappears!

### ISSUE THREAD

**Issue by BrentThoma** [dsifford/academic-bloggers-toolkit#1]
Hey Derek,

Great work on this so far! I'm quite excited to use it.

After activating the plugin I noticed that the 'preview text' under the titles of the blog posts on my homepage disappeared. Deactivating the plugin resolved the issue so I'm confident that it's related.

Specifically what I'm referring to can be seen if you go to http://boringem.org - under a post title (e.g. "#TipsForNewDocs | Using spaced repetition to study") the text description (e.g. "The Canadian Royal College licensing exam in emergency medicine has a certain mystique. While the pass rate for Canadian graduates is spectacular [1], exam survivors speak of the test in hushed whispers that have an air of PTSD. Having recently survived the exam myself, I have some understanding of where these whispers come from. Prior to my exam year I had planned to write a blog post to reassure the residents following me that it was not that bad… Except that it was. Or at least it would have...") disappears!

I'm not sure if this is just an issue with this theme (it's from Elegant Themes) or will affect people more broadly. Regardless, there will be a theme change for my blog in the future so if it's an isolated issue it won't be bothering me for long.

Thanks!

-Brent

**Comment by dsifford** [comment]
Thanks for pointing this out. You were right; a small error in the code of this plugin was creating the issue. I just sent out a new release that should fix the issue. Everything should be in working order now :smile:

**Comment by BrentThoma** [comment]
Quite the response time!
When I logged back in WP didn't indicate that there was an update for the plugin available. When I tried to update it anyways that seemed to work. However, it's still doing the same thing to the preview's. Perhaps I didn't get the fixed version?
-BT

**Comment by dsifford** [comment]
Oops! My mistake. When I uploaded the fix to WordPress, I forgot to tag it as the "stable" version. Thus, when you downloaded the file again, you just downloaded the same one as before. Everything should be working now.
