### ISSUE TITLE
Problems with URLs

### ISSUE THREAD

**Issue by JLJu** [dsifford/academic-bloggers-toolkit#100]
Thank you for your work!
I use the following toolchain/procedure to publish references with your plugin.
Zotero->Export RIS -> Plugin, Choose citation style  "IEEE With URL->Plugin, Import RIS -> Plugin, Insert selected reference.

Some chars are added at the end of the cited URLs and so the published URL is invalid. See for example the following code from WP.

```
<div id="abt-smart-bib" class="noselect mceNonEditable">
<div id="1m0ro2ca7">
<div class="csl-entry flush">
<div class="csl-left-margin">[1]</div>
<div class="csl-right-inline">C. Salter, J. H. Warsap, and D. G. Goodman, “A Discussion of Pitot-Static Tubes and of their Calibration Factors with a Description of Various Versions of a New Design.” Her Majesty’s stationery office, 1965 [Online]. Available: <a href="http://naca.central.cranfield.ac.uk/reports/arc/rm/3365.pdf&lt;/div" target="_blank">http://naca.central.cranfield.ac.uk/reports/arc/rm/3365.pdf&gt; </a></div>
```

Those added chars ```&lt;/div and &gt;``` are not present within the RIS file. As a workaround, I've patched by hand the URLs within Wordpress. Any advice is welcome , don't hesitate to ask for supplementary info.

**Comment by dsifford** [comment]
Hi there.

Looks like the html is stripping the `>` symbols and replacing it with encoded values. Can you tell me what browser you are using?

Thanks for the report.

**Comment by JLJu** [comment]
Hi,
Here we are.
Chrome 52.0.2743.82 (64-bit) under Fedora 23. 
Chrome 52.0.2743.82 (64-bit) under Windows 10.
Regards

**Comment by dsifford** [comment]
@JLJu Fellow Linux user, eh? Nice!

Thanks again for the report. I'm working on a massive update to the plugin's data flow and processing at the moment, so I'm going to hold off on working on a patch for this issue for the time being. 

The next update _should_ fix this on it's own, but I'll be sure to test this specifically before pushing the changes to WordPress.org. If you'd like, you can track the status of the next update by watching the changes to [this branch](https://github.com/dsifford/academic-bloggers-toolkit/tree/mobx). I'm hoping to have the update ready in about a week. 👍

**Comment by JLJu** [comment]
Yes, Linux is great!
It's good to hear your news.

**Comment by Vitaliy-1** [comment]
> Those added chars &lt;/div and &gt; are not present within the RIS file. As a workaround, I've patched by hand the URLs within Wordpress. Any advice is welcome , don't hesitate to ask for supplementary info.
>
I think my issue with text which goes beyond the Peer Review box is because this added chars from RIS file.

**Comment by dsifford** [comment]
@JLJu @Vitaliy-1 I haven't forgotten about you both 😃 

I'm making pretty tremendous strides on the next update. The current work-in-progress is _much_ more stable than the current release, so I think you'll both be happy about that. It's also a touch faster too!

Anyway... Two things:

1. @JLJu can you send me the RIS file that you used that triggered this error so I can try to trigger it here?
2. (cc: @metallikat36 ): Would any of you be interested in testing the next version once I have it completed, prior to the release to WordPress.org? The more eyes I can get on it, the better. Thanks either way!

**Comment by metallikat36** [comment]
Unfortunately, I won't be able to test this one Derek. Presently too busy at the moment. We'll I mean I will try some basic stuff for 5 minutes, and let you know, but I won't try to break it.

**Comment by dsifford** [comment]
@metallikat36 No worries! You've been more than helpful with everything up to now. Thanks anyway 👍

**Comment by JLJu** [comment]
1. Sure http://www.basicairdata.eu/commenti/References.ris
2. Sure. However, right now it is not feasible for me. What about September?

**Comment by dsifford** [comment]
@JLJu Thanks!

Might be all tested and ready by September, but I'll keep that in mind. 👍

**Comment by dsifford** [comment]
@JLJu Where did you export that RIS file from? There are some non-standard fields included in it which creates issues in some cases. Gonna see if I can track down the spec for your particular reference manager...

**Comment by JLJu** [comment]
http://zotero.org(Release 4.0.29.10 64  bit)-> File -> export Lib -> Format RIS file (all options unticked)

**Comment by dsifford** [comment]
Ah, that's right you mentioned zotero in your first comment. Whoops, sorry for overlooking! Thanks

**Comment by dsifford** [comment]
@JLJu What citation style were you using when this issue occurred?

**Comment by JLJu** [comment]
Never mind. Citation style "IEEE With URL" within the plugin. I don't think the RIS file is affected by styles.

**Comment by dsifford** [comment]
Ok thanks for the clarification. 

I think I fixed it. I can't reproduce it with the new version I'm working on. I'll call this "fixed until proven otherwise". Let me know if you still have the issue after the next release and I'll re-evaluate.

**Comment by JLJu** [comment]
Roger. Thank you!
