### ISSUE TITLE
Bug with citation tooltip rendering

### ISSUE THREAD

**Issue by Vitaliy-1** [dsifford/academic-bloggers-toolkit#101]
Another issue that I discovered is dyssync. of peer review boxes with numeral list
For example: http://i11.pixs.ru/storage/3/5/5/ref3jpg_8469584_22788355.jpg
This issue especially true when downloading a .ris file (from zotero) and after it adding additional reference by PubMed number. This was my case. 

There is another issue with dissync. of all reference editor by can`t understand the mechanism.

Also when url is to long it It goes beyond the Peer Review box: http://i11.pixs.ru/storage/5/4/2/ref4jpg_7131967_22788542.jpg
This also was the case of importing .ris file

Sorry for my overbearing, but I am developing open access medical journal for my institution in Ukraine and planing to use this plugin for creating reference lists. Crushed references are not to good for scientific journal :) This is the best plugin available for WP, after all.

**Comment by dsifford** [comment]
Hm.. Thanks for letting me know.

Is there any chance you can share with me the URL of one of the affected pages so I can inspect it?

**Comment by Vitaliy-1** [comment]
For now I can share only with test page. I have emulated this two problem there:
http://www.e-medjournal.com/uk/artpost/%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%B0/
The first problem with dyssync were duplicated by deleting one reference in the refmanager (look at 5 and 6 ref items).
The second maybe because of problems with .ris creating by Zotero but the link is not completely broken.
I`m just wondering - is there a possibility to make URL links in references shorter? with Java for example?

**Comment by dsifford** [comment]
@Vitaliy-1 I'm sitting down to try and tackle this issue now and I noticed that the test page you shared is no longer available. 

Any chance you can make a new one and share with me again?

Also, what language is your wordpress installed in? (If unsure, you can find that information by selecting `Settings` -> `General` and scrolling to the bottom.

**Comment by Vitaliy-1** [comment]
I changed URL in the previous post. URL had broken because of conflicting 2 plugins after their update...

About the languages: there are 25 languages installed, but site language is English (US).

**Comment by dsifford** [comment]
@Vitaliy-1 Can you confirm that the improper citation tooltips resulted by the plugin itself and there was no physical manipulation of the html by you or anybody else?

The reason I ask, the plugin is actually doing what it's supposed to do. In the link above, citation number 6 shows citations 1-4, which looks like an error, but upon inspection, it looks like the saved metadata for that individual citation is for those four citations. The only way that the citation could have been labelled `6` is if somebody physically manipulated the numbers of the citations (which you should _not_ do). 

Of note, the plugin orders the citations based on how they are supposed to be ordered by your chosen citation style. If that order is manipulated, you'll not only have errors like these, but also you'll be using the citation style improperly.

**Comment by Vitaliy-1** [comment]
Those citation were made by importing RIS file from zotero. Than I placed them in text ONLY by plugin.
Citation numbers were  shifted after I deleted one of the reference also only by plugin.

I don`t remember if I changed citation style on this page. When I will have a free time I check this issue once more.

**Comment by dsifford** [comment]
Hm. Not sure what to tell ya. There's nothing I can do on my end that reproduces your issue.

The best I can tell you for that page is to wait for the next release and see if that fixes the issue. The backend is much, much stronger in the next release.
