### ISSUE TITLE
Javascript error in Entrypoint.js

### ISSUE THREAD

**Issue by gillespieza** [dsifford/academic-bloggers-toolkit#103]
I get this error on my WPMU site:

Uncaught TypeError: Cannot read property 'parentElement' of null in file Entrypoint.js

**Comment by dsifford** [comment]
Thanks for the report.

Can you tell me exactly what page this is happening on?

**Comment by dsifford** [comment]
Haven't heard back. I assume the latest update fixed this. 

Closing this issue for now. Feel free to reopen if the issue persists.

**Comment by gillespieza** [comment]
Hi, sorry, I've been off sick with flu for the last week. 

This was happening on the edit screen - posts or pages, when I try to insert references. 

Or it least, it *was* happening. I can't reproduce that console error any more (perhaps something to do with the latest WP update or plugin update to 4.0?) 

Now, I get a popup alert saying "" and the animated spinner just sits there in the background and nothing happens... No console errors logged either.

This is happening even if I switch to the default TwentySixteen Theme and de-activate all other plugins. 

Screenshot attached, fwiw.

![untitled-1](https://cloud.githubusercontent.com/assets/11884699/17731924/d1ce745c-646f-11e6-85d7-57fc839c813e.png)
