### ISSUE TITLE
BaseURL in Constants.ts gets stripped to domain instead of actual WP url

### ISSUE THREAD

**Issue by floaltvater** [dsifford/academic-bloggers-toolkit#105]
Hi,
After installing your plugin, whenever I want to add a reference, all I see is "Insert Formatted Reference". The main body (iframe) doesn't open. The Firefox console gives me a
"Load denied by X-Frame-Options: https://www.ocf.berkeley.edu/wp-content/plugins/academic-bloggers-toolkit/lib/js/tinymce/views/reference-window.html does not permit framing".

What's interesting is, that the blog lives at "https://www.ocf.berkeley.edu/~myusername/private/wp_myblog/" and not "https://www.ocf.berkeley.edu/" as suggested by the error message.
I can just assume that window.location.origin in Constants.ts strips the site URL down to the domain, ignoring the rest after it? It feels like it would be safer to somehow get the actual WP URL? I just don't know how I would implement that.

Thanks for your time,
Flo

**Comment by dsifford** [comment]
Darn, I thought changing how I had it might create an issue.

Previously I relied on wordpress sending the URL to the plugin directory prior to having the application start up. I switched to computing the URL on this last release (which was obviously a poor decision).

I'll work on a fix and push it out sometime in the next hour or so. 

Thanks for the report!
