### ISSUE TITLE
Biblio not showing when only one reference

### ISSUE THREAD

**Issue by floaltvater** [dsifford/academic-bloggers-toolkit#108]
Hey,
When I insert only one citation in a post, it doesn't create the biblio at the end of the post. It doesn't matter how often I cite that one reference. Only when I include a second reference in the post, will it create the reference list. Is that intentional, or am I missing something?

Thanks!

**Comment by dsifford** [comment]
Nope, not intentional. Good catch. 👍 

I'll work on a fix.

**Comment by dsifford** [comment]
@floaltvater I can't reproduce this.

Can you make this happen somewhere and then share the link with me?

Thanks

**Comment by floaltvater** [comment]
Hope this is what you meant:

https://www.ocf.berkeley.edu/~altvater/private/wp_neaton/?p=146

This post originally had two references. I just deleted one, and the biblio disappeared again.

**Comment by dsifford** [comment]
@floaltvater Thanks.

Hmm.. Is the bibliography mission on the editor page as well?

**Comment by floaltvater** [comment]
Yep. Very reproducible.

**Comment by dsifford** [comment]
Strange... I just can't get that to happen here. What other plugins are you using?

**Comment by floaltvater** [comment]
I just deactivated all plugins and changed the theme to Twentysixteen and it still happens. Not sure what else I could debug.

**Comment by dsifford** [comment]
Hm.. That's the same theme I'm using as well. 

Can you tell me exactly the steps you take to make this happen? Or perhaps take a [screen recording](https://www.opentest.co/) of this behavior?

Thanks for the help!

**Comment by dsifford** [comment]
@floaltvater Nevermind. I just got it to happen. 👍

**Comment by floaltvater** [comment]
Sweet! There was really nothing special about it. So what triggered it for you?

**Comment by dsifford** [comment]
To be honest, I'm not sure. I added and removed a citation a few times and also added and removed the bibliography heading. Gonna investigate it further.

**Comment by floaltvater** [comment]
Interesting. For me it happens every single time. No matter if I just add one citation, or remove one of two. As long as there is only one reference, I don't get a biblio.

Let me know if I can help any further with this.

**Comment by dsifford** [comment]
Will do. Thanks again!

**Comment by dsifford** [comment]
Found it. 👍 

Compared to `null` where I should have compared to `''` when setting the bibliography. 

I'll package this up and send out a release soon.

**Comment by floaltvater** [comment]
Awesome! Thanks so much!
