### ISSUE TITLE
Bug of your Academic Blogger Toolkit

### ISSUE THREAD

**Issue by aroy1962** [dsifford/academic-bloggers-toolkit#114]
HI,
I use your plugin in my website (epidis.net) and after la last update, I can not access to my administrator panel.  I checked the error.log file of my website, and read the following line:
Parse error: syntax error, unexpected '[' in /home5/epidemi2/public_html/epidisnet/wp-content/plugins/academic-bloggers-toolkit/academic-bloggers-toolkit.php on line 73

Then, I deleted the folder of the plugin and reinstall the plugin, but the plugin page of my administrator panel show the following:
The plugin was deactivated for:
Parse error: syntax error, unexpected '[' in /home5/epidemi2/public_html/epidisnet/wp-content/plugins/academic-bloggers-toolkit/academic-bloggers-toolkit.php on line 73

Can you help me to solve or fix this problem.

I think your plugin is awesome and I want to continue using it.

Regards,

Adriel

**Comment by dsifford** [comment]
Sorry to hear you're having issues, @aroy1962 

From what you're describing, it sounds like your php version is outdated. Do you know off hand what version you are running with your wordpress instance?

This plugin requires PHP 5.6 or greater.

**Comment by dsifford** [comment]
If that is indeed the issue (which I'm almost certain it is) I would highly recommend upgrading your PHP version to at least version 5.6.

All earlier versions are at "end of life" status on PHP.net, meaning there is a potential for security vulnerabilities.

See more on this [here](http://php.net/supported-versions.php)

**Comment by dsifford** [comment]
@aroy1962 Any updates? Were you able to get it working?

**Comment by aroy1962** [comment]
Thanks by your response and concern.

I configured my web hosting to work with php5.6 and your plugin works fine.

Also, I want to tell you that your plugin is awesome.

Regards,

Adriel

**Comment by dsifford** [comment]
Awesome. Glad to hear you got it working, and glad to hear you like it. 👍
