### ISSUE TITLE
Bibliography toggle icon not rendering

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#116]
Hi Derek. Five comments on the latest 4.0 release:

1. FYI, the custom CSS got deleted on update. Perhaps you did that intentionally. In any case, no worries, I always keep copies of my custom CSS code in a Word file. 

2. See screenshot below in mozilla. The expand button is weird. 
![image](https://cloud.githubusercontent.com/assets/17968340/17751854/f2f71d2e-647d-11e6-82f6-8f781f0a22de.png)

3. In my phone's Chrome I see an X bounded by a rectangle. Confirm that is the correct appearance? Is that supposed to be a universal symbol for "expand"? I think the arrow was more intuitive. 

4. The references did need refreshing in each article after this update. Otherwise the tooltips were displaying the wrong references. Not an issue for me at all, but just thought I would make you aware of that. (BTW, in case you were tempted, I think a "mass refresh" button would probably be a bad idea as if something goes wrong your whole site is screwed. 

5. I am curious if ABT in any way conflicts with rolling back older versions of a wordpress post. Like if I wanted to revert to a version of an article I had 1 week ago, what if that version had different references? Or what it there was also an update to the plugin in that timeframe? Something to think about.

**Comment by dsifford** [comment]
>  the custom CSS got deleted on update.

Shoot! You're right. I had to shuffle a lot of options around and after checking, it looks like I missed that one.

If anything, that tempt people to load their CSS through their child theme, rather than using that box. I still maintain that that box is horribly inefficient.

> The expand button is weird. 

Rendering of the toggle button depends on wordpress built-in "dashicons". I didn't have that explicitly set as a dependency, but I just changed to so that it is. Next update should fix that.

> The references did need refreshing in each article after this update. Otherwise the tooltips were displaying the wrong references. Not an issue for me at all, but just thought I would make you aware of that.

Can you confirm that all your references needed a refresh? That should not have been the case. I apologize for the inconvenience.

**Comment by metallikat36** [comment]
Yes, I did need to refresh all articles with references - which for me was only a grand total of two articles, One of them had only three references. I noted the third tooltip in that article actually displayed the first reference. The other article had 50 references and I noticed the 50th tooltip similarly displayed the the wrong reference. I think it was also displaying reference number 1 if I recall.  That's as much as I clearly remember. 

Aside from rollbacks, what about site backup restores? Like I am hosted on Siteground, and say I wanted to rollback my whole site restore that they have saved for me, say from 1 week ago. This would actually work without issue I imagine. Would you agree?

**Comment by dsifford** [comment]
> Aside from rollbacks, what about site backup restores? Like I am hosted on Siteground, and say I wanted to rollback my whole site restore that they have saved for me, say from 1 week ago. This would actually work without issue I imagine. Would you agree?

Correct. As long as the post meta agrees with the current state of the document, this should work. 

Heck, rollbacks might even work if the rollbacks also include post meta. I'm not sure.

**Comment by dsifford** [comment]
> Yes, I did need to refresh all articles with references - which for me was only a grand total of two articles, One of them had only three references. I noted the third tooltip in that article actually displayed the first reference. The other article had 50 references and I noticed the 50th tooltip similarly displayed the the wrong reference. I think it was also displaying reference number 1 if I recall. That's as much as I clearly remember.

What citation style are you using? This update fixed an issue that was lingering that caused something similar to what you described to happen to the tooltips. This might have just fixed that issue. Updates from now on _shouldn't_ require any post updates.

**Comment by metallikat36** [comment]
I use AMA style.

What's post meta? Does "post meta agreeing with current state of a document" in anyway depend on a sitewide rollback being as recent as possible? 

My real concern in the event of either a sitewide restores or a rollback of an individual post is just to make sure the info is all there somewhere/somehow, even if it takes some work to make it function again.  As long as I can somehow dig up the list of urls I referenced, worst case scenario I can just spend the time to reinput those as reference lists. Would you agree that even if rollbacks of either the whole site or individual articles didn't function "out of the box" that I would still somehow be able to obtain a raw list of references that I could then reinput?

**Comment by dsifford** [comment]
> What's post meta?

The state of the reference list is saved and attached to the post as post meta. Things like the post author, post type, categories, etc are all saved as post meta and attached to each individual post for use behind the scenes.

I'm 99.999% positive that a site rollback will not affect your references in any way because you'd be rolling back everything, including the post meta. 

Hope that makes sense.
