### ISSUE TITLE
Clash with Customizr theme

### ISSUE THREAD

**Issue by floaltvater** [dsifford/academic-bloggers-toolkit#122]
I finally tracked down my `tinyMCE.activeEditor.dom.addStyle is not defined` error. It is actually the customizr theme, of which I'm using a homemade child. I don't know why it didn't occur to me earlier to actually try to find the `tinyMCE.activeEditor.dom` in the code. The line appears in the Customizr theme files (customizr/inc/admin/class-fire-admin_init.php).

To summarize: With the Customizr theme, ABT works when ACF is turned off, and doesn't when it is on. With Twentysixteen ABT works any time (despite what I said in the other issue, where I was sure that changing the theme didn't change the outcome, sorry about that). I suspect that `tinyMCE.activeEditor` in Customizr is probably not what it expects it to be, and gets the ABT editor for which activeEditor.dom is not defined.

Would that make sense? And is there a way to fix it on your end, or should I contact the customizr developers to see if they can change it? I don't actually know what that line does.

**Comment by dsifford** [comment]
@floaltvater I just installed customizr to my test site and tried with my plugin and it doesn't seem to be an issue for me.

Are you doing anything fancy with your child theme?

**Comment by dsifford** [comment]
Oh, wait.. Didn't read this line...

> With the Customizr theme, ABT works when ACF is turned off, and doesn't when it is on. 

Let me test that real quick.

**Comment by dsifford** [comment]
Yep, it's an issue with customizr, and not ABT.

I actually had this same issue in the past and had to correct it. Like I said before, ACF creates a hidden tinymce editor on every admin page. 

Customizr doesn't have a check to make sure that the editor they are adding the styles to is the "content" editor. Because of that, it fires the script for both the content editor and the `acf_settings` editor (pictured below).

That is the root of the issue.

**Comment by dsifford** [comment]
If you show the theme developer this line, he should be able to fix this quite easily:

https://github.com/dsifford/academic-bloggers-toolkit/blob/4.0.1/src/lib/js/tinymce/index.ts#L10

**Comment by dsifford** [comment]
The reason why my plugin breaks is because his script executes before mine does and it causes an uncaught exception to be thrown which then causes the rest of the execution to fail.

No way I can defend against that.
