### ISSUE TITLE
Bibliography stopped rendering on front-end

### ISSUE THREAD

**Issue by gillespieza** [dsifford/academic-bloggers-toolkit#124]
Hi there

My bibliography is suddenly not rendering anymore, on my website front-end. I get the following console error in Chrome:
`Frontend.js:1 Uncaught TypeError: Cannot read property 'children' of null`

and in Firefox:
`TypeError: e.bibliography is null  Frontend.js:1:833`

URL is: http://demo4.salamanderthemes.net/mindfulness/scientific-research/

**Comment by dsifford** [comment]
Hm, strange. I haven't touched that stuff, so there shouldn't have been a change. 

I'm away on vacation until Friday so I won't be able to look into it until then.

**Comment by dsifford** [comment]
One thing I will mention: the bibliography _never_ has to be rendered. It is a static element and does not need my plugin installed to render it once it has been generated on the post editor page. 

The only responsibility of the script that you mentioned is rendering tooltips. The error you specifically mentioned leads me to believe the bibliography does not exist. Can you open the post editor and confirm that it does?

If it does, then there must be a conflict with another plugin you have installed.

**Comment by gillespieza** [comment]
The reference list exists as html in the post, but doesn't appear to be attached to the Reference List any more... The div containing the references is there in HTML/text view but seems to disappear when I toggle to Visual Mode (and then stays disappeared).

Very odd. It must be a plugin conflict. I've restored an autosave, and will remind clients not to edit that particular post.

**Comment by dsifford** [comment]
Has this been resolved @gillespieza ?

I'll check into CMSMasters and see if it's something I can guard against.

**Comment by dsifford** [comment]
Closing this for now. I checked the URL you listed in your first comment and it appears that everything is working for you now.

FYI: CMSMasters' custom editor will not work with ABT. ABT requires the default TinyMCE editor. There's really no way to get both plugins to play nicely together since CMS Masters uses a custom editor.

**Comment by acsinsurancegroup** [comment]
This plugin is straight up garbage!
