### ISSUE TITLE
Can't get URL right

### ISSUE THREAD

**Issue by Greentreegarden** [dsifford/academic-bloggers-toolkit#151]
**ABT Version:** 4.2.0

**PHP Version:** 5.6

**Theme:**

**Plugin List:**

**Expected behavior:**
Use "http://capital-gain.eu/wp-content/uploads/sites/2/2016/09/test.ris" as RIS file.
I have copied the URL exactly from Media Library.
Note this is a multisite URL.

**Actual behavior:**
"The provided URL is not a valid file in your WordPress upload directory."

**Console messages:**
```js
// Paste messages here
```

This is the RIS file:
TY  - BOOK
SN  - 0471863890
AU  - Seborg, Dale E.
AU  - Edgar, T. F.
AU  - Mellichamp, Duncan A.
T1  - Process dynamics and control
PY  - 1989
H1  - British Library
H2  - DSC q90/03788
H1  - British Library
H2  - HMNTS YK.1990.b.5205
TS  - The British Library
M4  - Citavi
ER  -

**Comment by dsifford** [comment]
Thanks for the report. @Greentreegarden 

I hadn't considered multisite installations. I'll try and push out a fix with the next update (it's gonna be a big one!).

**Comment by dsifford** [comment]
@Greentreegarden Looking at this now. It should be working for multisite as-is.

Can you give me an idea of what your wordpress multisite directory structure looks like? What is the path to your uploads directory?

Thanks

**Comment by Greentreegarden** [comment]
.mceResizeHandle {position: absolute;border: 1px solid black;background: #FFF;width: 5px;height: 5px;z-index: 10000}.mceResizeHandle:hover {background: #000}img[data-mce-selected] {outline: 1px solid black}img.mceClonedResizable, table.mceClonedResizable {position: absolute;outline: 1px dashed black;opacity: .5;z-index: 10000}
Hi Derek,
 
see attached. It is the standard structure, as far as I know.
 
I have been trying to insert http://capital-gain.eu/wp-content/uploads/sites/2/2016/09/test.ris as given by Media Library.
 
(In order to be able to register files with the RIS extension, I am using https://de.wordpress.org/plugins/wp-extra-file-types/ )
 
Regards / Viele GrüßeArmin
 
Derek Sifford <notifications@github.com> hat am 12. September 2016 um 18:26 geschrieben:
@Greentreegarden Looking at this now. It should be working for multisite as-is.
Can you give me an idea of what your wordpress multisite directory structure looks like? What is the path to your uploads directory?
Thanks

**Comment by dsifford** [comment]
@Greentreegarden Oh, ok I'm sorry I misunderstood what you were attempting to do.

RIS importing does not happen through the media library. That happens on the editor page.

Instructions for how to accomplish that can be found here: https://github.com/dsifford/academic-bloggers-toolkit/wiki#adding-references-using-ris-file

Please let me know if this still does not work for you.

**Comment by Greentreegarden** [comment]
.mceResizeHandle {position: absolute;border: 1px solid black;background: #FFF;width: 5px;height: 5px;z-index: 10000}.mceResizeHandle:hover {background: #000}img[data-mce-selected] {outline: 1px solid black}img.mceClonedResizable, table.mceClonedResizable {position: absolute;outline: 1px dashed black;opacity: .5;z-index: 10000}
hmm.
 
I only see the turning circle on the right hand side (attachment) - and I thought, of course, there is no link to the RIS file. The "Hamburger Menu" as in

: https://github.com/dsifford/academic-bloggers-toolkit/wiki#adding-references-using-ris-file

does not appear.
 
 
Regards / Viele GrüßeArmin
 
Derek Sifford <notifications@github.com> hat am 12. September 2016 um 19:37 geschrieben:
@Greentreegarden Oh, ok I'm sorry I misunderstood what you were attempting to do.
RIS importing does not happen through the media library. That happens on the editor page.
Instructions for how to accomplish that can be found here: https://github.com/dsifford/academic-bloggers-toolkit/wiki#adding-references-using-ris-file
Please let me know if this still does not work for you.

**Comment by dsifford** [comment]
> I only see the turning circle on the right hand side

This leads me to believe that you do not have the visual editor enabled. The wordpress visual editor is a requirement for the plugin.

If you are using some other custom editor or the "text" editor, the plugin will not work (it's deeply integrated into the default one).

Also, FYI: I'm not getting any of the attachments you are sending. If you'd like to post an image, you'll have to do so at this URL: https://github.com/dsifford/academic-bloggers-toolkit/issues/151

**Comment by Greentreegarden** [comment]
![abt file structure](https://cloud.githubusercontent.com/assets/22142544/18450717/62cd6b42-7934-11e6-9227-e7264f95d11f.png)
![abt reflist](https://cloud.githubusercontent.com/assets/22142544/18450716/62cb31a6-7934-11e6-99f8-c6fb7c7bd37e.png)

**Comment by Greentreegarden** [comment]
.mceResizeHandle {position: absolute;border: 1px solid black;background: #FFF;width: 5px;height: 5px;z-index: 10000}.mceResizeHandle:hover {background: #000}img[data-mce-selected] {outline: 1px solid black}img.mceClonedResizable, table.mceClonedResizable {position: absolute;outline: 1px dashed black;opacity: .5;z-index: 10000}
trying to find out what "visual editor" is. 
https://www.google.de/#q=wordpress+plugin+visual+editor does not help.
 
Do I have to install a plugin?
 
I have a self-hosted (on a professional hoster) wordpress - out of the box.
 
 
 
Derek Sifford <notifications@github.com> hat am 12. September 2016 um 21:37 geschrieben:

I only see the turning circle on the right hand side

This leads me to believe that you do not have the visual editor enabled. The wordpress visual editor is a requirement for the plugin.
If you are using some other custom editor or the "text" editor, the plugin will not work (it's deeply integrated into the default one).
Also, FYI: I'm not getting any of the attachments you are sending. If you'd like to post an image, you'll have to do so at this URL: #151

**Comment by Greentreegarden** [comment]
I have visual editor enables as in https://en.support.wordpress.com/visual-editor/

**Comment by dsifford** [comment]
Hm... Not sure why it isn't working.

I'm on my way to class now so I'll have to check in on it later.

In the meantime, can you try the following:

1. disable all other plugins besides ABT. Does it work then?
2. on the editor page, hit <kbd>F12</kbd> and paste any error messages over to here.

Thanks!

**Comment by Greentreegarden** [comment]
.mceResizeHandle {position: absolute;border: 1px solid black;background: #FFF;width: 5px;height: 5px;z-index: 10000}.mceResizeHandle:hover {background: #000}img[data-mce-selected] {outline: 1px solid black}img.mceClonedResizable, table.mceClonedResizable {position: absolute;outline: 1px dashed black;opacity: .5;z-index: 10000}
I am at conferences and travelling until Wed next week - and this is a multisite. So "quickly disabling" all plugins is not something I would like to do on the flight.
 
We'll see.
 
Maybe I can give you a BE access via private email.
 
Derek Sifford <notifications@github.com> hat am 12. September 2016 um 22:08 geschrieben:
Hm... Not sure why it isn't working.
I'm on my way to class now so I'll have to check in on it later.
In the meantime, can you try the following:

disable all other plugins besides ABT. Does it work then?
on the editor page, hit F12 and paste any error messages over to here.

Thanks!

**Comment by dsifford** [comment]
Back home now. 

Let me know if you get it working or if you're able to come up with more clues that could help point me in the right direction.

**Comment by dsifford** [comment]
Any updates @Greentreegarden ?

**Comment by dsifford** [comment]
@Greentreegarden I'm closing this issue for now since I haven't heard back. Feel free to reopen if you're still having issues.
