### ISSUE TITLE
Error in new installation

### ISSUE THREAD

**Issue by davidandrew52** [dsifford/academic-bloggers-toolkit#158]
**ABT Version:** 4.3.0

**PHP Version:** 5.6

GalaNight

Askimet
Blog2Social
Breadcrumb NavXT
Fast Secure Contact Form
Google Analytics Dashboard for WP
Google XML Sitemaps
Grunion Ajax
Postie
RichTextEditor For WordPress
Ultimate Social Media PLUS
UpdraftPlus - Backup/Restore
Yoast SEO

**Browser:** Google Chrome (Version: xxx)

Installation and operation

The box under Reference list has a rotating circle and no other content
Error message Notice: Rich editing must be enabled to use the Academic Blogger's Toolkit plugin
I use a rich text editor

l
```js
// Paste messages here
oad-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,wp-a11…:9 JQMIGRATE: Migrate is installed, version 1.4.1
https://d37gvrvc0wt4s1.cloudfront.net/js/v1.9/rollbar.min.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
chrome-extension://onjpdndafpomogcncdgemfpoidkhjemi/sitecheck.js:6 undefined
3contentscript.js:21 Uncaught ReferenceError: $ is not defined
VM4127:1 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
2contentscript.js:21 Uncaught ReferenceError: $ is not defined

**Comment by dsifford** [comment]
Thanks for the report @davidandrew52 

There's a couple things that could be happening...

### 1. Are you _certain_ that you have rich editing enabled? 

The only way that the message you're speaking of should show up is if that option is not set in your database. Can you go into your user page and make sure the "visual editor" checkbox is checked?

### 2. Adblocker blocking scripts
From the log messages that you pasted in, it appears that you have an aggressive adblocker that is blocking one of my scripts (and others that aren't mine). 

Can you try again with your adblocker disabled and report back? 

### 3. Plugin conflict

I'm not familar with it, but I'm fairly certain that the `RichTextEditor For WordPress` plugin that you listed will conflict with ABT. 

ABT requires the use of the default wordpress rich text editor.

Thanks!

**Comment by dsifford** [comment]
@davidandrew52 Actually, after just looking into it, I'm absolutely certain it's because you are using `RichTextEditor For WordPress`. This plugin is not compatible as it's deeply integrated with the default editor.

**Comment by davidandrew52** [comment]
Thank you for the quick response - all sorted.

David

[image: photo]

<http://facebook.com/davidandrew52>
<http://us.linkedin.com/in/davidandrew52>
<http://twitter.com/davidandrew52>
David Andrew
Individual and Organisational Psychologist, Ministering to a better world

0208 144 6753
david@mcraeandrew.co.uk
mcraeandrew.co.uk

**Comment by dsifford** [comment]
Great! Glad to hear you were able to get it sorted out. Hope it works well for you. 👍
