### ISSUE TITLE
Add optional collapse reference list & peer review boxes

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#16]
An idea just came to my mind.  It's not essential, and may not be possible anyway, but it would be cool.  Make the ordered list of references expandable and collapsible.  An example of this is Mercola.com:
http://articles.mercola.com/sites/articles/archive/2010/08/10/making-sense-of-your-cholesterol-numbers.aspx
Default position would be collapsed.  This would make it easier to scroll down past the article to reach the comments section, without having to scroll past 100 references first.  

I'll test out your new 2.4.0 changes shorty, then give you my feedback.

**Comment by dsifford** [comment]
@metallikat36 Good thought, though it's a bit of a niche change that I don't think everyone will want/need. 

There are various plugins out there that can give you that functionality with mine. An example off the top of my head would be [Shortcodes Ultimate](https://wordpress.org/plugins/shortcodes-ultimate/)

**Comment by dsifford** [comment]
@metallikat36 Good news: I've had another request for the ability to choose between collapsible and non-collapsible peer-review boxes...

Because of that, I think I'll put some time into writing a function to allow collapsible and non-collapsible references and peer review boxes next time I get some free time 👍

**Comment by dsifford** [comment]
Resolved: 8733a491004f72a3ce66dc2f2d01cbce52907381

**Comment by metallikat36** [comment]
A few comments:

1. You might want to add a note about styling the bibliography heading.  Here is what I used to style mine:
```
#abt-smart-bib-toggle {
   font-size: 22px; 
}

#abt-smart-bib-toggle.abt-hidden.noselect::before, #abt-smart-bib-toggle.noselect::before {
margin-left: 10px;
}
```
2. I don't know the CSS selector for the bibliography header while in "fixed" mode. I was only able to figure out how to style the header in "toggle" mode. Might want to include a note about what that selector is too. Though I personally do not need it.

3. Switching to "toggle" mode for the bibliography breaks my previous posts prior to the update. You may want to include instructions for that. Though I don't personally need it, since I only had one post with three references, so I just redid it.

**Comment by dsifford** [comment]
Hey there!

> I don't know the CSS selector for the bibliography header while in "fixed" mode.

That should be `#abt-smart-bib-container h3` (let me know if it isn't)

> Switching to "toggle" mode for the bibliography breaks my previous posts prior to the update.

Yikes!! Can you give me more details on what happens exactly? That's the trouble with modifying existing features -- Super dangerous if you don't cover all your bases!

Thanks for the feedback.

**Comment by metallikat36** [comment]
Yes, that CSS selector works.

For me, what happened after the update is the biblio heading and the biblio just disappeared completely. I think this only happened if I turned on "Toggle" mode. I think if I kept the plugin in "Fixed" mode then the biblio header and biblio displayed fine, just as they were before the update (the heading in this case being due to manual CSS code). If I applied a heading name with the new field you provided in this update, that info did nothing.

**Comment by dsifford** [comment]
Can you elaborate on "biblio heading and the biblio just disappeared completely" -- Like, you weren't able to see it at all? 

Any chance you could reproduce the issue and capture a screengrab (or give me the steps to reproduce)?

**Comment by metallikat36** [comment]
Like if you edited the post, deleted all the references, then deactivated the plugin, that is what I saw at hte bottom. THe inline citations were there, but at the bottom of hte post, it was like the plugin didn't even exist.

The only way I could try to reproduce is by installing an older version of the plugin. You would have to give me the files to do that.

**Comment by metallikat36** [comment]
Steps would be install the old version, and make a references list on a post. Then update the plugin to the new version, and put it in Toggle mode, and the reference list  should disappear.

**Comment by dsifford** [comment]
Hm... Is there any chance it could have been a cache issue?

**Comment by metallikat36** [comment]
I don't think so. I disabled my cloudflare, cleared my cache in my HyperCache plugin, and opened the link in a private browsing window.

**Comment by metallikat36** [comment]
Well, maybe if no one else complains then it's not an issue =). If it is actually a bug, you should be getting more posts soon.

**Comment by dsifford** [comment]
Hm... I'll have to dig into it more to see if I overlooked something. Thanks for letting me know.
