### ISSUE TITLE
Can't add different citations with the same title

### ISSUE THREAD

**Issue by chrisaldrich** [dsifford/academic-bloggers-toolkit#161]
**ABT Version:** 4.4.0

**PHP Version:** 5.6

2016 (child theme with few modifications)

**Plugin List:**
IndieWeb Plugins, but likely not the issue

Google Chrome: 53.0.2785.116 (Official Build) m (32-bit)

**Expected behavior:**
Put in several book citations with the same title, but different authors/publishers and expected to list them separately.

**Actual behavior:**
Citations with the same title name as those previously entered seemed to be rejected and were cited as the original book with that title instead.

**Console messages:**
```js
Uncaught TypeError: Cannot read property '0' of undefined
/wp-content/plugins/academic-bloggers-toolkit/lib/js/tinymce/components/reference-window/index.js:2 Uncaught TypeError: Cannot read property '0' of undefined
```

**Additional Notes:**
(TL;DR: It seems like I can't cite five different books which all have the same title.)

Is it possible that the location you're adding the citations to prevents duplication by rejecting titles with the same name even if the other meta data is different? And then potentially defaulting to the prior citation with that title? I've got several books with the title: Complex Analysis (see http://boffosocko.com/2016/07/25/introduction-to-complex-analysis-ucla-extension/) but can only seem to add one of them. If I add some additional text to other citations with the same title I don't seem to have the same problem. It also appears that if I don't capitalize one of the letters in one of the titles then it gets added as a separate citation and the formatting output of the style handles the capitalization properly.

p.s. Unrelated, but I LOVE the manifesto/philosophy of this plugin!

**Comment by dsifford** [comment]
Hi there,

> Is it possible that the location you're adding the citations to prevents duplication by rejecting titles with the same name even if the other meta data is different? 

This is precisely correct. That happens [here](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/src/lib/js/reference-list/Store.ts#L24-L28). I had a feeling this might eventually become problematic. 

The good news is that I'll be able to fix this quite easily. I'll likely just add in a check for author names along with the title and that should be enough to allow for the addition of items with the same name, but prevent duplicate items from being added.

Expect the fix on the next plugin update 👍

**Comment by dsifford** [comment]
@chrisaldrich Just finished an update that should handle this issue, but I wanted to make sure my logic is correct.

In the current version, a citation is marked as a duplicate and "intercepted" if just the titles match.

In the update, I added an additional "deep equality" check that runs if the titles match. Basically, once it's found that the titles match, if any additional field matches exactly, the citation is deemed a duplicate and intercepted. 

Do you see a problem with this?

Curious to hear your thoughts 👍

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dsifford/academic-bloggers-toolkit/issues/161#issuecomment-248747889" class="u-in-reply-to"></a>@dsifford My case will not likely be seen frequently in the first place, so I suspect that your fix should handle the largest number of cases.  I don't think one would ever(?) face the issue with respect to journal articles and it's probably only books where it may crop up.  In most modern book titles it's relatively infrequent that books will have the same title (usually for marketing purposes) but it may happen in cases like mine here, where some of the texts are older. 

The only other potential issue I might see is if someone were doing an analysis of multiple editions of the same book by the same authors and they wanted to cite them all separately.  In this case, possibly saving the ISBN field as the unique identifier for the book may be more useful, though it might not differentiate between slightly different "updates" (or corrected versions) of some text editions. (Off hand I know that Springer will often release moderate updates--usually with corrected typos--of a particular edition of a textbook without changing the edition number or the ISBN and some might want to potentially cite slightly different corrections of the same edition of a book.

There may also be edge cases in which one might want to separately cite a pre-print of a journal article (an early draft, on arXiv.org as an example) and then separately cite the final published article with potential updates. You'll then also likely run into this type of matching issue where you'll have the same title and authors but different publications with different dates.

If you want to get into super-edge-cases, there are some areas of scholarship in which one may also be studying time-varying versions of texts as in the Roman De La Rose Project [http://romandelarose.org/] and one may wish to cite the same textual source in which all the meta data is the same between them with the exception of the date of publication (or possibly the current owner/institutional holder when the text is very rare). I suspect in these cases a reasonable portion of the written analytical text will be devoted to the provenance of such texts to differentiate them in greater depth than would be done in a typical footnote.

I highly suspect that your proposed fix will handle the largest majority of cases as I can't think of an actual real-world example of any of the edge cases I mention in the preceding three paragraphs other than the Roman de la Rose project.
