### ISSUE TITLE
Tooltip in different browsers

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#17]
I haven't installed your 2.4.0 update yet, but this issue probably still applies.  No tooltip shows when I use Firefox or IE.  I tested this with some online browser comparison tools, so this does not seem to be an issue with my local machine as far as I can tell.  I tested the following URL:
http://www.earthmedresearch.org/wordpress-resources-at-siteground/
Works fine in Chrome, which is what I use, so I did not notice the issue until now.  I didn't test any other browsers besides these three.

**Comment by dsifford** [comment]
@metallikat36 Great catch! Not sure why that is. I'll download firefox tomorrow and see if I can write a polyfill for this. 👍

**Comment by dsifford** [comment]
@metallikat36 - Update: Found the error. Gonna do some PHP rewriting and it should fix it. 

Thanks for letting me know about this.

**Comment by dsifford** [comment]
Fixed fac9e326eeebffeac2a1c5e7aba49a082269a301 👍
