### ISSUE TITLE
Bug: Default Citation Style Does not Change

### ISSUE THREAD

**Issue by cwbullet** [dsifford/academic-bloggers-toolkit#182]
**ABT Version:** 4.4.4

**PHP Version:** 5.5.38

**Theme:** MH Newdesk

**Plugin List:**
Academic Blogger's Toolkit	
Ad King Pro
Akismet
Categories Images	
Cleverness To-Do List	
Contact Form 7	
Content links
Duplicate Page	
Fancy Lightbox	
Google Analytics Counter Tracker
Image Watermark
Jetpack by WordPress.com
Post Type Switcher
Rating-Widget: Star Review System (Premium)
Recipe Schema Markup
Review Content Type
Social Pug
Symple Shortcodes
Tiled Galleries Carousel Without Jetpack
Ultimate Widgets	
Widget Importer & Exporter	
WP Broken Link Status Checker	
WP Edit Pro	
WP Instagram Widget modified by GbThemes	
WP Meta SEO
Yet Another Stars Rating
Zedity

**Expected behavior:**
Setting Default Citation Style expected to be default in all new posts. 

**Actual behavior:**
When I change the Default Citation Style to Chicago, it appear to save it in the settings and comes up as having been change on reload.  Unfortunately, if start a new post, it reverts to the "American Medical Association" in all new posts.  If I change it in the post, it keep the chosen format for that post.  

**Console messages:**
None
// Paste messages here
None

**Comment by dsifford** [comment]
Thanks for the report. That's definitely not what's supposed to happen. I'll check this out a bit later today and see if I can fix.

One thing I will mention: Changing the default citation style will have no effect on posts that already exist with citations in them. It will only set the default style for all new posts (from your comments, I have a feeling that you already knew this, but just wanted to make sure).

Keep an eye on this thread for updates 👍

**Comment by dsifford** [comment]
@cwbullet This works as expected for me.

Any chance you might be able to make me an account on your site so I can try to reproduce the issue there?

**Comment by cwbullet** [comment]
ok.  I did.

walkingoffpounds.com
login: testme
password: TestMeNow2016!!%%GG

**Comment by dsifford** [comment]
Cool, I'll check it out now.. 

PS: I edited your comment to remove the password.

**Comment by dsifford** [comment]
@cwbullet Are you having server issues? Your site load speed is at a crawl. Who is your hosting provider?

**Comment by dsifford** [comment]
Also, I just logged in and opened a new post. It looks like the default is set to Chicago. Is this not the case for you?

**Comment by cwbullet** [comment]
It works now.  No sure what we did.  Thanks

**Comment by dsifford** [comment]
Great! Glad to hear that.

It may have just been your browser caching the AMA format option. No way to know for sure.

If you run into any other issues, please let me know! 😄
