### ISSUE TITLE
Webpage Citation Issue

### ISSUE THREAD

**Issue by jhcarrell** [dsifford/academic-bloggers-toolkit#184]
**ABT Version:** 4.4.4

**PHP Version:** 5.4.42

**Theme:** Juster

This is concerning webpage citations that have no known published date.  When using the manual add feature, Date is a required field and will not accept anything but the predefined date formats.  However, for the sake of accuracy it would be useful to be able to enter n.d. if the published date is unknown.

Do you have any suggestions on how to handle this issue?

**Comment by dsifford** [comment]
@jhcarrell Good point. I hadn't considered that possibility.

I'll remove the requirement from the next release. Thanks for the feedback. 👍

**Comment by dsifford** [comment]
@jhcarrell Pushing the update now.

Hopefully this works well for you 👍

**Comment by jhcarrell** [comment]
Thanks, I'll update and check it out.
