### ISSUE TITLE
Footnote text in addition to citation. 

### ISSUE THREAD

**Issue by scalice** [dsifford/academic-bloggers-toolkit#186]
First, I *love* the plug-in. 

I'm using the plug-in for writing in the humanities and we routinely have extensive footnote text in addition to the citation. 

For example, my footnote would read "On the idea of hidden transcripts, see Scott1990." Is there a way I can incorporate this text with ABT? Perhaps I'm missing something obvious, but I don't see how to do this at present.

Thanks.

Joseph

**Comment by dsifford** [comment]
Thanks for the feedback. Glad you like it!

Give this a look and let me know if this is what you're describing: https://github.com/dsifford/academic-bloggers-toolkit/issues/155#issuecomment-247125334

**Comment by scalice** [comment]
This may be a solution, although I'm not entirely certain how to implement it successfully. 

For my minimal example, if I am understanding correctly, I would have two entries. 

The first, Generic (text), would read "On the hidden transcripts, see"

And the second, Book, would "James C. Scott, _Domination and the Arts of Resistance_, Yale University Press (1990). 

I have combined both citations into a single footnote, but the output in both Chicago and APA, reads 

"“On the Idea of Hidden Transcripts, See,” n.d.
Scott, James C. Domination and the Arts of Resistance: Hidden Transcripts. Yale University Press, 1990."

It treats the generic text as a separate entry with a date, etc.

Also this is a very simple sample footnote. My other footnotes can have more complicated interspersing of text and citation. 

Any thoughts?

Your help is much appreciated.

**Comment by dsifford** [comment]
If I'm understanding you correctly, it seems like you want to prepend a citation with the text "On the hidden transcripts, see". 

The resulting inline citation would then be `On the hidden transcripts, see James C. Scott, Domination and the Arts of Resistance, Yale University Press (1990)`

Is that correct?

Wouldn't the text that you're wanting to prepend be implied, given that the inline citation would be falling directly after (what I can only assume would be) the section talking about hidden transcripts?

This wouldn't be something that I'd be able to add in, unfortunately. The goal is to keep the plugin 100% compliant with the Citation Style Language specification.

**Comment by scalice** [comment]
That's about the case, I was describing, but perhaps I can give a better example so it doesn't seem so trivial.

I have a footnote which reads: 
"This manuscript was translated and edited by Encarnacion Alzona as Encarnacion Alzona, ed., Julio
Nakpil and the Philippine revolution (Makati: Carmelo & Bauermann, Inc., 1964). Images of Nakpil’s handwritten manuscript and score are included. Relevant material can be found on 12, 45-49, 66 and the score of Pamitinan on 109ff."

As you can see interspersed between the prepended and postpended text is a citation -- Alzona1964.

The heart of my question is, is it possible to perhaps manually edit the inline citation to include this text, or is there some other way to include it in the citation / footnote?

**Comment by dsifford** [comment]
@scalice It's not possible to manually edit either the inline citation text or the bibliography/footnote text because they are all generated/regenerated continuously as the document is edited and additional citations are added in.

No details of the actual final citation exists in memory. Instead, all citations are generated using CSL XML (basically the blueprints for how the final citation needs to look) and a JSON store of each citation (the actual citation "parts").

Have you considered just using a style like APA 5th edition? If you chose that route, then your "generic" citation above could read `This manuscript was translated and edited by Encarnacion Alzona as (Alzona 1964). Images of Nakpil’s handwritten manuscript and score are included. Relevant material can be found on 12, 45-49, 66 and the score of Pamitinan on 109ff.`

**Comment by scalice** [comment]
That's helpful. I can use a parenthetical citation style like APA 5th and the Generic citation to create what I need. Thanks very much.

**Comment by dsifford** [comment]
Great. Sorry I wasn't able to be more helpful.

Thanks for the feedback. 😄
