### ISSUE TITLE
Indentation issue

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#19]
Hi Derek,

I finally updated the plugin, and now it totally doesn't work.  =)  But one thing at a time!  The first major issue is that any new post I write is indented:
http://www.earthmedresearch.org/testing-citations-indentations/
If I deactivate the plugin and reload this page, the indentation will no longer be there.  Any ideas?  

Thanks,
David

**Comment by metallikat36** [comment]
Oh I think some of the other issues I was seeing are fixing themselves...I'll let you know in more detail in the next day or two.

**Comment by metallikat36** [comment]
Oh, dang..now once I have added at least 1 citation/reference to the post, the indenting disappeared.  Guess this one fixed itself.  So downgrade this to just an FYI.

**Comment by dsifford** [comment]
@metallikat36 Thanks for letting me know about this. It probably has to do with how the plugin  searches and tags or ordered lists if no smart bibliography is found..

I'll see if there's any way I can make it more accurate next time i get some free time

**Comment by metallikat36** [comment]
Here is some more specific symptoms of this issue.  On the following page:
http://www.earthmedresearch.org/newsletter/
you can see the indentation that should not be there.  But also the entire first paragraph of the page disappears, as long as the plugin is active.

**Comment by dsifford** [comment]
Thanks for the test run.. It looks like it is doing exactly what I thought it was. I'll see if I can work on a fix later this afternoon

![image](https://cloud.githubusercontent.com/assets/5240018/14411686/71f5292a-ff1d-11e5-8530-c3fec6b6f96d.png)

**Comment by dsifford** [comment]
Fixed: e8c1de463e51715a8afdc3c19ca869a7168b452f
