### ISSUE TITLE
Some stray references aren't being properly cleared from document. (ending up as the first line of the document)

### ISSUE THREAD

**Issue by dsifford** [dsifford/academic-bloggers-toolkit#208]

**Comment by CyanoKobalamyne** [comment]
I have the same bug.

Steps to reproduce:
1. Create a new page.
2. Add a citation with in-text reference.
3. Publish the page.
4. Delete the in-text citation from the text.
5. When you press Update, the citation will magically appear at the beginning of the document.

**Comment by dsifford** [comment]
@CyanoKobalamyne Does the "workaround" clear the citation, or is it still happening.

It's documented somewhere but, in short:

To delete a single citation instance from the document, you have to delete it using the backspace key as you probably have been doing, and then hit the "Refresh Reference List" button in the menu to make the plugin aware of your changes.

I'll be working on a better solution for this soon.

Let me know if that works.

**Comment by CyanoKobalamyne** [comment]
Yes, refreshing the reference list solves the problem, thanks!
