### ISSUE TITLE
4.6.0 CSS bugs

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#209]
I think the update messed up some CSS stuff. My original override CSS was:

```
.abt_cite {   
color: #ea6900;
font-weight: bold;
font-size: 17px;
}

.abt_tooltip{
color: white !important;
background: black !important;
border: solid 2px;
border-color: #ea6900;
z-index: 10000002;
}

.abt_arrow_up { 
  border-color: transparent transparent black !important; 
z-index: 10000001;
} 

.abt_arrow_down { 
  border-color: black transparent transparent !important; 
z-index: 10000001;
}

.abt_tooltip_touch_close{
z-index: 10000003;
}

#abt-smart-bib>h3 {
    font-size: 22px;
    left: 10px;
    position: relative;
}

}
```

So here is what I note:

1.  The selector .abt-cite still works. So that is backwards compatible. But trying the new selector .abt-citation loses the CSS. 

2. The tooltip only appears on click. It used to be on hover. Confirm this is intended? Personally, I preferred the hover on PCs, but no big deal. 

3.  The old selector .abt_tooltip does not work. Switching to the new .abt-tooltip does work. 

4. Furthermore, .abt-tooltip seems to have any inputted z-index apply to the close button as well. I don't think this was the case with the old .abt_tooltip. That is fine with me, but it is potentially confusing since you also provide a separate selector to the close button. But then again, having the two linked together does seem to guarantee that the two never end up with different Z-indexes, which is desirable. And it seems a tie-break in z-index defaults to the close button being on top, which is good. 

5. The old .abt_tooltip_touch_close does not work. Nor does the new .abt-tooltip__close-button. But with the aforementioned fix, I just deleted this code. All I needed was a z-index set, but if someone else wanted to change the color of the close button or something, they may not be able to do it. 

6. The old .abt_arrow_up and .abt_arrow_down do not work. Nor does the new .abt_tooltip__callout. I can't find a way to select the triangle callout shapes,

7. The old #abt-smart-bib>h3 works. The new .abt-bibliography__heading does not. 

I did not test  anything about footnotes, or the other two bibliography selectors.

**Comment by dsifford** [comment]
@metallikat36 

1. Have you tried clearing your cache and reloading the page? That might fix. If that doesn't can you tell me exactly where it's not working?

2. Correct. I've made a switch to only show the tooltips on click because some older browsers don't work with the hover event listeners. (IE specifically).. Actually, IE still doesn't work, but I'm working on fixing that.

3. Ah shoot... I forgot that users might have style rules for the old tooltips. You're correct. I didn't keep those backwards compatible because they aren't something that lives beyond the life of the tooptip (the other css classes are permanently saved to the post so they were much more prudent to make backwards compatible).

4. Correct. The tooltip and the close button will move together across the z-axis.

5. I've added examples on how to style the new tooltips on the options page. Did you see those? It outlines how to style the close buttons as well.

6. See above.

7. See above.

Footnotes and static bib selectors are unchanged. Those were already set using best-practices. 

Let me know if those examples were able to help or not.

**Comment by metallikat36** [comment]
1. Here is where:
http://www.earthmedresearch.org/neuropathy-review-natural-treatments-drug-risk-factors/
Note the inline citations are orange and larger font than the default. This is with the old .abt_cite selector. If I switch to using .abt-citation, it loses it. If I switch back again, it regains it. I have disabled cloudflare and cleared my caching plugin, so it's not cache related.  Trying the following example code verbatim also does nothing for me:
```
.abt-citation {
    color: gold;
    display: inline-block;
}
```
So something is going on here it seems. 

2. Okay.

3. Okay. No fix needed for me personally, but just making sure you are aware. 

4. Okay.

5. Okay.

6. Thanks, that works. I overlooked the examples you gave. 

7. Doesn't seem to work. I tried the example code:
```
.abt-bibliography__header{
color: gold;
}
```
No effect. Also, FYI, you have a typo on the backend that says .abt-bibliography__heading instead of "header".

**Comment by dsifford** [comment]
The issue with your inline citations is that you need to be targeting the superscript element.

So, in other words:

this...
```css
.abt-citation {
    /* style changes */
}
```
needs to be this...
```css
.abt-citation sup {
    /* style changes */
}
```

Does the example code say to use `.abt-bibliography__header`? If so, then _that's_ the typo. The correct selector is `.abt-bibliography__heading`.

**Comment by metallikat36** [comment]
I tried
```
.abt-citation sup {
color: #ea6900;
font-weight: bold;
font-size: 17px;
}
```
You can see on my site at the moment that the CSS is not there. So this also does not work.

The section called "CSS Selectors used in this plugin" says ".abt-bibliography__heading", whereas the example code uses ".abt-bibliography__header".  So the example code does have a typo.

**Comment by dsifford** [comment]
Ah, now I see.

You'll have to keep the old selectors as well as add in the new selectors for the citations. This is because posts that you've created prior to the update will still have the old selectors. 

so, in other words...

if this is what your old selectors looked like prior to the update...
```css
.abt_cite {
    color: gold;
    display: inline-block;
}
```

you need to just do this to it...
```css
.abt_cite, .abt-citation {
    color: gold;
    display: inline-block;
}
```


Thanks for pointing out the discrepancy in the examples. I just fixed that.

**Comment by metallikat36** [comment]
Oh okay. If I refresh the old posts biblios, will that fix it?

**Comment by dsifford** [comment]
Yep, that will also

**Comment by metallikat36** [comment]
Refreshing the posts have now made the new bibliography selectors work, but the ".abt-citation sup" selector still does now work on these existing posts.

**Comment by metallikat36** [comment]
Making a new test page, the .abt-citation sup selector does work. So it is an issue with previously existing posts.

**Comment by metallikat36** [comment]
If its not fixable, I can just republish those posts as new posts. I can do that since I only have a couple, but some other uses may not be able to do that.

**Comment by metallikat36** [comment]
Also, using the old selector ,abt_cite still does not give full control for existing posts. For example, I am unable to make the inline citations have a color when hovering. Neither of the following code blocks works for that:

```
.abt_cite:hover{
color: green;
}
```
```
.abt_cite sup:hover{
color: green;
}
```

**Comment by dsifford** [comment]
Can you link me to a page that isn't working and tell me what you're trying to set?

**Comment by metallikat36** [comment]
Here is a pre-existing post where I want to set the inline citation style:
http://www.earthmedresearch.org/neuropathy-review-natural-treatments-drug-risk-factors/
The new selectors "abt-citation" and "abt-citation" do not work. The old selector ".abt_cite" does work for changing the style, but does not seem to work for changing the hover color of the inline citations.

A new page from scratch works fine with the new selectors:
http://www.earthmedresearch.org/abt-test/

**Comment by dsifford** [comment]
To change the style for all posts, existing and new, you need to add coverage for the outdated and new selectors to your stylesheet.

So, in other words, assuming you want the inline citation to be bold and orange, set your css to this:

```css
.abt-citation sup, .abt_cite sup {
  color: orange;
  font-weight: bold;
}
```

that will cover everything

**Comment by metallikat36** [comment]
That code would work mostly, but like I said, there is still no way that works to make the hover color different. For example, the following doesn't do it:

```
.abt-citation sup:hover, .abt_cite sup:hover{
color: #ffb200;
}
```

I don't need a fix for this, since I am just going to make new posts, but this might be an issue for otheres.

**Comment by dsifford** [comment]
Give me just a second and I'll look at that specifically

**Comment by dsifford** [comment]
The above selector you pasted doesn't work for you? Looks like it works fine on my end.

**Comment by metallikat36** [comment]
That's correct. It does not work on pre-existing posts. Of course, it does work on a brand new post.

**Comment by dsifford** [comment]
If I copy and paste that to the pre-existing post that you linked it works. I'm not sure why it's not working for you.

**Comment by metallikat36** [comment]
hold on gimme a minute

**Comment by metallikat36** [comment]
Okay crazy, now it works. Seriously it was not working before though. 

So ya, then the way to keep old posts just to keep the old selectors in addition. Everything sgood.

**Comment by dsifford** [comment]
Sweet! Sorry for the trouble
