### ISSUE TITLE
Add ability to add literal author name (for publication collab groups, etc)

### ISSUE THREAD

**Issue by dsifford** [dsifford/academic-bloggers-toolkit#215]

**Comment by Antimatzist** [comment]
Just want to leave a note that this would be a really awesome feat. E.g., if you want to cite software, you now have to find a way to work around the "surname and name are both mandatory" feature which leads to very confusing citations (e.g. "Super Mario World. Inc., Nintendo [...]" as a silly example. You have to think about it while importing, as ABT doesn't allow manual editing in this cases; or you need to include a very ugly empty space which will still have a comma.

dl;dr: Just making the name mandatory and the surname optional would be very awesome.

**Comment by dsifford** [comment]
It's definitely on the todo list. Thanks for the reminder 👍

**Comment by dsifford** [comment]
@Antimatzist Let me know what you think of this... 

![image](https://user-images.githubusercontent.com/5240018/34023137-3b27cf24-e111-11e7-8e22-cc13896b0117.png)

Added a new button next to the remove button that toggles between the "surname, given name" form and the "literal name" form.
