### ISSUE TITLE
PageSpeed Insights Notifications

### ISSUE THREAD

**Issue by noreliacob** [dsifford/academic-bloggers-toolkit#218]
**ABT Version:** 4.7.0

**PHP Version:** 5.6

**Theme:**News7paper by tagdiv

PageSpeed Insights gives me a poor score for the new website and part of the suggested fixes are related to your plugin. Can you, please, suggest a solution? Thank you. https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.semneletimpului.ro%2F&tab=desktop …
Flag this message  Delete this message

**Comment by dsifford** [comment]
@noreliacob Would it be possible to make me a temporary account on your site so I can see what's going on?

Not sure why your theme triggers `is_singular()` on your homepage. That shouldn't happen.

Still investigating....

**Comment by dsifford** [comment]
![image](https://cloud.githubusercontent.com/assets/5240018/19912604/006d45f2-a072-11e6-9975-991ca9cf0bb6.png)

Not much of a speed improvement, but I'll include this in the next release @noreliacob

**Comment by noreliacob** [comment]
Thank you.
Sorry for not answering promptly to your message. It was night time here.

Looking forward to update your plugin.

Greetings,
Norel Iacob / redactor-șef
Revista Semnele timpului
www.semneletimpului.ro

**Comment by dsifford** [comment]
@noreliacob You're very welcome. If you have any other suggestions, please don't hesitate to let me know.

Also, If this fix works well for you and you're overall enjoying the plugin, would you mind leaving a review on wordpress.org? I received another (somewhat suspect) negative review this evening and it's really hurting the overall plugin rating 😞 

Thanks so much

**Comment by noreliacob** [comment]
Sure. My pleasure.

Norel Iacob / redactor-șef
Revista Semnele timpului
www.semneletimpului.ro
