### ISSUE TITLE
Reference List is blocked

### ISSUE THREAD

**Issue by HoussenMoshine** [dsifford/academic-bloggers-toolkit#220]
**ABT Version:** 4.7.0

**PHP Version:** 5.6.4-4ubuntu6.4

**Iconic:**

**Plugin List:**
-Academic Blogger's Toolkit
-Add Meta Tags
-Advanced Custom Fields
-Akismet
-Amazon Web Services
-AmazonJS
-AMP
-AP HoneyPot
-Better WordPress Google XML Sitemaps
-BNS Featured Category
-Breadcrumb Trail
-Fast Secure Contact Form
-Google Analyticator
-Google XML Sitemaps
-Importateur WordPress
-IP Geo Block
-Jetpack par WordPress.com
-Markup (JSON-LD) structured in schema.org
-Page Builder par SiteOrigin
-Postman SMTP
-Schema
-Simple Drop Cap
-SiteOrigin Widgets Bundle
-Table of Contents Plus
-UpdraftPlus - Sauvegarde/Restauration
-User Switching
-W-3 Total Cache
-Wordfence Security
-WP Adverts
-WP Offload S3 Lite
-WP-Polls
-WP-SpamShield
-Yet Another Stars Rating

**Browser:** Google Chrome (Version: xxx)

****

**The Menu Reference List is blocked in a kind of loop and don't show any options**

**Console messages:**

JQMIGRATE: Migrate is installed, version 1.4.1

// Paste messages here

I  think it's related to Wordfence or IP Geoblocking. But the problem is still there after disabling this plugin.

**Comment by dsifford** [comment]
Hi @HoussenMoshine 

I'm not able to say for sure, but I'm nearly certain your issue is that you have a plugin conflict somewhere, given the amount of plugins that you have installed.

Can you try disabling all of your plugins but ABT and see if it works then? If so, reenable your plugins sequentially, one at a time, and let me know which one is creating the conflict.

Thanks

**Comment by HoussenMoshine** [comment]
Hi @dsifford, i have found the conflicting plugin. It's [SiteOrigin Widgets Bundle](https://wordpress.org/plugins/so-widgets-bundle/). For now, i have disabled it.

**Comment by dsifford** [comment]
Thanks @HoussenMoshine 

I'll look into the conflict soon.

**Comment by dsifford** [comment]
@HoussenMoshine 

Finally got around to testing. The plugin seems to be working fine with `SiteOrigins Widgets Bundle` installed. Perhaps their latest update fixes the issue? Looks like they pushed one 6 days ago.
