### ISSUE TITLE
Bibliography heading doesn't change.

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#229]
**ABT Version:** 4.7.1
**PHP Version:** 5.6.27
**Theme:** Dazzling

**Plugin List:**
Academic Blogger's Toolkit
Ajax Search Lite
All In One WP Security
Disqus Conditional Load
Easy Google Fonts
Give - Donation Plugin
Hyper Cache	
Jetpack 
Popular Posts Tabbed Widget for Jetpack	
PopupAlly	
Social Popscroll	
Super Socializer
UpdraftPlus - Backup/Restore	
WP Smush	
Yoast SEO	

Tried to change the Bibliography heading text from "References" to "References (click to expand)".

Text did not change. I ruled out caching issues. I also tried all three different Update buttons. 

**Console messages:**
![image](https://cloud.githubusercontent.com/assets/17968340/20166674/3734f77e-a6cb-11e6-810a-1281d7aa0294.png)

**Comment by dsifford** [comment]
@metallikat36 You're correct that it's not caching.

Setting the heading using the heading option will only change headings for posts created after the heading is set. To get the new option to apply to past posts, you'd have to open the post editor for each post and hit save again.

It's a necessary evil. Setting headings using some other "just in time" method would jeopardize the longevity of the posts. Doing it this way ensures that once your post is saved, your bibliography and citations will not be affected unless you explicitly choose to affect it.

**Comment by metallikat36** [comment]
Problem solved.

**Comment by dsifford** [comment]
Great!

With the above said: You can get away with setting the heading for all posts if you do it with a clever css `:before` selector. However, that won't apply to you if you've got the toggle option set.
