### ISSUE TITLE
Outgoing links and SEO

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#23]
Just wondering if having virtually all my links ultimately ending up in a tooltip would have any adverse effects on SEO?  Maybe search engines don't see those links?

Actually, now it occurs to me the actual links are in the references list as well, so I suppose there should be no issue.  Unless collapsing a reference list somehow hid those links in the references from search engines.

**Comment by metallikat36** [comment]
Also, you might want to reflect on how you have implemented target=blank links.  According to this guys plugi description, there are good and not-so-good ways of opening links in new windows as far as SEO goes.  It's not something I understand, but thought I would bring it up.  
https://wordpress.org/plugins/open-external-links-in-a-new-window/

**Comment by dsifford** [comment]
Good thought, though I don't think there really is any hit in using `target="_blank"` on external URLs. SEO for individual sites take somewhat of a hit if their own internal links to other pages within their own domain are targetless, but external links make no difference. This is so the search engine can travel through the flow of the site and generate a sitemap for itself to index.
