### ISSUE TITLE
Feature request: Import *.bib files

### ISSUE THREAD

**Issue by jugdemon** [dsifford/academic-bloggers-toolkit#233]
I would highly appreciate it if it was possible to import bib-files to load references.

**Comment by dsifford** [comment]
Hi @jugdemon 

Can you explain where it is that the `.bib` files are coming from? Are you exporting from a reference manager? Some online source?

Thanks!

**Comment by jugdemon** [comment]
There are several sources. I have them on my computer from projects (the accompanying latex files).
Another source would be the export button from google scholar.

I usually collect references as bibs so I can easily use them with latex. So I have many of them around.

The features that would be useful would be either to provide a bib-file or to paste a bib-entry into a text field that is then transformed into the reference.

Does that make sense?

**Comment by dsifford** [comment]
Yep, makes sense.

This feature already exists for `.ris` files, so my question was really just trying to see if you would be able to export in that format vs `.bib`. That solution would work for google scholar, but unfortunately not for scattered `.bib` files existing on your disk.

The immediate issue with adding support for `.bib` is that it would take a significant amount of work to do it. `.bib` works wonderfully for latex, but unfortunately it's quite a pain when it comes to extracting metadata.

My suggestion to you for the immediate future would be to export in `.ris` when able or to use some other online service for converting your `.bib` files to `.ris`.

I'll take a look and see if I can find an easy way to add support for this. If I can't find one, I'll keep this on the todo list, but won't be able to devote the time to adding support for it until I can allocate a large chunk of time for it in my regular schedule.

**Comment by jugdemon** [comment]
I like your plugin and I would consider helping, but I haven't messed around with typescript (though I have a fair share of javascript experience) and at the moment I won't have time.

Would you consider using external libraries? Such as this one: https://github.com/chbrown/tex

**Comment by jugdemon** [comment]
Thanks for putting it on the list of consideration. I understand the problems as I maintain a medium-sized framework and it is causing trouble to have outside dependencies.

**Comment by dsifford** [comment]
Update: found one I think I like https://github.com/ORCID/bibtexParseJs

**Comment by dsifford** [comment]
Just finishing up an early working version of the bibtex importer @jugdemon 

Still need to add tests for it, but if you feel like trying it out, you can do so by pulling the `next` branch.

BibTeX will never be as good as RIS. There's always going to be some annoyances. For example: You'll never be able to use journal abbreviations (which is a requirement for AMA format).

**Comment by jugdemon** [comment]
Thank you for giving it a shot. I appreciate it a lot that you expand the toolkit to accommodate a wide range of academic writers.

Since I don't use AMA I will have no such problems. I think it is good, that you implement bibtex nontheless. I think people who use AMA will have no problems because they won't use bibtex anyway and people (like me) who use bibtex will not use AMA. I am going to check it out later and thanks again for putting in the effort.

**Comment by dsifford** [comment]
Let me know how this works for you @jugdemon

**Comment by jugdemon** [comment]
Thank you very much. This is awesome. It works well most of the time. I made a new issue #258 to cover a minor problem.
