### ISSUE TITLE
Circle Arrows is back

### ISSUE THREAD

**Issue by cwbullet** [dsifford/academic-bloggers-toolkit#257]
**ABT Version:** 4.8.0

**PHP Version:** 5.6

**Theme:** 

**Plugin List:**
- Plugin 1: About Me Page
- Plugin 2: About Me Page
- Plugin 3: Academic Blogger's Toolkit	
- Plugin 4: Ad King Pro	
- Plugin 5: Akismet
- Plugin 6: amr shortcode any widget
- Plugin 7: Calorie Calculator
- Plugin 8: Categories Images
- Plugin 9: Cleverness To-Do List	
- Plugin 10: Contact Form 7
- Plugin 11:  Content links
Count Per Day
Dai Pho Keywords Generator
Duplicate Page	
Easy Nutrition Facts Label
Fancy Lightbox
Google Analytics Counter Tracker
Inline Related Posts
Jetpack by WordPress.com
Let's Review
List category posts
Post Type Switcher
Print Friendly and PDF
Rating-Widget: Star Review System (Premium)
Recipe Schema Markup
Schedule Posts Calendar
ShortPixel Image Optimizer
Simple Pull Quote
Social Pug
Special Text Boxes Pro
Symple Shortcodes
Theme Check
Ultimate Widgets
Universal Star Rating	
WP Broken Link Status Checker
WP Edit Pro
WP SEO Plugin Optimizer
Zedity Premium

Delete this - I got it to work.

**Comment by dsifford** [comment]
@cwbullet I'm not sure what this means. Can you elaborate?

**Comment by cwbullet** [comment]
I fixed it.  False alarm.  I tried everyone but forgot the empty the cache on my browser.
