### ISSUE TITLE
Misformating of special characters in latex bibtex imports (alpha)

### ISSUE THREAD

**Issue by jugdemon** [dsifford/academic-bloggers-toolkit#258]
When testing the bibtex alpha #233 I found that special characters formated for latex are not parsed correctly. For instance Techné remains as Techn{\{}{’{e}}{\}}. 

I understand that you don't want to implement or reference a latex parser, so I would suggest the ability to edit inserted references. I hope I am not blind and missed the "edit existing references"-button, but I think it would be fair to just click on a (new) menu button for an entry (see Figure below for a mock-up) to have the option to edit details or remove the reference from the text (I noticed that I can't delete references once they are inserted, if it is a bug, I will create a new issue). 

![new_button](https://cloud.githubusercontent.com/assets/4126068/20706217/73d493d2-b626-11e6-9c10-b227ef5d2c8a.png)

**Comment by jugdemon** [comment]
I just noted that #208 explains the removal of dangling references in the text. However, I still think it would be useful to be able to manually remove a singe reference.

**Comment by dsifford** [comment]
@jugdemon Can you send me a copy of the bibtex file that triggers this issue so I can play around with it.

Editing single references is a lower priority right now than figuring out a way to remove single references. Perhaps in the near future though I can look into that.

For the time being, I can probably just write in something that strips the latex out and leaves behind the raw text.

**Comment by jugdemon** [comment]
@dsifford here is the bibtex entry from the reference above:

`@article{ropohl1999,
author = {Ropohl, G{\"{u}}nter},
journal = {Techn{\{}{\'{e}}{\}}: Research in Philosophy and Technology},
number = {3},
pages = {186--194},
title = {{Philosophy of socio-technical systems}},
volume = {4},
year = {1999}
}`

**Comment by dsifford** [comment]
@jugdemon Just now looking into this. It's going to require a huge transform of the string in order to render appropriately. 

Two options:
1. I can fix this now by just stripping all instances of `{`, `}`, and `"` (leaving `'e` in place in the journal name and call it good.
2. You give me an exhaustive list of all simple accented letter transforms so that I can apply the appropriate transformation to all of them.

I'll leave that to you. I'll need a large list of accented letters used in various contexts if you choose option 2.

**Comment by dsifford** [comment]
Option 3: I skip it altogether and just work on adding an "edit" citation feature.

**Comment by jugdemon** [comment]
I think unless you implement a latex engine the second option will always have that one case where somebody comes to you complaining about a missing character. So for the sake of your sanity (and the cleanliness of your code unless you actually want to parse latex) I would forego the second option.

The first one doesn't leave me satisfied (I would rather manually edit the bib file than having random accents lying left and right of letters). I think it is a bad choice as well.

I think this will be implemented with minimal effort for you by working on edit citation (which would probably not only make me happy but many others as well judging by the other issues opened her). I get that it might be a longer overhaul to get there for you so I understand if you want to take your time on it. But I rather have an editable citation sometime in the future where I can fix type-setting manually over fake/incomplete/wrong type-setting right now.

**Comment by dsifford** [comment]
Got it. Sounds good. Closing this for now then. Will get started on the edit citation feature as time allows. Shouldn't take terribly long, so it'll probably be released in the next month or two. 👍
