### ISSUE TITLE
Journal name abbreviations

### ISSUE THREAD

**Issue by floaltvater** [dsifford/academic-bloggers-toolkit#260]
**ABT Version:** 4.8.0

**PHP Version:** 5.6.27-0+deb8u1

**Theme:** Child of Fluida theme (but same issue with Twentysixteen)

**Plugin List:**
no others activated

**Browser:** Firefox (Version: 50.0.2)

**Expected behavior:**
Abbreviated journal names for styles like AMA or APS (e.g., Phys Rev B or Phys. Rev. B)

**Actual behavior:**
Journal names are fully written out (e.g., Physical Review B)

**Console messages:**
No apparent error messages

How does your plugin handle journal abbreviations? In the CSL Visual Editor, the AMA and APS style both abbreviate journal names correctly (the former without, the latter with periods). However, selecting these styles from the dropdown, or using an uploaded csl file with the ABT plugin doesn't have the desired effect. Is the abbreviating part "outsourced" somehow? And what could be the reasons that it is not working for me/how would I debug it?

Thanks!

**Comment by dsifford** [comment]
@floaltvater Abbreviations are only carried over if the file that you are uploading has them. 

In the case of BibTeX, it never has them, so you'll never get them. RIS has them optionally.

If you get citations using the automatic lookup (using DOI, PMID, PMCID) you'll always be provided with abbreviations.

Does that make sense?

**Comment by floaltvater** [comment]
Sorry, should have mentioned that I do add the citations via automatic lookup (DOI). And it loads correctly except for the abbreviated journal names.

**Comment by dsifford** [comment]
@floaltvater Can you share a specific DOI that does this with me? Thanks

**Comment by floaltvater** [comment]
https://doi.org/10.1103/PhysRevB.94.155105

**Comment by dsifford** [comment]
Thanks... Gimmie a few and I'll check it out now

**Comment by dsifford** [comment]
@floaltvater which style are you using?

**Comment by floaltvater** [comment]
I tried it with American Physics Society, and American Medical Association, both of which should produce abbreviated journals.

**Comment by dsifford** [comment]
Aha! You've indeed located a bug.

Looks like CrossRef mislabeled one of their data fields. It should be `container-title-short`, but it's actually `short-container-title`. Tisk, tisk CrossRef!

I'll fix this and include on the next update. Thanks for pointing this out.

**Comment by floaltvater** [comment]
Sweet! Thanks for tackling this so fast and efficiently :)

**Comment by floaltvater** [comment]
@dsifford Also, maybe related to this issue (otherwise I'm happy to open a new one): Somehow the page number doesn't get transmitted. Entering the DOI results in "n.p." in the lower right in the Reference List box, and no page number shows up in the bibliography. I don't know if I just have not noticed it before, or if something changed at some point.

Let me know if you'd need any more information for that.
Thanks!

**Comment by dsifford** [comment]
@floaltvater Interesting. Can you send a couple of the DOIs you're using that trigger this?

Thanks

**Comment by floaltvater** [comment]
Across the journals that I checked, the problem seems localized to the Physical Review journals. They all show the same behavior of not producing a page number, whereas all other journals that I tried did. Here are DOIs that don't work:

10.1103/PhysRevA.94.040701
10.1103/PhysRevB.94.115134
10.1103/PhysRevB.94.155105
10.1103/PhysRevB.94.041107
10.1103/PhysRevC.94.041301
10.1103/PhysRevLett.95.135301

**Comment by dsifford** [comment]
@floaltvater Just checked. That specific journal doesn't provide a page number/range to crossref for whatever reason. Nothing I can do there. Perhaps email the journal if you find yourself citing that one often.

**Comment by floaltvater** [comment]
Oh weird. Unfortunately, I do cite that one pretty often. I'll write them and see what happens. In the meantime I'll also wait for the "edit citation" feature ;)

Thanks for looking into this!

**Comment by dsifford** [comment]
@floaltvater Sure thing.

Pushing release `4.8.1` within the next 20 minutes which will include the fix for the abbreviations. 👍
