### ISSUE TITLE
Add ability to edit references

### ISSUE THREAD

**Issue by saltiredj** [dsifford/academic-bloggers-toolkit#261]
First of all, this plug-in rocks. Seriously, it's awesome. I'm using it all the time, which is probably why I have some requests for future updates (in no particular order).

**Edit references.**
My references are imported from Endnote. I am not able to edit the reference in order to add a specific page number. I have to write something like _Smith, J. (2015). p.123_ with the page numbers outwith the created reference. (If there _is_ a way to do this, please let me know!)

**Search by ISBN**
I tend to do this via Endnote but it may be helpful to have the ability to do it within the plug-in directly.

**Only show selected reference styles**
Although the default referencing style can be set in the plugin settings, I need to use two or three different styles depending on the journal to which my article is being submitted. It would be very helpful to be able to select just the 2 or 3 I tend to use, perhaps in the plug-in settings. If this were implemented, users would only need to scroll through the whole list once in the plugin settings, select the most common referencing styles for them and then choose from a much smaller list when using the plug-in directly.

Thanks for making such an amazing plug-in, Derek!

**Comment by dsifford** [comment]
Hello again @saltiredj 😄 

Glad you're enjoying the plugin! Thanks for the kind words and great suggestions.

To address each of them individually...

### Editing references
This has been requested a couple of times. It's on my radar, but not sure when I'll get to it. Likely within a few months. (cc: @jugdemon)

### Search by ISBN
This already exists! On the "Add References" screen, hit `Add Manually` and then select "book" or "book section" and you can search by ISBN-10 or ISBN-13. 

### Only show selected styles
You shouldn't have to scroll through the styles to find what you're looking for. You can just type the name of it and it'll filter right to it! Does this not work for you?

Thanks again for the suggestions. If you continue to enjoy the plugin, please consider rating it in the WordPress plugin repository. (I've got 2 really low reviews that have dragged the entire plugin rating wayyyy down which has been quite discouraging).

**Comment by saltiredj** [comment]
Well don't I feel silly. Didn't realise I could search by ISBN that way nor did I realise I could just type the name.

Will add a review immediately  :-)

Sent from my iPhone

On 5 Dec 2016, at 19:59, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello again @saltiredj<https://github.com/saltiredj> ?

Glad you're enjoying the plugin! Thanks for the kind words and great suggestions.

To address each of them individually...

Editing references

This has been requested a couple of times. It's on my radar, but not sure when I'll get to it. Likely within a few months. (cc: @jugdemon<https://github.com/jugdemon>)

Search by ISBN

This already exists! On the "Add References" screen, hit Add Manually and then select "book" or "book section" and you can search by ISBN-10 or ISBN-13.

Only show selected styles

You shouldn't have to scroll through the styles to find what you're looking for. You can just type the name of it and it'll filter right to it! Does this not work for you?

Thanks again for the suggestions. If you continue to enjoy the plugin, please consider rating it in the WordPress plugin repository. (I've got 2 really low reviews that have dragged the entire plugin rating wayyyy down which has been quite discouraging).

-

**Comment by saltiredj** [comment]
I just realised I can include pages to my citation via the text editor (rather than the visual editor). ::smacks palm on forehead::

**Comment by dsifford** [comment]
@saltiredj Can you explain what you mean by your statement above.

If you are saying that you can edit the reference in the bibliography in the text editor, you are correct. Technically that is possible. However, those changes will be erased immediately after the next insertion or deletion of a reference because the bibliography is automatically regenerated each time the reference list is interacted with.

**Comment by saltiredj** [comment]
Oh crap. Really? Damn.

Sent from my iPhone

On 8 Dec 2016, at 17:11, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


@saltiredj<https://github.com/saltiredj> Can you explain what you mean by your statement above.

If you are saying that you can edit the reference in the bibliography in the text editor, you are correct. Technically that is possible. However, those changes will be erased immediately after the next insertion or deletion of a reference because the bibliography is automatically regenerated each time the reference list is interacted with.

-

**Comment by dsifford** [comment]
@saltiredj I'll add support for editing existing references shortly since it's now been requested on three separate occasions. Sit tight.

**Comment by saltiredj** [comment]
You, sir, are a gentleman and a scholar. 👍

**Comment by dsifford** [comment]
@saltiredj @jugdemon @floaltvater Let me know what you think of this:

![editing-references](http://i.giphy.com/3o7TKGhqEHRiU8q6Gc.gif)

There's still a bit of work to be done, but it's functional at this point. If you'd like to test it out as it currently sits let me know and I'll compile a zip that you can install.

The reference editor is triggered by double clicking on any reference in the reference list. There's not really enough real estate available to be able to put another button. Hope that works alright for you all.

(**Note:** In the example above, the bibliography is not changing after the reference is edited. I'm working on fixing that now.)

**Comment by saltiredj** [comment]
Very happy to test it for you. Thanks so much!

Sent from my iPhone

On 9 Dec 2016, at 22:02, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


@saltiredj<https://github.com/saltiredj> @jugdemon<https://github.com/jugdemon> @floaltvater<https://github.com/floaltvater> Let me know what you think of this:

[editing-references]<https://camo.githubusercontent.com/1716601cfabfd7409eb4f587209f1213375d8824/687474703a2f2f692e67697068792e636f6d2f336f37544b476871454852695538713647632e676966>

There's still a bit of work to be done, but it's functional at this point. If you'd like to test it out as it currently sits let me know and I'll compile a zip that you can install.

The reference editor is triggered by double clicking on any reference in the reference list. There's not really enough real estate available to be able to put another button. Hope that works alright for you all.

(Note: In the example above, the bibliography is not changing after the reference is edited. I'm working on fixing that now.)

-

**Comment by jugdemon** [comment]
@dsifford This looks amazing. Thank you for considering this so quickly. I will have a closer look, but I am currently clogged up with other work.

**Comment by floaltvater** [comment]
@dsifford Happy to test it out too. I'm not sure though if I can get around to it in the next couple days. But I should find some time next week.

**Comment by dsifford** [comment]
Pushing the update that includes this feature in less than 10 minutes. Let me know what you think once you get your hands on it.

Thanks

**Comment by saltiredj** [comment]
Thanks. On a train but I'll check it when I'm at hotel. Is the update via the WordPress?

Sent from my iPhone

On 12 Dec 2016, at 03:13, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


Pushing the update that includes this feature in less than 10 minutes. Let me know what you think once you get your hands on it.

Thanks

-

**Comment by dsifford** [comment]
@saltiredj Yep, pushed the update live last night 👍

**Comment by saltiredj** [comment]
Derek,


Yes, I'm on the train-it has WIFI, amazingly-and I've tried out the update. Looks great. Very easy to use and it works like a charm. Thanks so much for working on this.


However, there is one issue which still would be worth resolving - the ability to add page numbers to the reference. It is so helpful that the reference can be edited but often the imported reference from Endnote needs to have a page number in the citation, something which cannot currently be done, even with the addition of editing you've added (unless I've missed something). Being able to a reference such as (Pate 2016) to (Pate 2016:16) or (Pate 2016 p.16) would make this plug-in much more usable (in my humble opinion).


I hope that makes sense to you. There is so much potential for me to use this plug-in on practically a daily basis but, if I'm honest, the inability to add the page numbers is proving to be the one (and only!) think holding me back from going full speed with it.


I'm still going to spread the word, though! I think you're definitely onto a winner with this and you ought to be charging more!


With thanks,


Graeme

________________________________

**Comment by dsifford** [comment]
@saltiredj Ah, so you're saying you want the page number to be listed in the inline citation?

If no citation style in the list of styles satisfies that (which you can find out by [searching here](http://editor.citationstyles.org/searchByExample/)), then you can create and use your own citation style by following [these instructions](https://github.com/dsifford/academic-bloggers-toolkit/wiki#using-a-custom-citation-style)

If _that_ doesn't solve your issue, please let me know.

**Comment by saltiredj** [comment]
APA works just fine so a different reference style isn't needed. It isn't so much an issues with the style but with the information I can add into the reference itself.


For example, Endnote references don't identify page numbers for books (and some other types) because, well, references don't tend to. I often use the same book and cite different pages at different times in my article. I need to add the citations manually when I'm writing an article, whether it be using Pages, Word, Scrivener or (hopefully) Wordpress.


I'm not a programmer so I apologise if I'm saying something exceptionally stupid but I was wonder if it would be possible to either have an extra field when editing which could be 'page number', 'page reference' or 'citation page reference' - or do what the other programmes do and allow for a suffix to be added to the date so that 2016 can have a suffix of p6, pp.15-17 or :15-17. This would give the writer the option to add the page number suffix (or anything else) in any way they please. It also means one could add "cited in" and other clever do-dads.


I hope that makes sense.


I'm going to be awake for another hour (because I'm sad). If you are free and willing to do so, I'm more than happy to Skype/Facetime/live chat/whatever so I can show you what I mean. (In the meantime, I'll make a little video to demo what I'm looking for and I'll tweet you the link in about, oh, 10-15 minutes or so).


I'm so sorry for being a pain but I do hope the constructive comments are helpful.


G


________________________________

**Comment by saltiredj** [comment]
https://www.dropbox.com/s/bla4dj33k0s5b6f/Adding%20page%20numbers%20to%20citations.mp4?dl=0

[https://cfl.dropboxstatic.com/static/images/icons128/page_white_film.png]<https://www.dropbox.com/s/bla4dj33k0s5b6f/Adding%20page%20numbers%20to%20citations.mp4?dl=0>

Adding page numbers to citations.mp4<https://www.dropbox.com/s/bla4dj33k0s5b6f/Adding%20page%20numbers%20to%20citations.mp4?dl=0>
www.dropbox.com
Shared with Dropbox





Sorry, no awesome music this time. [😊]


— G


Facetime: saltiredj@me.com

Skype: saltiredj@hotmail.com


________________________________

**Comment by saltiredj** [comment]
Here's an example of what I mean ...

![screenflow mp4](https://cloud.githubusercontent.com/assets/24391106/21121949/34c73d56-c0c7-11e6-89a1-d28856716550.gif)

**Comment by dsifford** [comment]
@saltiredj Thanks for the clarification. Can you move those items to a new issue and I'll look into it next time I have a chance? 

Much appreciated!
