### ISSUE TITLE
Question about reordering references

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#263]
I know you write in the documentation not to reorder inline citations. For example, cutting and pasting a sentence along with an inline citation at the end of it would not be a good idea. But can you confirm simply deleting an inline citation (without removing it from the reference list) is okay? If so, then you might add a note to the documentation that a workaround would be to do as follows:

1. Delete the inline citations associated with text that you want to move.
2. Cut and paste that text to put it where you want.
3. Add those citations back into the text.

Or if you just wanted to move a citation, but not any text associated with it:

1. Delete the inline citation
2. Add it where you want, and the ordering will automatically be refreshed.

**Comment by dsifford** [comment]
Deleting a citation from the document is okay as long as you click "Refresh reference list" after you do that. See [here] for more on that(https://github.com/dsifford/academic-bloggers-toolkit/wiki#removing-one-or-more-single-references)

If you have any suggestions for documentation fixes/clarifications, feel free to make the changes and send it as a pull request. 👍
