### ISSUE TITLE
Additional References List

### ISSUE THREAD

**Issue by jugdemon** [dsifford/academic-bloggers-toolkit#264]
I might be wrong, but I couldn't find a way to add a reference to the List visible at the end without actually placing it in the text. Sometimes I want to add additional readings in the reference list. Would it be possible to force uncited references into the References List in the end?

**Comment by dsifford** [comment]
See [here](https://github.com/dsifford/academic-bloggers-toolkit/wiki#static-publication-lists) for details on how to insert a static publication list and let me know if that solves your issue or not.

**Comment by jugdemon** [comment]
Thanks, I didn't know the name and therefore did not find it. That works well for me.
