### ISSUE TITLE
Make "Pages" for Journals/Magazines etc. optional

### ISSUE THREAD

**Issue by Antimatzist** [dsifford/academic-bloggers-toolkit#275]
I ran into a small problem: There are some web-only Journals which I'd like to cite. As they are web-only, they do not have pages; however, the plugin "forces" me to use them.

It would be great if the "Pages" rider would be optional and not mandatory.

**Comment by dsifford** [comment]
@Antimatzist Good point. I'll remove the requirement on the next update.
