### ISSUE TITLE
Din1505-2 (numeric, German) bugged display

### ISSUE THREAD

**Issue by Antimatzist** [dsifford/academic-bloggers-toolkit#281]
**ABT Version:** 4.9.2

**PHP Version:** 5.5.9

**Theme:** Fox

**Plugin List:**
- Academic Blogger's Toolkit	4.9.2
- Captcha by BestWebSoft	4.2.8
- Creative Commons Configurator	1.8.27
- Fruitful Shortcodes	1.5
- IssueM	2.6.0
- MailPoet Newsletters	2.7.5
- TablePress	1.7
- Yoast SEO	4.0.2

**Browser:** Google Chrome (Version: 55.0.2883.87)

When using the bibliography style Din1505-2 (numeric, German), it displays the numbering incorrectly. The actual text and numbering overlap strangely. I could reproduce this on another wordpress installation (using a different theme)  on Firefox on another computer.
![abt_bug](https://cloud.githubusercontent.com/assets/17783483/21771464/bb869e74-d687-11e6-803e-632b1780b9d5.png)

**Comment by dsifford** [comment]
@Antimatzist Thanks for the report. I'll push a fix on the next update.

**Comment by dsifford** [comment]
@Antimatzist Pushing the fix for this now. Thanks for the report.
