### ISSUE TITLE
Inline Citation disappears

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#283]
ABT Version: 4.9.2
PHP Version: 5.6.29
Theme: Dazzling
Browser: Out of date Chrome on a Vista machine

Plugin List:
Academic Blogger's Toolkit
Ajax Search Lite
All In One WP Security
CM Table Of Contents Pro
Disqus Conditional Load
Easy Google Fonts
Give - Donation Plugin
Hyper Cache
Jetpack
Popular Posts Tabbed Widget for Jetpack
PopupAlly
Scalable Vector Graphics (SVG)
Social Popscroll
Super Socializer
UpdraftPlus - Backup/Restore
WP Smush
Yoast SEO

Issue:
See the following three screen shots that are for the back end of this article: http://www.earthmedresearch.org/antidepressants-fraudulent-what-science-actually-says/

1) Note the existence of citation 16
![image](https://cloud.githubusercontent.com/assets/17968340/21787595/e9ef253c-d67e-11e6-8622-8c552d1b4306.png)

2) Note that by simply deleting the space between two paragraphs (i.e. merging two paragraphs) that citation 16 disappears. I did this by using the DELETE key.
![image](https://cloud.githubusercontent.com/assets/17968340/21787634/1d4874f6-d67f-11e6-91e0-a9078df15354.png)

3) Note in the following example, I merged the same two paragraphs, yet citation 16 didn't disappear. In this case, rather than using the DELETE key to accomplish this, I used hte BACKSPACE key.
![image](https://cloud.githubusercontent.com/assets/17968340/21787674/5d17214a-d67f-11e6-87cf-b50010d9d9c4.png)

Why this happens, I don't know, but I just worked around it. 

David

**Comment by dsifford** [comment]
@metallikat36 Hard to say without seeing the rendered html in the `Text` editor.

When you merge paragraphs together, in the backend, tinymce has to join two `<p>` tags together so it might have been getting clipped during that phase. 

Nothing I'd be able to fix on my end. <kbd>ctrl</kbd> + <kbd>z</kbd> should work to restore the citation if this happens in the future.
