### ISSUE TITLE
Academic doesn't work (fine) with Visual Composer

### ISSUE THREAD

**Issue by clarberlin** [dsifford/academic-bloggers-toolkit#292]
**ABT Version:** 4.10.0

**PHP Version:** 5.6

**POL**

**Plugin List:**
VIsual Composer

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**

**Console messages:**
```js
// Paste messages here

The problem is that you can use the new version of ABT with Visual Composer. If you open a post and edit with backend editor you can't insert something from the reference list.
![bildschirmfoto 2017-01-22 um 11 55 59](https://cloud.githubusercontent.com/assets/25279028/22181992/d2f3d24a-e099-11e6-8060-c8d5dac1f5e8.png)

**Comment by dsifford** [comment]
Hi @clarberlin 

I'm not sure I understand what your issue is. Can you elaborate?

**Comment by dsifford** [comment]
Are you able to provide additional information about this @clarberlin?

**Comment by clarberlin** [comment]
i'm so sorry. Now it doesn't work at all. It's only a spinnig wheel - please look at the screenshot: 
I'm already deactivate all other plugins. Did you have any idea?
![bildschirmfoto 2017-01-30 um 10 46 27](https://cloud.githubusercontent.com/assets/25279028/22420670/d7d59b36-e6e3-11e6-9aac-0a3fdb4199f7.png)

**Comment by dsifford** [comment]
@clarberlin The plugin does not work with non-standard WordPress editors. It's deeply integrated with TinyMCE (the default visual editor) and will not work with any custom-made solutions.
