### ISSUE TITLE
Adding advanced search box

### ISSUE THREAD

**Issue by filimora** [dsifford/academic-bloggers-toolkit#295]
**ABT Version:** 4.10.0

**PHP Version:** 5.6

**Theme: onesocial**

**Plugin List:**
bbPress
bbPress Moderation
BuddyDrive
BuddyPress
BuddyPress Docs
BuddyPress Member Type Generator
BuddyPress Xprofile Custom Fields Type
BuddyPress Xprofile Member Type Field
Co-Authors Plus
Comments Disable - AccessPress
Conditional Profile Fields for BuddyPress
Contact Form 7
Header and Footer
Limit Login Attempts
Re-add text underline and justify
User Role Editor
User Specific Content
WooCommerce
WP Super Cache
WP User Frontend
Yoast SEO

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**
Congratulation for the really useful plugin! It will be possible to add some advanced research fields (ie journal and authors research box) in addition to the main search box.

**Actual behavior:**

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Search is being deprecated in the next release. Closing this as it's no longer something I plan to support.
