### ISSUE TITLE
Suggestion for a new feature: footnotes integrated. 

### ISSUE THREAD

**Issue by galderna** [dsifford/academic-bloggers-toolkit#296]
**ABT Version:** 4.10.0

**PHP Version:** 5.6

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**

**Console messages:**
```js
// Paste messages here

```
When doing academic work, the scheme I use to follow is: title -- abstract -- body (main information) - footnotes (additional explanatory information with eventually a brief citation of its source as: author, publishing year and page number) -- references (full bibliographic citations sorted alphabetically). 

This way, the explanatory notes and the references don't get mixed and everything is neatly located. A fine example of this would be the next article: 

http://www.thezensite.com/ZenEssays/DogenStudies/Doctrine_and_Concept_of_Truth.html

Academic Bloggers Toolkit is useful for setting references directly associated with the body of the article but at this moment of its development does not offer the possibility of: 1. adding explanatory notes as footnotes; 2. separating notes and references; 3. sort the references alphabetically.

It would be really helpful if ABT allowed to work this way as well. Otherwise, one would need to use ABT plugin in combination with another plugin for the footnotes. But then, two or three main issues might occur:

1. Both plugins compete against each other for gaining the end of the post. (For instance, I have tried ABT in combination with "footnotes" plugin and ABT's references go first and "footnotes" plugin's footnotes go last. I need the opposite order. Plus, of course, the indexes of both plugins go independently, so you get two "1", two "2", etc. which is not functional.

2. As far as I know, ABT's references appear in the same order they are cited in the text but not sorted alphabetically. (Which makes perfect sense when working only with references but not when working with both footnotes and references).

My suggestion for a new ABT feature is then the following: 

When using the "+" button to add a new reference, the dialog box could include two options: 

1. "Add reference", for the user to make only bibliographical citations in their order of appearance in the text. (This is the very functionality available so far. Ant the output would be also the same.) 

2. "Add footnote and reference", for the user to get two separate lists at the end of the page/post: the first one for the footnotes in their order of appearance in the text, and the second one for the corresponding bibliographical references (if any, because not all footnotes necessarily have to have a bibliographical reference associated) sorted alphabetically. In this case the output would be something like this:

Notes (in the same order that they appear along the text):
1. This is a note without a reference associated.
2. Cf. Newton, I. (1726) p. 10.
3. Einstein, Albert (1950) p. 14: "Special relativity has this in common with Newtonian mechanics: The laws of both theories are supposed to hold only with respect to certain coordinate sys­ tems: those known as 'inertial systems.'"  

References (with or without the index number, sorted alphabetically):
1. Einstein, Albert (1950), "On the Generalized Theory of Gravitation", Scientific American, CLXXXII (4): 13–17, doi:10.1038/scientificamerican0450-13
2. This is a reference without a note associated, of an author whose surname starts with a letter between E and N.
3. Newton, Isaac. Philosophiae Naturalis Principia Mathematica: the Third edition (1726) with variant readings, assembled and ed. by Alexandre Koyré and I Bernard Cohen with the assistance of Anne Whitman (Cambridge, MA, 1972, Harvard UP) 

Finally, as for the text hover, it would be nice if it showed both the note and the reference (if them both exist), or the one that exists (the note or the reference).

And that's all. Sorry for the lenghty message. Thanks a lot for your attention and great work with the ABT plugin.

**Comment by dsifford** [comment]
Hi @galderna. Thanks for the feedback!

Agreed that this is a particular pain area that has been brought up a few times by others. I'm still trying to figure out the implementation details for something like this because on the backend side, things are pretty complicated.

The way you describe using footnotes intermixed with references is interesting. I've never seen them used like that. Does this come from a particular style (AMA format, for example)? If so, is there a guide to using this style somewhere online that I can take a look at?

One of the trickiest issues that I've had to consider when thinking about putting something like this together is that it needs to be done in such a way that doesn't conflict with any of the 1000+ styles that are available for citations. You brought up some of the tricky parts already but here they are again for the sake of completeness:
1. How would I number the footnotes? Should they be numbered at all or should they use symbols (e.g. "daggers", "asterisks", etc)? What if a style uses the same number format as the footnotes? 
2. Do the footnotes get numbered separately from the citations?
3. How would footnotes work with "Full Note" style citations? (See Chicago Full Note style for an example of this).
4. How would these footnotes be positioned in the reference list? Or should they be at all?
5. How should the footnotes work on published pages? (i.e. should they produce tooltips or should they appear some other way?).

Finally, to comment on one of the points you made...

> Academic Bloggers Toolkit is useful for setting references directly associated with the body of the article but at this moment of its development does not offer the possibility of: 1. adding explanatory notes as footnotes; 2. separating notes and references; **3. sort the references alphabetically.**

Number 3 is currently possible. You just have to use a citation style that sorts alphabetically. APA 6th does this I believe.

Thanks again for the feedback.

Any ideas on how to go about this @fbennett ?

**Comment by galderna** [comment]
Hi @dsifford. Thanks for your quick answer!

> Does this come from a particular style (AMA format, for example)? If so, is there a guide to using this style somewhere online that I can take a look at?

This is not from AMA but from APA style format you mention below in your message. You can take a quick look at the [following page](https://owl.english.purdue.edu/owl/resource/560/04/) from [Purdue OWL](https://owl.english.purdue.edu/owl/) website.

This is pretty similar to the [CMS NB](http://lib.trinity.edu/research/citing/Chicago_Notes_16thed_w_short.pdf) style ("NB" stands for "Notes and Bibliography"). You can see an example in the following [sample document](https://owl.english.purdue.edu/media/pdf/1300991022_717.pdf) also from  [Purdue OWL](https://owl.english.purdue.edu/owl/resource/717/11/) website. The example uses the footnotes for making full bibliographic citations in the same page, as well as other comments such as "Ibid", etc. Then it appends all the cited sources at the end of the document as a Bibliography sorted alphabetically. 

> One of the trickiest issues that I've had to consider when thinking about putting something like this together is that it needs to be done in such a way that doesn't conflict with any of the 1000+ styles that are available for citations.

I am not either a programmer or a developer, so sorry for the lack of beautiful poetic code and excessive verbosity below, but I think the conflict could be overcome following the next logical sequence:

1. Add to the dialog box opened when clicking the "+" button, right under the "Add Reference" field, a new field called "Add Footnote", "Add Endnote", "Add Note", "Add Comment", or something like that.
(This new field should be also visible within the "Add Manually" dialog box). 
2. This field is for the users to write their own additional explanations on some point of the text, to make indications such as "_Ibid_", "_op. cit._", etc., or even to include a partial or full reference, according to certain style.
3. We then can distinguish four different cases: 1. both fields are left empty; 2. the "Reference" field is filled in whereas the "Footnote" field is empty; 3. the "Footnote" field is filled in whereas the "Reference" field is s empty; 4. both fields are filled in.
4. Of course, in the first case (both fields empty), no index is added to the text.
5. In the second case ("Footnote" field empty), the content of the "Reference" field is used both to generate the corresponding footnote as well as the citation for the bibliographic referenced at the end of the document. Plus an index is added to the text.
6. In the third case ("Reference" field empty), the content of the "Footnote" field is used to only generate the corresponding footnote but not a citation for the Bibliography at the end. Plus an index is added to the text.
7. In the fourth case (both fields filled in), the "Footnote" field is used to only generate the corresponding footnote whereas the "Reference" field is used to generate a citation for the Bibliography at the end.
8. Sort all the citations alphabetically by first author Surname.   
9. Define new style formats such as, for example, "APA NB" and "CMS NB" (NB = Notes & Bibliography). 
10. Whenever one of those formats is chosen, generate both a numbered list with the contents of the "Footnote" fields and an alphabetically sorted list with the contents of the "Reference" fields. 
11. Write one list after the other at the end of the document, preceded by the corresponding title "Notes" or "References".
12. If the article were to be divided in several pages, then it would be just fine to give the user the chance to choose where to insert the notes": as footnotes, at the bottom of each page, or as endnotes, at the en of the article.

Sorry if I'm missing something important above. I do know this all is being too bold for my part...

Now, as for the tricky parts:

> 1. How would I number the footnotes? Should they be numbered at all or should they use symbols (e.g. "daggers", "asterisks", etc)? What if a style uses the same number format as the footnotes?

I think it would be just as fine as well to give the user the chance to choose how to index the footnotes, with numbers or with special symbols such as daggers, asterisks, etc.

It's not necessary to use the footnotes capability for all the styles, only for the ones so defined, such as "APA NB", "CMS NB", or just "NB" for a generic user defined style... 

> 2. Do the footnotes get numbered separately from the citations?

Following the logic above, each index in the text would have both a comment and a citation associated. If the comment were empty, the content of the footnote would be the citation. If the citation were empty, the content of the footnote would be the comment. If both the citation and the comment were specified, the content of the footnote would also be the comment. The remaining case is irrelevant because there wouldn't be any index.   

> 3. How would footnotes work with "Full Note" style citations? (See Chicago Full Note style for an example of this).

Whenever a comment were specified along with its reference source, the footnote would include both the comment plus the full citation for the first time being cited. Elsewhere the footnote would only content the comment, which possibly a short reference to the already footnoted full reference, specified manually by the user.

If there were no comment associated to an index, then the footnote would only show the full citation in the Chicago Full Note style.

> 4. How would these footnotes be positioned in the reference list? Or should they be at all?

They would be needed two lists to define: 1. a footnote list (oredered by index number) and 2. a reference list (sorted alphabetically by author Surname). 

Of course, if a work were eventually cited more than once, the repeated appearances of the same work would be dismissed for the reference list.

> 5. How should the footnotes work on published pages? (i.e. should they produce tooltips or should they appear some other way?).

On hover, the indexes would produce tooltips showing the same content as the associated footnote, that is to say: either a plain comment with no citation at all, a comment with a short citation, a comment with a full citation (for the first time cited), or just a full citation without a comment (if not specified).  

> Number 3 is currently possible. You just have to use a citation style that sorts alphabetically. APA 6th does this I believe.

Thank you very much for the tip. I'm still getting familiar with the ABT plugin. 

Hope all this is viable. Best.

**Comment by dsifford** [comment]
@galderna Thanks for the in-depth explanation.

Does [this style](http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fchicago-annotated-bibliography) appear to be what you're describing?

If so, then I'll need to get implementation clarification from @fbennett prior to working on this.

**Comment by galderna** [comment]
@dsifford Yes, that's the style.

I look forward to see that implemented. All the best with the work ahead. 

Thank you very much for your kind feedback. I appreciate it.

**Comment by dsifford** [comment]
This will be added in the next update. Demo below...

https://www.useloom.com/share/fef8ab0d7ba34186aa8129d1924844cc

**Comment by dsifford** [comment]
Done
