### ISSUE TITLE
Improve Manual Adding

### ISSUE THREAD

**Issue by jugdemon** [dsifford/academic-bloggers-toolkit#297]
I ran into the situation, where I added several journal articles manually. I accidentally added information into the first data mask and then switched from Webpage to journal article. All previous input into the data mask was deleted. It would be useful, if similar fields (author, title, etc.) would not be automatically emptied when switching the reference type.

Even though I noticed the bug/behaviour, I had to retype at least 3 out of 10 references.

While this is not a high profile issue, I believe it would ease the usability of manually adding references.

**Comment by dsifford** [comment]
Let me mull this one over.

I added explicitly the clear action on type change to prevent leakage of fields from a certain citation type over to other types that don't use those fields because that could potentially lead to some tricky bugs.

**Comment by jugdemon** [comment]
Your reasoning makes sense. That is why I specified similar fields only, but if equal fields would be the only thing, that would be fine as well. Obviously all other field should be pruned. Would it be possible to check whether the next selected type has a field with the same name and if yes copy the value and otherwise drop it?

Again, this is a minor issue, I just happen to come across a few references per week that I would like to manually insert and such a feature would make the processes smoother (for example: I could accidentally start inserting information until I notice my mistake - usually when the next field to fill does not exist - switch reference type and continue what is still missing instead of retyping everything.

**Comment by dsifford** [comment]
Gonna say no to this change for now since there are a bunch of higher priority things in the pipeline (the highest being Gutenburg support).

When that all dies down, I may reconsider later on.
