### ISSUE TITLE
Potential missing feature in citing Book Section

### ISSUE THREAD

**Issue by jugdemon** [dsifford/academic-bloggers-toolkit#299]
I was adding a book section to one of my articles, and I noted that there are no fields for editors. It is common to actually cite the editors as well (strong emphasis by me to highlight the editors, not actually part of the reference style):

Montello, D. and Raubal, M. (2013). Functions and applications of spatial cognition. In: **Waller, D. and Nadel, L. (Eds.).** _Handbook of Spatial Cognition_. American Psychological Association, pp. 249-264.

At the moment, I can only achieve: 

Montello, D. and Raubal, M. (2013). Functions and applications of spatial cognition. In: _Handbook of Spatial Cognition_. American Psychological Association, pp. 249-264.

Could you investigate whether it would be possible to add editors (I assume the underlying citation processor is capable of doing this and that the feature is merely not exposed).

**Comment by jugdemon** [comment]
P.S.: Also, I am sorry for swamping you with issues and request, but I now moved to use the toolkit on a regular basis. Please don't read this requests as criticism to your great work, but rather as another computer scientist that does user testing and software testing for you.

**Comment by dsifford** [comment]
@jugdemon Thanks. Yeah, this is an oversight on my part. Thanks for the report.

(Note: No timeframe on when I'll be able to get to this. This project, being a side-project generating no revenue, is the lowest thing on my priority list. I'll try to circle back and get the open issues resolved once I get some free time. Sorry in advance for the delay.)

**Comment by jugdemon** [comment]
I am not sure if you fixed it, or whether I just figured out how to do it. But I noticed that you can click on "Author" and switch it to "Editor". So the issue is resolved for me.

**Comment by dsifford** [comment]
@jugdemon Ah, okay yep that was an existing feature. 

I was under the assumption that you were already aware of that so I didn't check. 

Glad to hear you got it sorted out.
