### ISSUE TITLE
Missing shorting of author list

### ISSUE THREAD

**Issue by jugdemon** [dsifford/academic-bloggers-toolkit#300]
Many styles such as APA shorten the list of authors with "et al." as soon as the long form has been listed once. I have a case where the "et al." shorting only happens at the third repetition.

I assume it has to do with the fact that I list first the quotation in a list of citations:

(A & B, 2015; C, D, E & F, 2004)

The followed by a citation:

(C, D, E & F, 2004)

And only the third time around it lists:

(C et al., 2004)

Assume, that the chaining is somehow stopping it from shortening it.

**Comment by dsifford** [comment]
@jugdemon Missed this one. Sorry for the delay..

Can you provide an actual example of the issue? I'm not sure I'm following what you're saying.

Thanks

**Comment by jugdemon** [comment]
@dsifford: [Here is the page](http://blog.gruebel.io/2017/02/23/asc-introduction/) with the actual occurrence. The citation of: "Lempert, R., Nakicenovic, N., Sarewitz, D., & Schlesinger, M. (2004). Characterizing climate-change uncertainties for decision-makers. An editorial essay. Climatic Change, 65(1), 1–9."

You find the citation in the second paragraph, the second subtitle (predict-then-act) and at the end of the quotation.

In my understanding the second occurrence should be formatted as the third. This leads me to belief, that the first occurrence in the list is not properly counted.

**Comment by dsifford** [comment]
No way to tell without being able to play with it. 

What style is being used?

**Comment by jugdemon** [comment]
It is set on APA6. Does that help enough?

**Comment by dsifford** [comment]
@jugdemon You're correct.

This issue is out of scope here, but I've opened up an issue in the style repository that you're welcome to follow/chime in on.

Closing this thread because it's not within scope.
