### ISSUE TITLE
Citation not removed upon refresh

### ISSUE THREAD

**Issue by jugdemon** [dsifford/academic-bloggers-toolkit#303]
When I remove more than one citation at once and refresh the citation list, I actually only have one citation removed, and all other citations are placed at the beginning of the document. I then have to iteratively remove a single citation, update the reference list and rinse and repeat until all citations are removed.

The reason why I regularly come across this behaviour is that I want to add 2-5 references for one citation. Since I have not added the citations to my text yet, I add each and get a single entrance into the text body. A proper citation has them in one parenthesis. So I do the group insert and need to remove the separated citations.

It would be useful, if refresh could remove all "unused" references at once.

Another useful change could be to add a reference to the list without immediately inserting them. So I could create all references at once and then "group insert" them.

**Comment by dsifford** [comment]
I'm not sure I understand exactly what you're describing. 

> It would be useful, if refresh could remove all "unused" references at once.

This is an existing feature. Click the "refresh reference list" button.

> Another useful change could be to add a reference to the list without immediately inserting them

This is also an existing feature. Uncheck the "insert inline citation" toggle when adding citations.

If you haven't done so already, you might benefit from reading through this: https://github.com/dsifford/academic-bloggers-toolkit/wiki

**Comment by jugdemon** [comment]
@dsifford I am actually using the first feature and it only removes the first removed inline citation. If you remove more than one, the rest are reinserted at the beginning of the text.

As for the second, I just missed the toggle. Sometimes it is hard to identify features. Sorry, for missing it.

**Comment by dsifford** [comment]
@jugdemon Hm.. I'm still having a hard time wrapping my head around what you're describing. 

Any chance you can provide an example?

Also: Apology not necessary; I'll admit that the plugin is probably lacking in the documentation department. Down the road I'll hopefully get around to making things clearer.

**Comment by jugdemon** [comment]
I have observed the patterns a few times. Let me get back to you with a step by step example. Though I am going on a trip, so give me a few days.

**Comment by jugdemon** [comment]
Here is step-by-step instruction.

1. Create new post.
2. Insert 1st Citation (e.g. A, B. (2017). C. Retrieved from E)
3. Insert 2nd Citation (e.g.F, G. (2017). H. Retrieved from J)
4. Delete both inline citations.
5. Expand Reference List menu.
6. Press "Refresh reference list".
7. After the editor reloads only (A, 2017) is gone.

I hope this helps.

**Comment by dsifford** [comment]
@jugdemon Thanks for the clarification. 

What about when the citation is listed in more than one location?

So, for example, consider citations "A" and "B".

> Blah blah blah (A). Blah blah (B). Blah Blah Blah Blah(A).

Delete one of the A's. Does it still happen?

I think this might only happen if your citation is listed only once and you delete the way you are describing.

If the citation is only listed once, you should delete using the delete citation button on the reference list to fully strip it out.

**Comment by dsifford** [comment]
Sorry for the delay.

This will be fixed in the next release. I found the problem. 👍
