### ISSUE TITLE
unexpected error "length of undefined"

### ISSUE THREAD

**Issue by sdmd89** [dsifford/academic-bloggers-toolkit#306]
Hi there,
I am a new user of your toolkit. An unexpected error just occured and disables me to write blog articles. When opening articles in edition mode, it says : 

> An unexpected error occurred. TypeError: Cannot read property 'length' of undefined

I have no idea of what's happening since it started with a new article that is correctly published and visible for users, even if I can't edit it anymore. Do you have any clue on what's going on ?

Thanks
Sam

**Comment by alfalfa31** [comment]
I'm having a similar issue and i am not a new user of the plugin
![screenshot from 2017-03-10 10-28-58](https://cloud.githubusercontent.com/assets/13860678/23801136/02c9850c-057d-11e7-8c7e-b2284ad41413.png)

**Comment by alfalfa31** [comment]
I've verified this issue in Chrome Version 56.0.2924.87 (64-bit) as well as Firefox 52.0 (64-bit) on Ubuntu 16.10.

In the posts where this error occurs there are no citations, and attempting to create a citation yields this result.


![screenshot from 2017-03-10 10-35-27](https://cloud.githubusercontent.com/assets/13860678/23801354/dcf9f7ac-057d-11e7-82f6-28218414241a.png)

**Comment by dsifford** [comment]
@alfalfa31 Thanks for the report!

Is there any chance you could create me an account on your blog so I can take a look? This specific issue has been haunting me for months. I've never been able to reproduce it myself.

**Comment by dsifford** [comment]
@sdmd89 Didn't see that there were two of you.

Ditto what I said above. 😄

**Comment by alfalfa31** [comment]
It's not mine to do, but I'll see.  It happened, then healed itself.  Once I tried to add a citation to the article that caused the issue, the issue went away.

Next time it happens (assuming that it does) I'll grab the console output to see about helping you out.

This thing is one of the best plugins I've seen, BTW.

**Comment by dsifford** [comment]
@alfalfa31 Sounds good. It's a sneaky little bugger, that's for sure!

And thanks! Glad to hear you like it. 😄

**Comment by sdmd89** [comment]
Thanks for your answers. At least I am not alone.
The issue occured today once again.
Then I clicked okay and I managed to write something... But impossible to quote. When trying to quote this messages pops up:

> An unexpected error occurred. TypeError: Cannot read property 'registry' of undefined

**Comment by dsifford** [comment]
@sdmd89 Any chance you can give me access to your blog so I can take a look? Without being able to investigate or reproduce the issue myself, I won't be able to fix.

Thanks in advance.

**Comment by sdmd89** [comment]
Okay @dsifford many thanks to you. How can I give you login information in private ?

**Comment by dsifford** [comment]
@sdmd89 dereksifford@gmail.com

Also, please provide the steps that I need to take to trigger the error.

Thanks so much.

**Comment by sdmd89** [comment]
There we are @dsifford you should receive an email with log in information.
For the problem to occur you only need to create an article. You will see that it becomes impossible to write in the visual mode. Thank you very much for your time.

**Comment by dsifford** [comment]
@sdmd89 The style that you have set doesn't exist. I think that might be the issue.

The style may have been renamed from when you initially set it. Can you try going into your settings and setting it to `universite-de-montreal-apa.csl` and see if that works?

**Comment by dsifford** [comment]
@sdmd89 The style will actually be named `Université de Montréal - APA (French - Canada)`

**Comment by sdmd89** [comment]
I actually changed the style to APA 6th edition.
I can now write new articles but the problem still occurs when opening an old one. Only one of them fortunately. I think I am just going to copy-paste its content and hope this never happens again. Which is only half satisfying. Anyway thanks for your help @dsifford

**Comment by dsifford** [comment]
@sdmd89 I assume that the style that you had previously installed did work at one point in time, correct?

If so, I'll have to add something in that falls back to a common style in the event that other styles get renamed in the future to prevent the errors.

Thanks for the report.

**Comment by sdmd89** [comment]
You are almost right @dsifford. In fact I didn't install any style, I used one of the list. And indeed it worked for a (short) while. Until is started bugging.
Many thanks for your help.

**Comment by dsifford** [comment]
This will be fixed in the next release. 

It was actually a much larger issue than previously expected (about half of the styles in the list were affected by this!). So, in other words, if a user was using a relatively uncommon style, chances are he/she would have experienced this issue!

Thanks for the feedback. I apologise for the delay!

**Comment by alfalfa31** [comment]
I'm pretty sure we all appreciate the effort.  Like I said, this plugin is a huge time saver and a wonderful way of lending credibility to articles.
