### ISSUE TITLE
Text citation feature

### ISSUE THREAD

**Issue by jugdemon** [dsifford/academic-bloggers-toolkit#309]
When describing the context of a reference, it is often useful to write sentences like

> As Doe (1997) points out, it ...

However, as far as I know with ABT, one can only approximate this with

> As Doe (Doe, 1997) points out, it ...

It would be nice, if the first style was available as well. In latex biber it would be the difference between textcite and autocite. 

I tried to find out whether it is an available feature, but to my understanding it is not implemented.

Would it be possible to enable this second citation type?

**Comment by dsifford** [comment]
Unfortunately, there's no reasonable way to make the processor aware of the proceeding text without adding a significant amount of extra (and probably buggy) code.

Even if it was possible to add that extra code, the current reference implementation of the citation style language processor (which this plugin uses) wouldn't be able to make use of it...

It's a good idea, but just not feasible to implement right now.

An alternative would be to just cite your reference like this to make it read a little less redundantly...

> "As Doe points out, it [ blah blah blah ] (Doe, 1997)"
