### ISSUE TITLE
Conflict with Page Builder plugin

### ISSUE THREAD

**Issue by KirkLowery** [dsifford/academic-bloggers-toolkit#310]
**ABT Version:** 4.10.0

**PHP Version:** 7.0.15-0ubuntu0.16.04.4

**Theme:** Kadence Virtue Premium version 4.0.4

**Plugin List:**
- Academic Blogger's Toolkit	by Derek P Sifford – 4.10.0
- Akismet Anti-Spam	by Automattic – 3.3
- Black Studio TinyMCE Widget	by Black Studio – 2.3.1
- Cyclone Slider Pro	by Nico Amarilla – 2.10.4
- Kadence Importer	by Kadence Themes – 1.5.2
- Kadence Slider	by Kadence Themes – 2.1.3
- Slider Revolution	by ThemePunch – 5.3.1.5
- Page Builder by SiteOrigin	by SiteOrigin – 2.4.25
- SiteOrigin Widgets Bundle	by SiteOrigin – 1.8.1
- Twitter Auto Publish	by xyzscripts.com – 1.3.1
- Wordfence Security	by Wordfence – 6.3.4
- Yoast SEO	by Team Yoast – 4.4
- WP-Mail-SMTP	by Callum Macdonald – 0.10.1
- WP-Piwik	by André Bräkling – 1.0.14
- WP User Avatar	by flippercode – 2.0.8

**Browser:** Google Chrome (Version: 57.0.2987.98 (64-bit))

**Expected behavior:** Opening a page or post edit window, the List Reference widget should show the function options for adding, etc., bibliography.

**Actual behavior:** The widget shows a "spinner" which never resolves. When I deactivate SiteOrigin's Page Builder plugin (comes with the Kadence Virtue Premium theme) and refresh the page, I get ABT's expected behavior with the List Reference widget.

**Workaround:** Disable Page Builder when using ABT functions.

**Console messages:**
```js
// Paste messages here
load-scripts.php:9 JQMIGRATE: Migrate is installed, version 1.4.1
post.php:326 Mixed Content: The page at 'https://blogs.emdros.org/eh/wp-admin/post.php?post=1&action=edit' was loaded over HTTPS, but requested an insecure image 'http://blogs.emdros.org/eh/wp-content/uploads/2017/02/IMG_1815_1-150x150.jpg'. This content should also be served over HTTPS.
post.php:327 Mixed Content: The page at 'https://blogs.emdros.org/eh/wp-admin/post.php?post=1&action=edit' was loaded over HTTPS, but requested an insecure image 'http://blogs.emdros.org/eh/wp-content/uploads/2017/02/IMG_1815_1-150x150.jpg'. This content should also be served over HTTPS.
post.php:1167 Mixed Content: The page at 'https://blogs.emdros.org/eh/wp-admin/post.php?post=1&action=edit' was loaded over HTTPS, but requested an insecure image 'http://blogs.emdros.org/eh/wp-content/uploads/2017/02/IMG_1815_1-150x150.jpg'. This content should also be served over HTTPS.
post.php:1168 Mixed Content: The page at 'https://blogs.emdros.org/eh/wp-admin/post.php?post=1&action=edit' was loaded over HTTPS, but requested an insecure image 'http://blogs.emdros.org/eh/wp-content/uploads/2017/02/IMG_1815_1-150x150.jpg'. This content should also be served over HTTPS.
post.php:1169 Mixed Content: The page at 'https://blogs.emdros.org/eh/wp-admin/post.php?post=1&action=edit' was loaded over HTTPS, but requested an insecure image 'http://blogs.emdros.org/eh/wp-content/uploads/2017/02/IMG_1815_1-150x150.jpg'. This content should also be served over HTTPS.
post.php:1170 Mixed Content: The page at 'https://blogs.emdros.org/eh/wp-admin/post.php?post=1&action=edit' was loaded over HTTPS, but requested an insecure image 'http://blogs.emdros.org/eh/wp-content/uploads/2017/02/IMG_1815_1-150x150.jpg'. This content should also be served over HTTPS.
post.php:1171 Mixed Content: The page at 'https://blogs.emdros.org/eh/wp-admin/post.php?post=1&action=edit' was loaded over HTTPS, but requested an insecure image 'http://blogs.emdros.org/eh/wp-content/uploads/2017/02/IMG_1815_1-150x150.jpg'. This content should also be served over HTTPS.
(unknown) Download the React DevTools for a better development experience: https://fb.me/react-devtools
plugin.min.js:1 Deprecated TinyMCE API call: <target>.onNodeChange.add(..)
post.php:1 Mixed Content: The page at 'https://blogs.emdros.org/eh/wp-admin/post.php?post=1&action=edit' was loaded over HTTPS, but requested an insecure favicon 'http://blogs.emdros.org/eh/wp-content/uploads/2017/02/cropped-ehLogo20170218-192x192.jpeg'. This content should also be served over HTTPS.
```

**Comment by dsifford** [comment]
Hi @KirkLowery -- This is a known issue (See #259 #220)

Unfortunately, there's nothing I can to on my end to fix this. SiteOrigins uses a non-standard editor for their plugins, which won't work with ABT. ABT is deeply integrated with the default TinyMCE editor that is provided by WordPress. 

The reason why the loading spinner shows endlessly is because it is waiting for a TinyMCE editor to become available for it to attach to. Without that editor, it'll never fully load.

Sorry for the confusion. I'll better clarify this on the WordPress plugin page when I push out the next update.

**Comment by KirkLowery** [comment]
Okay, thanks. I doubt SiteOrigin is going to change their basic design. I use Page Builder a lot. I could live without it. I'll look into other bibtex alternatives.
