### ISSUE TITLE
Custom citation style "PRL" not showing

### ISSUE THREAD

**Issue by LordNouda** [dsifford/academic-bloggers-toolkit#312]
I first want to say: great plugin!

I do have a problem, though. I wanted to use a custom citation style "Physical Review Letters", since I come from the physics community, and did everything you describe so well [here](https://github.com/dsifford/academic-bloggers-toolkit/wiki#using-a-custom-citation-style). The URL was successfully converted to a local path an I can also select the new style for individual references. However, they do not show up. The only thing produced is the following span:

`<span id="ad1fhfqtlp" class="abt-citation noselect mceNonEditable" data-reflist= "[&quot;t1mgjqrfb5&quot;]"></span>`

Selecting any one of the preinstalled styles shows a neat reference list and the numbers in the text.

I disables all other plugins and the problem persists.

**ABT Version:** 4.10.0

**PHP Version:** 5.4.40

**Theme:** Twenty Seventeen

**Plugin List:**
- Akismet Anti-Span v3.3
- Jetpack by WordPress.com v4.7.1
- SQLite Integration v1.8.1

**Browser:** Google Chrome (Version: 56.0.2924.87)

**Expected behavior:**
I expected the reference to be displayed in the custom style

**Actual behavior:**
Nothing was displayed.

**Console messages:**
```js
Uncaught TypeError: Cannot read property 'children' of null
    at eval (eval at 576 (https://www.succo.net/wp-content/plugins/academic-bloggers-toolkit/lib/js/Frontend.js?ver=4.10.0:1:81), <anonymous>:23:33)
    at Array.map (native)
    at eval (eval at 576 (https://www.succo.net/wp-content/plugins/academic-bloggers-toolkit/lib/js/Frontend.js?ver=4.10.0:1:81), <anonymous>:22:61)
    at Array.forEach (native)
    at new Citations (eval at 576 (https://www.succo.net/wp-content/plugins/academic-bloggers-toolkit/lib/js/Frontend.js?ver=4.10.0:1:81), <anonymous>:20:53)
    at HTMLDocument.frontendJS (eval at 576 (https://www.succo.net/wp-content/plugins/academic-bloggers-toolkit/lib/js/Frontend.js?ver=4.10.0:1:81), <anonymous>:144:5)
```

**PRL Style (physical-review-letters.csl):**
```xml
<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" version="1.0" default-locale="en-US">
  <info>
    <title>Physical Review Letters</title>
    <id>http://www.zotero.org/styles/physical-review-letters</id>
    <link href="http://www.zotero.org/styles/physical-review-letters" rel="self"/>
    <link href="http://www.zotero.org/styles/american-physics-society" rel="independent-parent"/>
    <link href="http://authors.aps.org/STYLE/ms.html#citations" rel="documentation"/>
    <author>
      <name>Richard Karnesky</name>
      <email>karnesky+zotero@gmail.com</email>
      <uri>http://arc.nucapt.northwestern.edu/Richard_Karnesky</uri>
    </author>
    <category citation-format="numeric"/>
    <category field="physics"/>
    <issn>0031-9007</issn>
    <eissn>1079-7114</eissn>
    <summary>A style for APS's journal "Physical Review Letters"</summary>
    <updated>2013-03-29T23:50:45+00:00</updated>
    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License</rights>
  </info>
</style>
```

**Comment by dsifford** [comment]
@LordNouda Thanks! Glad you like it.

Luckily, the issue you're having is actually quite easy to fix.

The style you have selected is a "dependent" style, meaning it's actually the exact same as an "independent" style, but with a different name. 

What you'll need to do is just delete the custom style that you added and instead use the preinstalled `American Physics Society` style (it's the exact same as Physical Review Letters).

Let me know if you run into any other trouble.

**Comment by LordNouda** [comment]
Works like a charm. Many thanks @dsifford !
