### ISSUE TITLE
Adding citation to existing citation block doesn't work.

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#318]
WP version 4.7.4
ABT 4.10.0

This must have started happening recently at some point, because this used to work. See the screenshot:
![image](https://cloud.githubusercontent.com/assets/17968340/25266487/25497640-2626-11e7-9e7a-7d9da5e02600.png)

**Comment by dsifford** [comment]
Strange. 

No idea when I'll have the time to actually look at this, but I'll keep this in mind when the time arises.

Thanks for the report!

**Comment by dsifford** [comment]
Sorry for the delay.

This issue had to do with a somewhat recent breaking-change in tinymce. I've fixed the breaking issue which should take care of this. It'll be in the next release.
