### ISSUE TITLE
#abt-smart-bib:before bug

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#32]
Awesome updates Derek. I will test it out more thoroughly probably tomorrow. One bug on my site is that if I try to add the before text, it does not appear:
http://www.earthmedresearch.org/community-guidelines/
The word "References" is something I wrote manually, so ignore that. 

When I click Update on the override CSS box, it keeps adding more  slashes "\" to the code.  The more you click update, the more slashes appear, like this:

#abt-smart-bib:before {
  content: \\\'Bibliography\\\';  
  margin-left: -20px;
  font-weight: 900;
  line-height: 50px;    
}

**Comment by dsifford** [comment]
Hm... Looks like that field is escaping itself. I'll have to look into it.

Protip for the meantime: Sequester all frontend CSS into the same file. That way, your site only has to make one request over the network for files. The box I provide is simply for convenience, it's definitely not for optimization!

Side note: did you try double quotes? `"` -- Same result?

**Comment by dsifford** [comment]
@metallikat36 nevermind. Already fixed it. Pushing the fix shortly
