### ISSUE TITLE
The plugin loads 3 MB Javascript file. Is this a bug? This makes the site very slow.

### ISSUE THREAD

**Issue by MiteshAtGithub** [dsifford/academic-bloggers-toolkit#329]
I think this has to do with Webpack and a javascript file vendor.bundle.js which is big gets loaded. This makes the site very slow.

It gets loaded only first time and chrome caches it so it doesn't get loaded everytime, but still 3 mb is big, especially on mobiles.

Is this a bug or the js file is required to do some stuff on the site (not on admin/plugin side)?

Sorry if this is a basic question.

Thanks

**Comment by dsifford** [comment]
Thanks for the report.

Yeah, it's bad code splitting for sure. It's on the backburner to be fixed, but I have no estimation on when I can get that done since I have commitments that consume the majority of my time right now.

**Comment by MiteshAtGithub** [comment]
Thanks for prompt response.

I'll try to see what's happening and will report back if I can solve something.

**Comment by dsifford** [comment]
@MiteshAtGithub Sorry for the delay... Getting this squared away this week.

Current build size for the code you mentioned is 91.4kb. 👍 

Should be set to go in the next 7 days or so once I knock out some of the other issues.
