### ISSUE TITLE
z-index question

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#33]
I have manually coded in a z-index for .abt_tooltip. I am wondering if I also need to do it for the following:

.abt_arrow_up
.abt_arrow_down
.abt_tooltip_touch_close

In other words, I want to make sure all parts of the tooltip stick together. Have I got this list right, or did I miss any other elements I need to add the same z-index to?

**Comment by dsifford** [comment]
Here's how the tooltips are layered.

```
--------- top
.abt_tooltip_touch_close
.abt_arrow_up  (and) .abt_arrow_down (and) the text itself
.abt_tooltip
--------- bottom
```

stated slightly differently...

|Grandparent element|Parent Element(s)|Child element|
|----|----|-----|
|`.abt_tooltip`|`.abt_arrow_up`, `.abt_arrow_down`|.abt_tooltip_touch_close|

Child elements are on top of their parent

Hope that helps

**Comment by dsifford** [comment]
Setting this as resolved. If you have any other questions feel free to chime back.
