### ISSUE TITLE
ABT Plugin affects other plugin dialogs

### ISSUE THREAD

**Issue by dmayhem** [dsifford/academic-bloggers-toolkit#337]
**ABT Version:** 4.10.0

**PHP Version:** 5.6.30

**Theme:** Primer, Twenty Sixteen

**Plugin List:**
- Academic Blogger's Toolkit
- ZipRecipes
- Contact Widgets
- WP Statistics
- WP SpamShield

**Browser:** Google Chrome (Version: xxx) Chrome, Linux (Version: 60.0.3112.78)
Android Chrome (Version: 59.0.3071.115)
Firefox, Linux (Version: 54.0)

**Expected behavior:**
Modal Dialogs should have opaque backgrounds

**Actual behavior:**
If Academic Blogger's Toolkit is enabled, backgrounds for *other* plugins modal dialogs become transparent, making them extremely difficult to read. Specifically ZipRecipes. If I disable Academic Blogger's Toolkit plugin, the ZipRecipes dialog displays properly.
[http://desertraven.com/images/dialog_screenshot.png](url)

**Console messages:**
```js
// Paste messages here
No errors
```

**Comment by dsifford** [comment]
@dmayhem Thanks for the report.

I'm replacing the tinymce dialogs with completely custom dialogs in the next update. That should handle this.

The update should be released relatively shortly (as soon as I'm able to get the test coverage to 100%) -- Currently it's ~85%.

**Comment by dmayhem** [comment]
Thanks for the response!

**Comment by dsifford** [comment]
Sorry for the delay... Just published the update that should resolve this. Let me know if you have any other issues.
