### ISSUE TITLE
Bug - "An unexpected error occured"

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#340]
This bug happened a few times just right now. Then it stopped happening. Can no longer reproduce. I would try to edit any post, and I would get the following popup:
![image](https://user-images.githubusercontent.com/17968340/29446559-a31720d0-83a1-11e7-9170-1283c67fca2a.png)

Then the loading wheel would just spin forever:
![image](https://user-images.githubusercontent.com/17968340/29446612-062d7796-83a2-11e7-8ac6-883d5ecd2c64.png)

When it did happen, it was only on pages/posts that did not already have citations in it. Probably just a coincidence though.

**Comment by dsifford** [comment]
Most likely the result of a spotty internet connection. Next release will have better caching so that should take care of this.

**Comment by metallikat36** [comment]
Yes, my connection is spotty. That's probably the cause. Thanks.
