### ISSUE TITLE
Remove Footer

### ISSUE THREAD

**Issue by primalsean** [dsifford/academic-bloggers-toolkit#343]
**ABT Version:** 4.10.0

**PHP Version:** 5.6

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**

**Console messages:**
```js
// Paste messages here

```
Hi,

How would I keep the citation numbers but remove the footer reference? Example: https://www.screencast.com/t/c9BItwvAn

When I remove them by deleting the popup citation doesn't work.

**Comment by dsifford** [comment]
No sweat!

Adding the following lines to your child theme's css file (preferred) or to the css overrides box located in the options page should do the trick.

```css
#abt-bibliography {
    display: none;
}
````

Let me know if you have any other issues 👍

**Comment by primalsean** [comment]
Hi,

I'm having that issue again.

I made an edit to the list and it started showing at the bottom of the
page, https://primalherb.com/product/neuro-shroom/
but my other unedited pages still show correctly.
https://primalherb.com/product/endo-adrenal/

Please advise how to remove the box at the bottom of the page - Thanks So
Much!

**Comment by dsifford** [comment]
I'm not sure why that would be happening to be honest. The references on that page you linked are not rendering inside an `#abt-bibliography` div, and that is not how the plugin is coded to work. So either somebody edited something causing the references to appear in an unintended location or another plugin is clashing with this one.

The only advice I can give is to try again or start again.
