### ISSUE TITLE
Probable RTL issue (arabic locale)

### ISSUE THREAD

**Issue by ezzeldean** [dsifford/academic-bloggers-toolkit#348]
Hello,

I have an issue when add or edit any post and I see this error message:

http://i.imgur.com/l7Lu3WM.jpg

And loading icon still running.

**Comment by dsifford** [comment]
@ezzeldean What web browser are you running? What steps do you take to trigger the issue?

**Comment by ezzeldean** [comment]
Just activate the plugin and see this error. And this issue on all browsers.

**Comment by dsifford** [comment]
It is most likely a conflict with another plugin you have installed. 

Can you provide a list of your plugins?

**Comment by ezzeldean** [comment]
Don't be shocked, I'm really wicked to install all these additions :)

- Archives Calendar Widget
- BAW Login/Logout menu
- Block Bad Queries (BBQ)
- Contact Form 7
- Easy Footnotes
- Email Verification / SMS verification / Mobile Verification
- File Manager
- Google Analytics by BestWebSoft
- Google Captcha (reCAPTCHA) by BestWebSoft
- Hide Admin Bar From Non-admins
- Hide Title
- If Menu
- iThemes Security
- MailChimp for WordPress
- miniOrange 2 Factor Authentication
- myCRED
- PDF & Print by BestWebSoft
- Remove Dashboard Access
- SSL Insecure Content Fixer
- The Events Calendar
- TinyMCE Advanced
- UsersWP
- WP User Frontend
- WP-Polls
- WPML Media
- WPML Multilingual CMS
- WPML String Translation
- WTI Like Post
- Yoast SEO
- bbPress
- User Switching
- WordPress Social Login

**Comment by dsifford** [comment]
@ezzeldean Hmm... None of those plugins jump out at me as being a known compatibility issue. 

Is there any way you can record your screen or something so I can see exactly what is happening?

**Comment by ezzeldean** [comment]
Sure,

http://i.imgur.com/FteqjIG.png

http://i.imgur.com/MP1eNNP.png

**Comment by dsifford** [comment]
Ah... You've got an RTL locale.

I haven't really ever dug into RTL locales and checked. I apologize for the lack of support!

This is likely an issue on my end. I'll check into this soon and (hopefully) will include a fix on the next major release (which is due shortly).

Side note: Thanks for also volunteering to contribute translations! Your translations will also appear on the next update. 😄

**Comment by dsifford** [comment]
All fixed. The fix will be available on the next update (should be soon)

**Comment by ezzeldean** [comment]
Thank you so much and I'm haven't forgotten the translation ;)

**Comment by ezzeldean** [comment]
Hello Derek,

What's new about the next update? :)

**Comment by dsifford** [comment]
Still a work in progress. Close though. 

I had to wait for an update to one of the project's dependencies. That update finally happened and now all that's left is to fix some breaking changes and then it should be good to go.

I haven't had any other hands on this to test other than my own. Would you be interested in testing a pre-release copy of the plugin? I can build and zip one for you. 

Thanks

**Comment by ezzeldean** [comment]
Sure,
I can help you to testing :)

**Comment by dsifford** [comment]
Thanks. I appreciate your patience.

Give this a shot and let me know how it works for you.

[academic-bloggers-toolkit.zip](https://github.com/dsifford/academic-bloggers-toolkit/files/1346554/academic-bloggers-toolkit.zip)

**Comment by ezzeldean** [comment]
Thanks. :)

**Comment by ezzeldean** [comment]
Great, Issue resolved. :)

Now, where can I send you translation files? From translation project or PO file?

**Comment by dsifford** [comment]
Glad to hear! I added a few new features so if you happen to run into any other unrelated bugs, please let me know.

Probably the most exciting feature is the fact that now the document and bibliography automatically updates when you delete in-text citations. I'm anticipating the most unforeseen bugs to occur there.

> Now, where can I send you translation files? From translation project or PO file?

If you could just finish them up on POEditor, I'll add them in. Here's the link again https://poeditor.com/join/project/PGYLKWQM5h

Looks like you're already about 9% done! 😄 

Thanks again.

**Comment by dsifford** [comment]
@ezzeldean Hows the plugin working? Any issues?

**Comment by ezzeldean** [comment]
Sorry for the delayed response, I was out of the country.

Everything is very excellent, and I've started to resume translation now :)

**Comment by dsifford** [comment]
Sounds great! No rush, just wanted to make sure everything has been running smoothly.

**Comment by ezzeldean** [comment]
I really stood by my side and let me if I could donate via PayPal when I get my monthly salary :)

**Comment by dsifford** [comment]
Donations are welcomed, but certainly not expected. Just happy that you're able to write high-quality academic blog posts 😄

**Comment by ezzeldean** [comment]
I want to thank you in any way even if it is a symbolic gift :)
Anyway, I will always be with you, of course, if you do not mind <3
