### ISSUE TITLE
mobile rendering possible bug

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#36]
Again, I am using an emulator, so this could be a false observation, but look at this:
http://mobiletest.me/iphone_5_emulator/?u=http://www.earthmedresearch.org/community-guidelines/
Hover over the first tooltip (i.e. [1,2]). Note that the long URLs do not wrap properly. Those two references are of type "Website". I don't see this problem with other types of references, which don't have long urls in them.

**Comment by dsifford** [comment]
Yeah, I think that site is a bit shaky. Here's how it looks using chrome devtools for an iphone 5.

![image](https://cloud.githubusercontent.com/assets/5240018/14836187/4ca78278-0bdc-11e6-86f9-383c5b1609a5.png)

Closing this for now, but if something else turns up, feel free to comment back on it.
