### ISSUE TITLE
Error when providing link since last update

### ISSUE THREAD

**Issue by HoussenMoshine** [dsifford/academic-bloggers-toolkit#369]
**ABT Version:** 4.11.0

**PHP Version:** PHP Version 5.5.9-1ubuntu4.22

**Theme:** Hueman

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

Insert link

**Actual behavior:** Impossible to insert link via Add References **I**

**Console messages:**

JQMIGRATE: Migrate is installed, version 1.4.1
index.js:30 Deprecated TinyMCE API call: <target>.onMouseUp.add(..)
%7Bdefault_value%7D Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:30 POST https://sitexxxx/wp-admin/admin-ajax.php 501 (Not Implemented)

// Paste messages here

I have a message error saying that i need to enable the dom and libxml extensions.  I have checked and theses extensions are enabled. The error happen only since the laste update. Disable all plugin, error is still here. Screen capture joined.

![academic-toolkit-error-1](https://user-images.githubusercontent.com/8509831/31656197-98d4f162-b333-11e7-8f00-d39ba7f98103.jpg)

```

**Comment by HoussenMoshine** [comment]
Hi, thanks for the fast answer. But despite the new update, the error is still here.

**Comment by dsifford** [comment]
@HoussenMoshine Have you had a recent change in servers? Or have you upgraded your server recently?

Looks like your server is blocking `POST` request calls to `admin-ajax.php` which is needed for a bunch of internal processes. Can you check with your hosting provider?

Sorry for the trouble. Let me know.

**Comment by dsifford** [comment]
See here for more details: https://github.com/woocommerce/woocommerce/issues/9838

**Comment by HoussenMoshine** [comment]
@dsifford Yes, it seem that something blocking the POST request, but i can't find out for the moment. It's possible to use a older version of the plugin?

**Comment by dsifford** [comment]
@HoussenMoshine Yes, it's possible as of right now to use past versions of the plugin by downloading it directly from wordpress.org (https://wordpress.org/plugins/academic-bloggers-toolkit/advanced/).

However, as soon as WordPress 5.0 lands, all previous versions of the plugin will stop working since WordPress is switching out TinyMCE for their new Gutenberg Editor (this current version will also fail, but it's set up to quickly support Gutenberg once the time comes).

**Comment by dsifford** [comment]
Possibly related to #387

**Comment by dsifford** [comment]
@HoussenMoshine You were correct. This is an error resultant from a typo that was made during the last update. Found the issue. 

Thanks for your patience. I'll have a fix out for this soon.

**Comment by HoussenMoshine** [comment]
Thanks for following the issue and fixing it. I will check out in the next update

**Comment by smtech12** [comment]
I am using Legacy V3 just before a week for integration Woo Commerce Product Posting using Rest Api's on WC Version 2.5.5.
At that time products with all details are working fine but variable product detail are not posted with all details.
now i have updated the Woo Commerce Version 2.5.5 to 3.2.6 and i have WP Version 4.5.12 according to documentation i can use v1 and v2 both for integration 
but when ever i post product it's giving me an error 
**{
    "errors": [
        {
            "code": "woocommerce_api_missing_product_data",
            "message": "No product data specified to create product"
        }
    ]
}**
Note: I have Posted documentation given example of simple product  for the cross check it gives same error as define above.
your kind help needed 
Thanks
