### ISSUE TITLE
Duplicate references

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#37]
I really don't care about this, but just giving you a heads up. The plugin allows for repeating the same references multiple times. Of course, anyone manually writing a paper in real life can always make that mistake, so I don't consider an automated check on that to be a necessary feature.  Just letting you know though.

**Comment by dsifford** [comment]
Good point. Let me think this one over and see if there is any easy way to implement a check.

**Comment by dsifford** [comment]
@metallikat36 Thanks for the suggestion. This will be included in the next release.
