### ISSUE TITLE
Adding citation to existing citation block removes references

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#371]
I think I may have already reported this, but this example illustrates another facet of the bug.

![image](https://user-images.githubusercontent.com/17968340/31741278-824997ce-b408-11e7-97a6-f8dc76fd3583.png)
Here I am about to add a citation to an existing block.

![image](https://user-images.githubusercontent.com/17968340/31741311-a9b97ee6-b408-11e7-826d-855131e77494.png)
After I inputted a single Pubmed reference, this is the result. It removed several references and put them in the uncited list.

**Comment by dsifford** [comment]
I'll keep this in mind, but I won't likely be able to diagnose the issue unless it can be reproduced in a minimal, reproducible example. 

Too many factors at play with a document containing 100+ references.

**Comment by metallikat36** [comment]
No sweat. I just work around this by removing all references in a citation block, then adding them all back (plus the new reference I wanted to add).
