### ISSUE TITLE
Expanding list of citation styles crashes the Firefox

### ISSUE THREAD

**Issue by necxelos** [dsifford/academic-bloggers-toolkit#374]
Hello

I'm the psychology researcher that tries to create his own webpage/blog. I have some basic web-design knowledge but mostly I rely on reverse-engineering snippets instead of writing my own code. I use Wordpress with probably the most popular Theme out there - X Theme from Themeco. I also use Firefox as my first choice for browsing the internet and working on the site.

Enough about me. The issue is:
- I installed Your plugin, which seemed to perfectly fit into my needs.
- I created testing site in my localhost environement.
- I installed Your plugin and tried to change default styling via settings dropdown list of 1300 styles.
- Firefox crashes (technically stops responding - I close it using Windows kill task everytime).
- Works perfectly fine in Chrome at the same time using the same test site.

Thanks in advance for investigating this
necxelos

**Comment by dsifford** [comment]
Thanks for the report. What version of firefox is this happening in?

**Comment by necxelos** [comment]
56.0.2 (64 bit) (newest version)

P.S. A sidenote: I failed to find **APA (American Psychology Association)** in Your styles list which is the most used Psychology styling in this science with some usage in other social sciences too. I can easily reproduce it using custom style though, so it's not as big of an issue as the crash :)

**Comment by dsifford** [comment]
Hmm... I'll have to check it out and see if I can reproduce. I'll try to take a look at it this weekend.

Also, APA is definitely there. If you're using the search feature on the reference list itself, the fuzzy matching is a bit wonky. Try typing exactly "American Psychological Association" to see if that works... Typing "Psychology" rather than "Psychological" likely causes it to not match.

**Comment by necxelos** [comment]
My bad.
Indeed APA is there (all editions in fact).

I assumed it's alphabetically sorted, but things starting with "American" aren't. American Psychologist is alone between Americal Political Science Review and American Review of Canadian Studies, APA is between AORN and APCBEE and everything else is in proper alphabetical order elsewhere :)

Am I correct that it's due to the fact that "hidden/coded" names by which those are sorted are different from what end user sees?

Anyway thank You very much for insanely quick response :)

**Comment by dsifford** [comment]
No problem. Yeah, ordering gets shuffled based on match rank on the reference list search box. A fully alphabetical list can be found on the options page.

**Comment by necxelos** [comment]
If You mean:
_Backend > Settings > Academic Blogger's Toolkit > Default Citation Style_
...than it's not sorted properly there either. I was talking about this part in my previous post (I just installed and launched Chrome and did it there for the sake of testing).

**Comment by dsifford** [comment]
Ah, I see.. It's likely sorted by the unique ID, rather than by the label... That's a mistake, I'll adjust that too...

FYI: All the styles are pulled directly from here: https://github.com/citation-style-language/styles -- The filenames you see listed in that repo are (likely) the sort order of the styles in the select box.

**Comment by dsifford** [comment]
@necxelos Circling back to this issue finally. Is this crash still affecting you? Can you confirm that the crash occurs simply when toggling the list of citation styles in the reference list?

**Comment by dsifford** [comment]
Haven't heard back. Assuming this has been resolved.
