### ISSUE TITLE
ris import not working

### ISSUE THREAD

**Issue by dmayhem** [dsifford/academic-bloggers-toolkit#384]
**ABT Version:** 4.11.3

**PHP Version:** 5.4.16

**Theme:** Primer

**Plugin List:**
- Academic Bloggers Toolkit
- Contact Widgets
- WP Statistics
- WP-Spamshield
- Zip Recipes

**Browser:** Google Chrome Version 62.0.3202.74

**Expected behavior:**
import reference list

**Actual behavior:**
Error!
The selected file could not be processed

Note that this happens with two ris files that I have previously had no issues with importing. The files have not been modified since 30 August 2017

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
@dmayhem Thanks for the report.

 Can you please open an issue and also share the file in question here: https://github.com/dsifford/astrocite/

Thanks in advance
