### ISSUE TITLE
Requests on static publication lists

### ISSUE THREAD

**Issue by fortarrigo** [dsifford/academic-bloggers-toolkit#386]
Hi. I have two requests concerning static publication lists.

I use Academic bloggers toolkit not only to add references in articles and page, but for my Bibliography section.

Request 1
I have a long bibliography. Would be beautiful to select all references clicking from the first to the last (i.e. with Shift click).

Request 2
Now in static publication lists there is the number before every reference. Would be beautiful an option to delete the reference number on static publications list.

Request 3
I need to sort (A-Z) all the references in Bibliografy. Now, if you insert a new reference in static publication list, is displayed first than others. Would be beautiful an option to sort references in static publication lists.

Thanks

**Comment by dsifford** [comment]
Thanks for the feedback.

Re: Request 1 -- Seems reasonable. I'll look into it.

Re: Request 2 -- Should already be possible if you select a different, unnumbered citation style prior to inserting your list.

Re: Request 3 -- This should also be possible already if you select a citation style that sorts bibliographies alphabetically (80% sure here. I'll have to double check when I get some time).

**Comment by dsifford** [comment]
@fortarrigo Added shift-click functionality in `v4.12.0`. Thanks for the feedback.
