### ISSUE TITLE
Plugin not working for an editor status, but fine for administrator status

### ISSUE THREAD

**Issue by gconyers** [dsifford/academic-bloggers-toolkit#387]
**ABT Version:** 4.11.3

**PHP Version:** 5.5.38

**Theme:**: Make Plus

**Plugin List:**
- Academic Blogger's Toolkit
- Contact Form 7
- Disqus Comment System
- Edit Flow
- Exec-PHP
- Google Analytics for WordPress by MonsterInsights
- Jetpack by WordPress.com
- Make Plus
- Participants Database
- PopupAlly
- Re-add text underline and justify
- Sensei (and all the plugins to make it fully functional)
- Shortcodes Ultimate
- WooCommerce
- WooCommerce First Data Payeezy Gateway
- WooCommerce Name Your Price
- WooCommerce Services
- Wordfence Security
- WP Super Cache
- Yoast SEO
  |
-- | --

**Browser:** Chrome 62.0.3202.94

ABT to function correctly for ALL users.

One of my writers who has _editor status_ on our site noted that the plugin isn't functioning for her. I checked for me, and it's working fine ─ I'm an administrator. I've attached a screenshot of the error message she is getting. 

The Chrome version listed above is for her computer, not mine.

Let me know if you need any more info.

<img width="586" alt="screenshot" src="https://user-images.githubusercontent.com/4678920/33434102-38a7b374-d5ac-11e7-9009-ecc1e8481c7c.png">

**Console messages:**
```js
// see above screenshot.

```

**Comment by gconyers** [comment]
I should also note that when I go into the plugin the PHP in question is enabled in the settings. At least as an administrator.

**Comment by dsifford** [comment]
Hm.. interesting. Thanks for the report.

I'll have to dig a bit deeper into this to figure it out. I'll do my best to get to this when time allows.

**Comment by gconyers** [comment]
Let me know if there's anything we can do to help on this end.

Until then,
G.


<http://insanitek.net/>

Grace Conyers Founder and head geek
Email me: gconyers@insanitek.net
Call me: 317.759.1284

[image: Twitter] <https://twitter.com/Insanitek> [image: Facebook]
<https://facebook.com/InsanitekRD> [image: LinkedIn]
<https://linkedin.com/company-beta/3315307/> [image: Google+]
<https://plus.google.com/+InsanitekResearchandDevelopment> [image:
Instagram] <https://instagram.com/insanitek/> [image: Pinterest]
<https://pinterest.com/Insanitek/>

<http://insanitek.net/>insanitek.net

To get me on your terms, make an appointment:
*https://insanitek.acuityscheduling.com/*
<https://insanitek.acuityscheduling.com/>

**Comment by dsifford** [comment]
@gconyers Looks like this is indeed a bug. There was a typo made at some point during the last update that I didn't catch. 

What's strange is that I'm not sure how you're able to make it work for yourself? This should be broken for everybody, including administrators.

Regardless, thanks for your patience. I'll have a fix out for this shortly.

**Comment by gconyers** [comment]
No worries! Though, I'm not sure how it works for me either. I'm glad I
could help, though. You made one of the most useful plugins in my opinion.


<http://insanitek.net/>

Grace Conyers Founder and head geek
Email me: gconyers@insanitek.net
Call me: 317.759.1284

[image: Twitter] <https://twitter.com/Insanitek> [image: Facebook]
<https://facebook.com/InsanitekRD> [image: LinkedIn]
<https://linkedin.com/company-beta/3315307/> [image: Google+]
<https://plus.google.com/+InsanitekResearchandDevelopment> [image:
Instagram] <https://instagram.com/insanitek/> [image: Pinterest]
<https://pinterest.com/Insanitek/>

<http://insanitek.net/>insanitek.net

To get me on your terms, make an appointment:
*https://insanitek.acuityscheduling.com/*
<https://insanitek.acuityscheduling.com/>
