### ISSUE TITLE
Edition field: "Please match the requested format"

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#388]
**ABT Version:** 4.11.3

**PHP Version:** 5.6

**Theme:** GeneratePress

**Plugin List:**
- Loginizer

**Browser:** Firefox 57.0

**Expected behavior:** When entering a book reference manually, in the edition field I type 2nd.  It is accepted.

**Actual behavior:** Instead, when I click Confirm, a popup at that field says "Please match the requested format".  I don't see any requested format, nor did I find any mention of it in the Wiki.

**Console messages:**
```js
// Paste messages here
Didn't see any.
```

**Comment by dsifford** [comment]
There should be placeholder text showing the format in that field. If not, I'll look into adding that.

To clarify: The field should be a digit only. So, in your case, it should be `2` not `2nd`.
