### ISSUE TITLE
My "Citation link style" is stuck

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#391]
**ABT Version:** 4.11.3

**PHP Version:** 5.6

**Theme:** GeneratePress

**Plugin List:**
- Loginizer

**Browser:** Firefox 57

**Expected behavior:** When I change "Citation Link Style" in Settings, see it change on pages (at least after refreshing the bibliography).

**Actual behavior:**  It did work fine until a few days ago,  Now for some reason "Citation Link Style" is stuck on "whenever possible (full surround)".  When I choose a different style in the settings and click update, that style is chosen when I return to settings, but all that ever shows in pages is the full surround style (see image below, entire reference is a link - the settings indicate the subtle style).  

Clicking "Refresh reference list" doesn't help.

Did I somehow corrupt a settings file or something?

**Console messages:**
None

![capture](https://user-images.githubusercontent.com/6004417/33626052-c0a0922e-d9b6-11e7-8ab6-5f141ffb39bd.PNG)

**Comment by dsifford** [comment]
Might be a bug. Not totally sure. I'll give this a look soon when I get some free time.

Thanks for the report 👍

**Comment by dsifford** [comment]
Finally got some time to look at this.

> It did work fine until a few days ago, Now for some reason "Citation Link Style" is stuck on "whenever possible (full surround)".

Not sure how this would have worked ever in the past. It was set to cache and persist whatever the link style was set when the post was created. I removed that setting from cache so now the updated settings should load properly.

Fix will be on the next release.

**Comment by glorious1** [comment]
Great, thanks.  Maybe nobody ever tried to change citation link style after creating a page.
