### ISSUE TITLE
Tooltips not working for me after ABT 4.12.0 update

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#394]
**ABT Version:** 4.12.0

**PHP Version:** 5.6

**Theme:** GeneratePress

**Plugin List:**
- none after deactivating others to test

**Browser:** Firefox 57.0.1

**Expected behavior:** Tooltips pop up when clicking in-text citation.

**Actual behavior:** Nothing happens when hovering or clicking except cursor does turn into finger (recognizing link).

**Console messages:**
ReferenceError: jQuery is not defined
[Learn More]
frontend.ts:1:6
<anonymous>
frontend.ts:1:6
n
bootstrap%20d24dcb6e7ac0645d66d3:19
<anonymous>
frontend.js:9214:17
n
bootstrap%20d24dcb6e7ac0645d66d3:19
<anonymous>
bootstrap%20d24dcb6e7ac0645d66d3:62
<anonymous>
frontend.js:1:9
// Paste messages here

Note: The reference tooltips did pop up before the newest version of ABT.  I also tried making a new page and putting in a new reference, still didn't get the tooltips.

**Comment by dsifford** [comment]
Very strange... jQuery is a built-in dependency of WordPress. Not sure why this would be happening. 

Is this still occurring for you?

**Comment by glorious1** [comment]
Yes, unfortunately.  You can see it on this page of the test site, where I was playing with the test1.ris file I sent:
http://109.73.239.174/~cookand3/forestpathology.org/thank-you

**Comment by dsifford** [comment]
Hmm.. I might have an idea what's happening. Thanks for the test url. Super helpful!

**Comment by glorious1** [comment]
Well I'll be.  Today the tooltips started working again.  I wish I could say way why.  I updated two plugins that aren't even activated (Akismet and Force Regenerate Thumbnails, and I added bbPress.  Now the only console output is "JQMIGRATE: Migrate is installed, version 1.4.1".

**Comment by dsifford** [comment]
@glorious1 One of the other two plugins likely is requiring jquery on the same page where ABT needs it. So, by proxy, the ABT requirements are being fulfilled. 

I'll still have to add in an explicit requirement for it.

Thanks for your patience!
