### ISSUE TITLE
Issue with Advanced Custom Fields

### ISSUE THREAD

**Issue by billmorton** [dsifford/academic-bloggers-toolkit#40]
If i click add reference, i two pop ups, one on top of the other, with no error in the console. It won't let me add a reference, the button just clicks, but doesn't close the pop up or add the reference to the page.  

I have tracked the issue down to an issue with the plugin advanced custom fields. https://wordpress.org/plugins/advanced-custom-fields/

I thought it might be an issue with my theme, so i have tried a new blank WordPress install (4.5.1) running twentyfifteen. With the only plugins being ACF and the toolkit (which works great without ACF active!), but the error still occurs.

I'm not too sure whats causing the issue though.

![popup-issue](https://cloud.githubusercontent.com/assets/17826476/14882837/b40fce46-0d32-11e6-9860-0a16e17c1687.jpg)

**Comment by dsifford** [comment]
Thanks for the info @billmorton 

It's likely a naming clash. I'll check it out later this evening or tomorrow and try to get an update out sometime soon after. 👍

**Comment by dsifford** [comment]
@billmorton I reached out the the ACF dev to see if we might be able to put our heads together on this. His plugin is far too large for me to reasonably sift through.

**Comment by dsifford** [comment]
@billmorton - Issue is fixed. I'll include the fix on the next update (should be released sometime this weekend).

Thanks for the heads up :+1:

**Comment by billmorton** [comment]
Lovely job, cheers for the fantastic plugin!
