### ISSUE TITLE
ABT losing track of citations and error

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#402]
**ABT Version:** 4.12.1

**PHP Version:** 5.6

**Theme:**GeneratePress

**Plugin List:**  All others 

deactivated
- Plugin 1
- Plugin 2

**Browser:** Firefox 57

**Expected behavior:** Place citations, update page, citations remain.

**Actual behavior:** Starting fresh, I import a RIS file to a page with no citations.  Start placing citations.  When I update, ABT now shows no cited references.  The citation text is still there, but when I preview the page, they are nonfunctional and there is no reference list at the bottom.

When I go back to editing and try to enter a new reference, this error appears:
"An unexpected error occurred
TypeError: this.registry.citationreg.citationById[o[0]] is undefined"

At first I could delete all references and start from the top, with the same result.  Now, when I delete all references, most reappear when I update the page.

**Console messages:**
```js
ReferenceError: jQuery is not defined
```
[myrisfile.txt](https://github.com/dsifford/academic-bloggers-toolkit/files/1591655/myrisfile.txt)

**Comment by dsifford** [comment]
Strange.

If you have a cache plugin, can you try clearing all your server cache. That includes cloudflare if you are set up to proxy through them as well.

Additionally, can you also try clearing your browser cache and then attempt it again?

**Comment by glorious1** [comment]
Clearing the browser cache didn't help, but clearing the server cache (if that's what I did) apparently did.  SiteGround has a cPanel cache tool.  I clicked the flush cache button.  Now it is acting normally.  Thanks!
![screen shot 2017-12-28 at 11 17 07 am](https://user-images.githubusercontent.com/6004417/34419865-78b8eae6-ebc3-11e7-8422-73172075f8dd.png)

**Comment by dsifford** [comment]
How frustrating! 

I've ran into this sort of thing dozens of times and have still yet to figure out a reliable way to bust old cache on plugin updates.

I'll look back into this soon to see if I can figure out a better strategy than I'm currently using.

Thanks for reporting back!

(PS: The giveaway this time was the fact that your console had the jQuery error in it still. Last update removed the jQuery dependency! 😝)

**Comment by glorious1** [comment]
Now that I know how to fix it, it’s no problem, easy fix.  So if I understand right, the server was still using the old ABT plugin, at least in part, because it was stored in cache?  Good to know.

**Comment by dsifford** [comment]
Yep. Cache plugins are generally pretty liberal with caching static assets (javascript files being the cause of this issue, but also images, css, etc.), so unless you manually clear it out you or your visitors will be served the stale content until the expiration date occurs for the file in question (which, for javascript, is generally ~30 days IIRC).

This is a good thing though. It makes your site's load time orders of magnitude faster than if you weren't caching. But, as you've seen, it often causes these sorts of issues with plugin files if the plugin is updated regularly (the issue being the browser is requesting a file that no longer exists on disk).

I'm certain there's a better way to bust cache. I'll do some reading and see if I can sort it out on my end.
