### ISSUE TITLE
Cannot manually edit any reference except for author

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#412]
**ABT Version:** 4.13.0

**PHP Version:** 7.0.27

**Theme:**GeneratePress

**Plugin List:**
All deactivated

**Browser:** Firefox 57

**Expected behavior:** Be able to edit.

**Actual behavior:** Can edit authors only.  All other fields locked

**Console messages:** None
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Sorry for the trouble. I'll take a look at this as soon as I can.

**Comment by dsifford** [comment]
Duplicate of #411
