### ISSUE TITLE
Dates added by autocite causing problems

### ISSUE THREAD

**Issue by dsifford** [dsifford/academic-bloggers-toolkit#418]
Related: https://github.com/dsifford/academic-bloggers-toolkit/issues/411#issuecomment-357817774

<blockquote>
    <ol>
	<li>I click on the plus button to add a source.</li>
	<li>I click "add manually".</li>
	<li>I type a link in autocite box.</li>
	<li>It loads the page information with the date.</li>
	<li>I click "add reference" and it says there is a date format error even if it is correct.</li>
    </ol>
</blockquote>

cc: @cwbullet

**Comment by somdeb-ghose** [comment]
I think the reason why it says so is this : autocite shows dates with the format yyyy/m/dd, while the required date format is yyyy/mm/dd. Perhaps either a relaxation is the format requirements or a tightening up of the autocite might be in order?

**Comment by dsifford** [comment]
@somdeb-ghose Good catch. If that's the case, I'll fix that on my end as soon as I get time.

**Comment by dsifford** [comment]
Fixed in 4.13.3.
