### ISSUE TITLE
Cannot insert citations when set locales to Thai

### ISSUE THREAD

**Issue by Tammakit** [dsifford/academic-bloggers-toolkit#42]
I tried to add a citation when set locales to Thai and got the error in the console.

> Failed to load resource: the server responded with a status of 404 (Not Found)
> https://raw.githubusercontent.com/citation-style-language/locales/8c976408d3cb287d0cecb29f97752ec3a28db9e5/locales-th.xml

But adding a citation in English was fine.

**Comment by dsifford** [comment]
Can you send me a link to the reference that you used that created that issue? I think I may know the reason why...

Thanks for the heads up 👍

**Comment by Tammakit** [comment]
I recorded a video when the error occurred.

https://youtu.be/kAqwXP5xqGU

I think the problem is at the bottom of the file tinymce-entrypoint.js.

**Comment by dsifford** [comment]
Awesome, thanks so much @Tammakit !

I'm almost positive I know what the error is. I'll get working on this now and keep you posted. The fix _should_ be pushed out sometime this weekend (unless I'm wrong, then it might take a bit longer).

**Comment by dsifford** [comment]
@Tammakit Update: I've fixed the error on my end, however I've run into another error on the end of the CSL processor that I'm using. 

I can retrieve citations using your locale, however the processor is hiccuping and sending back US locale citations for everything. 

Good news: you'll be able to parse citations now (when I push the update). 
Bad news: It technically won't be in the correct locale until I can get in touch with the CSL guys.

**Comment by Tammakit** [comment]
Thank you, Derek.

**Comment by dsifford** [comment]
You're very welcome. If you'd like, you can follow along here for progress updates: https://github.com/Juris-M/citeproc-js/issues/4

**Comment by dsifford** [comment]
@Tammakit Possibly some good news: It turns out, the fix that I pushed out earlier today _should_ have fixed all the issues you were having. 

Also, the locale _should_ be correctly set to Thai. 

Please let me know if your citations aren't being processed correctly and I'll troubleshoot further. As of right now, I'm going to mark this issue fully resolved.

Thanks again! 👍

**Comment by Tammakit** [comment]
@dsifford I've already updated the plugin and it works very well. I appreciate your dedicated work.

Thank you very much. :+1:

**Comment by dsifford** [comment]
Great! Thanks again for the feedback.
