### ISSUE TITLE
Incorrect reference sorting in tooltips under certain circumstances

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#421]
**ABT Version:** 4.13.2

**PHP Version:** 5.6

**Theme:**GeneratePress

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Firefox 57

**Expected behavior:**Bibliography, inline citations, and tooltip all sort references consistently.

**Actual behavior:**
First let me say that last bug fix was a game changer for me.  For the first time I can edit or add references manually.  Also, for the first time, I am able to use a custom style.  Which leads to other questions. I doubt this is a bug, maybe a style issue.

The CSL system seems great, but it is mind-boggling.  The documentation illustrates how to do some very simple things, like change an element to italic or bold.  Anything more complicated than that, you're on your own.  I'm trying to learn it by trial and error. Anyway, I've got a style now where the bibliography and citations have the exact same sorting rules (author-issued-title).  But I'm getting some anomalies I can't understand (see screenshots).  In one case the inline citation is out of order. In another case the tooltip has references presented out of order.

The inline citation order is probably my bad, as editing the style is mysterious.  But I don't see that I have any control over ordering inside the tooltip specifically.    Any thoughts?

![tooltip out of order](https://user-images.githubusercontent.com/6004417/35102828-4c038cf4-fc21-11e7-8878-3413d2116c46.png)
![inline citation out of order](https://user-images.githubusercontent.com/6004417/35102829-4c1ef714-fc21-11e7-837c-33a9195950de.png)

**Console messages:**
```js
// Paste messages here

```

**Comment by glorious1** [comment]
I managed to fix the inline citation order (second screenshot above) by specifying citation-number sorting for the inline citations, instead of author-issued-title.  But the tool tip is still reversing refs 2 and 7.
The csl file is attached.
[mycologia_numbered.txt](https://github.com/dsifford/academic-bloggers-toolkit/files/1643299/mycologia_numbered.txt)

**Comment by dsifford** [comment]
Good catch. Can't remember off the top of my head how exactly the order in the tooltips is determined. But for certain I can tell you that I hadn't considered all the ways that the citation numbers can be sorted. 

IIRC, it just grabs them from the bibliography in the order that they are printed.

I'll see maybe if .I can adjust so that citation order is considered. No guarantees when I can get to that though.

**Comment by glorious1** [comment]
Thanks.  Just to be clear, in my testing, multiple references appear in a tooltip sorted by the order in which they were clicked.  It's not too hard to click them in alphabetical order if there aren't many, but yes, putting them in the bibliography (or citation) order would be a nice refinement.

**Comment by dsifford** [comment]
@glorious1 Which citation style causes this to happen? 

Or, more specifically, which one uses `author-issued-title` for inline citations? Tried to look at a few of the common ones now but couldn't find any that were sorted that way.

**Comment by glorious1** [comment]
Sorry I neglected your question for so long.  I'm not sure I understand it.  After thinking and studying styles, I think you mean that most numbered styles sort the references in the order they were cited.  And you're asking which numbered style sorts by author, issued?

In addition to my custom one, there are these:
http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fcouncil-of-science-editors-alphabetical
http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fspringer-basic-brackets-no-et-al-alphabetical

The bibliography and inline citations (when there are multiple citations) are sorting correctly.  The part where it doesn't is the popup.  The order of references in the popup, at least for me, is determined by the order I click them in.

**Comment by dsifford** [comment]
Got it. 

So, to confirm, `Council of Science Editors, Citation-Name (numeric, sorted alphabetically)` is a style that will trigger this issue correct?

**Comment by glorious1** [comment]
Let me test it tomorrow.  Right now I only know my custom style does.

**Comment by glorious1** [comment]
Yes that CSE style does the same thing.  Order of references in the tooltip is determined by the order you click them in.  Direct link to download the style:
http://www.zotero.org/styles/council-of-science-editors-alphabetical

**Comment by dsifford** [comment]
I can't reproduce this issue with that style @glorious1

**Comment by dsifford** [comment]
Disregard my last... I was just able to reproduce.

**Comment by dsifford** [comment]
Reproduction video from #516 : https://www.youtube.com/watch?v=iXr2YOhZJRY&feature=youtu.be
