### ISSUE TITLE
All DOI links broken

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#424]
For example, see tooltips for citations 3 and 10 in this article:
https://www.earthmedresearch.org/antidepressants-fraudulent/
Note how the hyperlink is incorrectly parsed or something.

If you look at citation #10 tooltip, for example, the actual DIO is "10.1016/j.ebiom.2017.09.031"
(http://www.ebiomedicine.com/article/S2352-3964(17)30385-7/fulltext)
But the tooltip says it is "10.1016/j.ebiom.2017.09031"

Note how the tooltip is missing a period in the DOI. The same appears to be true for all broken DOI links.

This bug used to not be there, so it must have been introduced at some point. I have the latest plugin version.

**Comment by metallikat36** [comment]
This bug may have a relation to a previous unsolved bug:
https://github.com/dsifford/academic-bloggers-toolkit/issues/368

I notice that on this same antidepressant article on my site, my reference list collapses permanently if i try to edit some of the references. But the only time this happens seems to be on references on that yield a broken DOI link in the tooltip.

**Comment by metallikat36** [comment]
Well, since all DOI links are presently broken, I should rephrase the above comment to say that the bug only happens on DOI links. Broken or not may not be relevant. I will update the other bug with this comment.

**Comment by dsifford** [comment]
Confirmed.

Note to self: Reproducible with (at least) this doi: `10.1097/TA.0000000000001333`

**Comment by dsifford** [comment]
Fixed in 4.13.3.
