### ISSUE TITLE
Javascript error - Failed to execute 'setItem' on 'Storage' when editing

### ISSUE THREAD

**Issue by paulber33** [dsifford/academic-bloggers-toolkit#430]
**ABT Version:**  4.13.3

**PHP Version:** 
Not sure

**Theme:**
Custom theme.

**Plugin List:**
ABT 4.13.3
Advanced Custom Fields
Advanced Custom Fields PRO
Advanced iFrame Pro
Autoptimize
Black Studio TinyMCE Widget
Blubrry PowerPress
CoSchedule
Custom Post Templates
ExportFeed - Create Product Feeds For 40+ Merchants
External Header Footer
Facebook Open Graph, Google+ and Twitter Card Tags
Facebook Post Embed
Force Regenerate Thumbnails
Instagram Feed Pro Personal
Klaviyo
Klaviyo for WooCommerce
PixelYourSite PRO
Post Types Order
Postman SMTP
Pretty Links
Product Catalog Feed Pro by PixelYourSite

-**Browser:** 
Google Chrome | 63.0.3239.132 (Official Build) (64-bit) (cohort: Stable)

**Expected behavior:**
I exepected the reference list to load when editing post/product

**Actual behavior:**

Reference list keeps loader icon keeps spinning and nothing happens.

**Console messages:**
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'abt-locale-cache' exceeded the quota.
    at Worker.receiveMessage (https://***.com/wp-content/plugins/academic-bloggers-toolkit/js/reference-list.js?ver=4.13.3:1:747981)

I'd appreciate it if you can take a look and tell me what I'm doing wrong. Thanks.

**Comment by glorious1** [comment]
I don't know if this is it, but when editing you need to be in the Visual editor for it to work.  ABT spins in the Text editor.

**Comment by dsifford** [comment]
Sorry, forgot to respond to this..

There's a technical reason for this that forces me to do it this way that I don't really care to get into, but what is going on right now is that the plugin downloads and caches locale files for citations into your browser's localstorage. Some browsers (esp safari) have notoriously low amounts of available space for caching. 

Yours appears to be one of those browsers. 

I'll look into a better fix for this when I get some free time.

**Comment by hamalrad** [comment]
I'm having this issue with the new editor on Wordpress 5, with the new sidebar. The plugin doesn't load, just gets stuck with the"loading" circle rotating indefinitely

**Comment by dsifford** [comment]
Update for WP 5.0 isn't quite ready... Should be ready soon though. Sit tight.

**Comment by dsifford** [comment]
Done.
