### ISSUE TITLE
Unable to add references - DOMDocument::loadHTML(): Empty string supplied as input in endpoints.php on line 19

### ISSUE THREAD

**Issue by saafbaat** [dsifford/academic-bloggers-toolkit#436]
Version 4.13.3

7.1.17

Dynamic News Lite

**Plugin List:**
academic-bloggers-toolkit/
advanced-custom-fields/
akismet/
broken-link-checker/
bwp-minify/
child-theme-configurator/
co-authors-plus/
configurable-tag-cloud-widget/
content-views-query-and-display-post-page/
duplicate-post/
easy-table/
facebook-page-feed-graph-api/
google-analytics-dashboard-for-wp/
inline-footnotes/
jetpack/
kk-star-ratings/
lingotek-translation/
newsletter/
nginx-helper/
photo-gallery/
polylang/
reading-time-wp/
save-import-image-from-url/
select-to-share/
ssl-insecure-content-fixer/
super-socializer/
table-of-contents-plus/
ultimate-social-media-icons/
wordpress-flash-uploader/
wordpress-importer/
wordpress-seo/
wp-conditional-captcha/
wpide/
wp-super-cache/

**Browser:** Google Chrome (Version: xxx)

1. This was working perfectly earlier, expect to be able to add new references

2. Now, I am unable to save any new references in posts. 
3. I see this error on my webserver logs

2018/02/23 23:06:33 [error] 7761#7761: *370085 FastCGI sent in stderr: "PHP message: PHP Warning:  DOMDocument::loadHTML(): Empty string supplied as input in ~/public_html/wp-content/plugins/academic-bloggers-toolkit/php/endpoints.php on line 19" while reading response header from upstream, client: 86.8.67.152, server: localhost, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", referrer: "...wp-admin/post.php?post=3596&action=edit"

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Is this still giving your problems @saafbaat? 

If so, any idea how I can reproduce this? Were you trying to cite a website?
