### ISSUE TITLE
Create URL for DOI in imported RIS

### ISSUE THREAD

**Issue by someonehere15** [dsifford/academic-bloggers-toolkit#44]
Just noticed that if I import a RIS with a DOI number, but no separate URL field, the doi just appears as text. I know it is not a bug, but it would be better and much more practical if the doi is automatically linked to the resolver, especially as I said, when the imported RIS has no URL but just a DOI number.

Just an additional question: Since from what I saw, you just generate the formatting and place it in the post, how do you recognize the list again if the post is opened in edit mode again? do you parse the text again to show the list on the widget, or something else? just curious.

**Comment by dsifford** [comment]
I'll look into having the DOIs from RIS linked. 

To answer your question (I think)... On load, the plugin traverses the entire post editor and looks for 2 things:

1. It looks for `<span>` attributes with the class `abt_cite` and it pulls the `data-reflist` attribute and stores it as an array (in local memory).
2. It looks for an `<ol>` with the ID `abt-smart-bib` and when it finds it, it takes each list item and copies it to the reference list.

Is that what you were asking?

**Comment by someonehere15** [comment]
Yes, thats what I was asking, just curious. Thanks. 

PS. If you do add the linked DOI option, don't forget also for manually entered references, so if I enter a reference manually and add a DOI in the respective field, that may also be linked.

**Comment by dsifford** [comment]
@someonehere15 Already done 😄 

I'm working on adding optional toggleable reference lists and peer review sections (see #16 ) and then I'll get the update pushed out

**Comment by dsifford** [comment]
Resolved: 8733a491004f72a3ce66dc2f2d01cbce52907381
