### ISSUE TITLE
Reference list not loading

### ISSUE THREAD

**Issue by helen-oneill** [dsifford/academic-bloggers-toolkit#440]
Hi dsifford,

I hope you are able to help me with my issue regarding ABT. I have filled out the required details to the best of my knowledge:

I have tried disabling all other plugins and have cleared cache on both WordPress and Chrome

-- Which version of ABT are you currently using? --
Version 4.13.3

-- Which version of PHP are you using with your WordPress installation? --
errm?

-- Which theme are you currently using? --
Maisha

-- List all activated plugins --
Academic  blogger toolkit
Akismet Anti-spam
Anariel Design Google Font   Picker
bbPress
Black studio Tiny MCE widget
BuddyPress
Collapse-Pro-matic
Contact Form 7
Duplicate page
Easy Google Fonts
Easy Siderbar Menu Widget
Elementor
Enhanced media library Pro
Envira gallery
Envira gallery - Albums addon
Envira gallery Breadcrumbs   addon
Envira gallery -Fullscreen   addon
Envira gallery- Tags addon
Envira gallery-Gallery themes   addon
f(x) Photo tag
Force login
Give - Donation plugin
H5P
H5P Mods
Header and footer scripts
Jetpack by WordPress.com
Menu Image
One Click Demo Import
Popup by supsystic
Post Grid
Search & Replace
Soliloquy
Tabby Responsive Tabs
The Events Calendar
Unique Headers
Widget Visibility
WP Super Cache
WPML Media
WPML multilingual CMS
WPML String Translation
WPML Translation Management

-- Browser:-- 
Google Chrome (Version: 64.0.3282.186 (Official Build) (64-bit) (cohort: Stable))

-- What did you expect to happen? --
ABT reference list to load and have beautiful references.

-- What actually happened? --
ABT reference list does not load. I initially installed it some months back, this happened then too but I got distracted with other work and didn't follow the problem up. I came back to ABT several weeks ago and reinstalled it, it worked for a little then - I managed to add two references which still work great, however when I try to add more references  in the editor the reference list is going back to not loading, just going round and round...

-- Open your javascript console on the affected pages by pressing F12 and paste any errors/messages below --
I don't see any error messages but could be looking in the wrong place.

Many thanks,
Helen

**Comment by dsifford** [comment]
Hi Helen,

My hunch is that you are currently using an outdated and no longer supported version of PHP. This has important implications beyond just being able to use this plugin; the most important of which is that deprecated PHP versions are extremely insecure and unsafe. Also, newer versions of PHP are up to 3 times faster than older versions.

My suggestion to you would be to contact your hosting provider and let them know you'd like to update your server to the latest version of PHP and they should be able to do that for you in a matter of minutes.

Once you've done that, if your issue still persists, please reopen this thread and we can investigate further.

**Comment by helen-oneill** [comment]
Hi dsifford,

I have done as you suggested and contacted my hosting provider, they got back to me saying that "...the only PHP versions we support are php 5.6 and php 7.0"  Would that explain why I was able to use it that one time? and that the references I did import and still functioning perfectly?

I'd really like to be using ABT,

Cheers for the help,
Helen

**Comment by dsifford** [comment]
What version of PHP is your site currently running? 5.6 is still supported so if you have PHP version 5.6 and up, it _should_ work properly.

Let me know.

Thanks

**Comment by dsifford** [comment]
And the issue is persisting, I assume?

If so, what about when you open a brand new post? Does it load then? In other words, is this issue specifically affecting exiting historic posts?

**Comment by dsifford** [comment]
It sounds like you might have a plugin compatibility issue. 

Can you try disabling your other plugins temporarily and see if the issue resolves?

**Comment by helen-oneill** [comment]
Hi,
I have disabled all plugins except ABT and there is still no change.

**Comment by dsifford** [comment]
Hm.... Hard to say what could be causing it. 

Can you take a screen recording of what's happening and share? Or, if you can, make me a temporary login with at least editor access permissions so I can take a look when I get some free time?

**Comment by helen-oneill** [comment]
I’ll happily provide you with log in credentials. How do I send them to you privately?

Cheers,

**Comment by dsifford** [comment]
dereksifford@gmail.com

**Comment by hsolsc** [comment]
Hi disfford. 
I have a very similar problem. Did you find a solution?
Thanks
Hans

**Comment by dsifford** [comment]
I don't recall what ended up happening here, but regardless of that, I'm working on an update now that supports the new block editor. If you can hold out for that, the plugin should work a bit more smoothly.

That said, I plan on sunsetting support for the old editor so if you plan on using the `classic editor` plugin, it should work for a bit longer but I won't be pushing any updates for it.

**Comment by hsolsc** [comment]
Hi Derek.

Thanks for you answering so quickly. I read your response and put that
article on hold. Just checking in, when do you expect to release this
functionality?

Thanks
Hans

**Comment by dsifford** [comment]
Crossing my fingers and _reaaaaaaaaaaally reaaaaaaaaaally_ shooting to have this done and released this weekend. Stay tuned.
