### ISSUE TITLE
Impossible to insert a reference

### ISSUE THREAD

**Issue by JJslab** [dsifford/academic-bloggers-toolkit#447]
**ABT Version: ??

**PHP Version: 7.0.27

**Theme: KALE

**Plugin List:**
- Plugin 1
- Plugin 2

**Expected behavior: adding a reference as I used to do

**Actual behavior: Impossible to add a reference

**Console messages: 
```js
// Paste messages here : TypeError: undefined is not an object (evaluating 'this.registry.citationreg.citationById[i[0]].properties') 


Thanks a lot for your help !

**Comment by dsifford** [comment]
@JJslab Can you add a bit more information to your issue?

As it stands, I'm not even sure where to begin helping with this since what you have is quite vague.

What web browser (including version) are you using?

Were you ever able to insert references? Does this happen only on a specific page? etc.

Thanks

**Comment by JJslab** [comment]
Hello, 

Many thanks for your response and so sorry for the lack of informations. 

I am using safari 11.0.3. I was able to insert references for quite some times and it suddenly stopped working about 3/4 weeks ago. I have tried to reinstall the extension, to deactivate all my others extensions, to install a new theme but still not working. 

I also get an error message when I add a reference (TypeError: undefined is not an object (evaluating 'this.registry.citationreg.citationById[i[0]].properties')) but strangely when I do it works anyway.
So the problem only occurs when I select a reference and click on the "insertion" button (with an arrow pointing to the left).

Thanks a lot in advance for your help and let me know if you need any additional informations.

Best regards from Belgium

Dounia

**Comment by JJslab** [comment]
Don't know if you've done something but it's working ! Thanks !
Dounia
