### ISSUE TITLE
Reference List doesn't load 

### ISSUE THREAD

**Issue by viveknallur** [dsifford/academic-bloggers-toolkit#448]
**ABT Version:** 4.13.3

**PHP Version:** 7.1.15

**Theme:** Twenty Seventeen 

**Plugin List:**
-ABT

**Browser:** Mozilla Firefox (Version: 58.0.2)

**Expected behavior:** Reference List plugin should activate as shown in Image 1 in the Visual Aids section on: https://github.com/dsifford/academic-bloggers-toolkit/wiki#adding-references-using-ris-file

**Actual behavior:**
![reference-list-not-working](https://user-images.githubusercontent.com/163498/37568917-a2d24508-2ad3-11e8-952a-28ab7644344e.png)

The plugin never actually activates

**Console messages:**
```js
Nothing reported at log levels: Warning and Errors
At log level Info: JQMIGRATE: Migrate is installed, version 1.4.1
```

**Comment by dsifford** [comment]
In order for the list to load, you need to have the visual editor enabled and have the visual editor tab active.

**Comment by viveknallur** [comment]
Mea Culpa :-(. Many thanks!
