### ISSUE TITLE
Bad DOI reference insertion

### ISSUE THREAD

**Issue by krmaxson** [dsifford/academic-bloggers-toolkit#450]
**ABT Version:** 4.13.3

**PHP Version:** 7.2.1

**Theme:** Customizr Pro

**Plugin List:**
- ManageWP
- Wordfence Security

**Browser:** Google Chrome (Version: 65.0.3325.162 (64-bit))

**Expected behavior:** Insert properly styled reference using DOI number.

**Actual behavior:** Inserted a reference displaying badly-formed extra target and rel tags in output. Inserted HTML follows:

<code>
<div class="csl-entry">4. Kizer KW. Sharks &amp; Rays—Elasmobranch Guide of the World. W 2003;14:64–64. Available at: <a href="http://dx.doi.org/&lt;a href=" target="_blank" rel="noopener noreferrer">10.1580/1080-6032(2003)014[0064:BR]2.0.CO"</a> target="_blank" rel="noopener noreferrer"&gt;http://dx.doi.org/<a href="https://doi.org/10.1580/1080-6032(2003)014[0064:BR]2.0.CO&lt;/a&gt;;2" target="_blank" rel="noopener noreferrer">10.1580/1080-6032(2003)014[0064:BR]2.0.CO</a>;2.</div>
</code>

This is from inserting this DOI: 10.1580/1080-6032(2003)014[0064:BR]2.0.CO;2

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Strange that the DOI issuer allowed the brackets and colon to be used inside the DOI since those are, according to the DOI specification, explicitly not allowed.

Good catch nevertheless!

I'll adjust for those as soon as time allows. :+1:

**Comment by krmaxson** [comment]
Thanks so much for the quick response! I hadn't realized they were violating their own spec.

**Comment by dsifford** [comment]
Fixed.
