### ISSUE TITLE
references/citations inside widgets?

### ISSUE THREAD

**Issue by oneoftwo** [dsifford/academic-bloggers-toolkit#452]
I'm unsure whether this is an issue with my installation, or whether this is simply not possible:

I wanted to add a reference list inside a widget block (for the purposes of this discussion, a simple Wordpress Text widget). However, I don't see the ABT interface anywhere in this case.

ABT works fine on straight-up pages or posts.

Thanks,
Thomas W

(If it's just my installation, I'll add the requested additional info)

**Comment by dsifford** [comment]
Hi there,

Good question. Unfortunately, for technical reasons, this isn't possible.

The only way you might be able to circumvent this is to add a static publication list in an empty post and then just copy and paste the HTML content from that post the the widget.

Not ideal, but the only option at this point.
