### ISSUE TITLE
Unexpected error and no DOIs accepted

### ISSUE THREAD

**Issue by cwbullet** [dsifford/academic-bloggers-toolkit#454]
**ABT Version:4.13.3

**PHP Version:5.64

**Theme: mh-newsdesk

**Plugin List:**
- Only ABT

**Browser:** Google Chrome (Version: xxx)
Safari 11.03

**Expected behavior:**
When I add PMID: 24552677, it gives me an unexpected error.  If I try any DIO, it gives me an unexpected error.  That is the PMID that fails to work, but all DOIs fail to work.  They may be unrelated errors.  

**Actual behavior:**
Error

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Sorry for the huuuuge delay here. Is this still giving you issues? Just tried PMID `24552677` with no issues here.
