### ISSUE TITLE
Can't Add NEJM.org Opinion Articles with DOI

### ISSUE THREAD

**Issue by cowboytrix** [dsifford/academic-bloggers-toolkit#458]
**ABT Version:** 

**PHP Version:** 

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**

Hi there. Great Wordpress tool! 

Here's the problem:
Can't add either of these references for the SAME PAPER:
PMID: 27626516 DOI: 10.1056/NEJMp1606869

Thanks!

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Thanks for the report. 

I'm not able to reproduce this. Both the PMID and the DOI work for me.

Does this happen on new posts for you as well, or just existing posts?
