### ISSUE TITLE
Autocite URL does not work

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#459]
https://youtu.be/_FaREybz3Xs

See video. Manually typing in a URL works fine. But if you try to use the autocite tool, it does not work. Clicking "Add Reference" just does nothing and the window does not close.

**Comment by dsifford** [comment]
Can you copy over the error logs from the developer tools console?

Thanks

**Comment by metallikat36** [comment]
Ah, it is because the date field is empty:
![image](https://user-images.githubusercontent.com/17968340/39155078-71c20216-4705-11e8-9b5c-157dd4efa208.png)
Just need to add a tooltip warning the user the date field needs to be filled out.

**Comment by dsifford** [comment]
Good to know. 

I think I recently laxed the form requirements for dates and I must have missed handling situations where dates were not entered.
