### ISSUE TITLE
CLS editor inline citations, Italics in title

### ISSUE THREAD

**Issue by helen-oneill** [dsifford/academic-bloggers-toolkit#460]
Hi, 
I'm hoping you are able to help with some things I am currently struggling with.

1. How do I change inline citations from author & date e.g. (Smith, 2000; Bloggs, 2015) to superscript numbers e.g. 1,2?

I am trying to edit American Psychological Association 6th edition, as that is the closest match to the referencing style I want, however I want numbered inline citations. I have viewed the User guide for the CSL Editor and can change some elements of the referencing style but not this.

2. How do I allow italics in the article title within the bibliography?

Some titles have scientific names in e.g. 
Ramón, D., & Bailey, K. (1996). Spawning seasonality of albacore, _Thunnus alalunga_, in the South Pacific Ocean. _Fishery Bulletin_, 94(4), 724–733.

Where _Thunnus alalunga_ needs to be italicized. 

Thanks,
Helen

**Comment by dsifford** [comment]
Hi Helen,

The first suggestion I will make is that you should try to avoid creating your own citation style at all costs. There are around 4500 individual styles available so, almost surely, there will be one that satisfies your constraints.

Going off of what you're describing, have you tried "American Medical Association"? That style uses superscript numbers and is very similar to APA.

To touch on your second question: If you're adding your citation manually using the manual input form, there is currently no way to include text formatting. So if you need this sort of thing, try to use a DOI if possible.

Hope that answers your questions.

**Comment by helen-oneill** [comment]
Hi Derek thanks for your reply.

I have taken your advice to avoid creating my own citation style, and have found something quite close to what I am looking for, so thanks for that.

I added references by both importing from Endnote, adding manually using the DOI search, and manually through the input form. I can't see that any of these methods worked to allow formatting (italics) within the reference. 
Would you be able to offer any more advice/solution on this issue?

Many thanks,
Helen

**Comment by dsifford** [comment]
Can you provide an example of what you're trying to accomplish? (you can paste screenshots directly into this thread).

Italics are definitely supported if the particular citation style has them defined.

**Comment by helen-oneill** [comment]
Hi Derek,

Through using ABT, the italicised scientific names (in this case: Acanthocybium solandri) is lost. The process I was doing was to import references from Scholar to Endnote, then import from Endnote in to ABT. I did have to edit some of the scientific names and change them to italics when in Endote, but they come out into Word OK (see later).
The references in the below example have been imported from Endnote, but I have tried different ways and it doesn’t seem to make a difference how they are inserted/imported, that I can see anyway

A screen shot of my site:
[cid:image001.jpg@01D3E6D6.49EA2D70]

I tested it on word to see if the issue was stemming from Endnote, as Acanthocybium solandri in the ‘Title’ (blue highlight) is NOT in italics. Lower down however in the reference breakdown in “Title:” Acanthocybium solandri IS in italics.
Endnote capture:

[cid:image004.png@01D3E6D4.1B782430]

And when this reference is inserted into Word the italics for Acanthocybium solandri works:
Word:
[cid:image005.png@01D3E6D4.1B782430]


This may be irrelevant, but I have noticed that scientific names in references on google scholar appear without formatting also -
When citing the same ‘Jenkins and McBride’ reference:
Scholar:

[cid:image002.jpg@01D3E6D6.49EA2D70]


Apologies for the longwinded-ness of this, I hope I have explained it enough and it’s mostly relevant. It’s hard to explain as I don’t know the backend workings to really understand what’s going on. If this is a new issue I am surprised, italicised scientific names are common practise in biological science.

Thanks for your help,
Helen

**Comment by fbennett** [comment]
@helen-oneill You should be able to edit the RIS exported from EndNote to add formatting tags. The citation formatter recognizes a [tiny subset of HTML markup](http://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#html-like-formatting-tags).

**Comment by helen-oneill** [comment]
@fbennett 
Hi,
Thanks for the email - it worked!!

The steps I took were: 
1. Open the RIS file in Notepad
2. Add the formatting tags
3. Save as RIS
4. Imported the reference list into ABT 
5. Inserted the reference within the text,
and got this -
![image](https://user-images.githubusercontent.com/37096834/39741640-079d361e-52de-11e8-88d7-960ea4e94ccb.png)

Do these sound like the correct steps to you? I would just like to confirm that this is the appropriate way to achieve the desired outcome - I'm a beginner and have had some previous bad experience with doing things wrong!

Many thanks,
Helen
