### ISSUE TITLE
TypeError: this.registry.citationreg.citationById[i[0]] is undefined

### ISSUE THREAD

**Issue by audioscavenger** [dsifford/academic-bloggers-toolkit#463]
**ABT Version:** latest 4.13.3

**PHP Version:** 7.0.2

**Theme:** devdmbootstrap3

**Plugin List:**
- Academic Blogger's Toolkit
- AJAX Thumbnail Rebuild
- Akismet Anti-Spam
- All In One WP Security
- Autoptimize
- Better Section Navigation
- Blog2Social: Social Media Auto Post & Scheduler
- Bootstrap 3 Shortcodes
- BU Navigation
- Category Order and Taxonomy Terms Order
- Child Theme Configurator
- Cloudflare
- Code Snippets
- Duplicate Post
- Duplicator
- Easy Table of Contents
- Embed Any Document
- Enlighter - Customizable Syntax Highlighter
- HTML Editor Syntax Highlighter
- Mammoth .docx converter
- Native Emoji
- Nginx Helper
- Nice Likes
- Post Updated Date
- Sassy Social Share
- Server IP & Memory Usage Display
- Simple Custom CSS and JS
- Simple Tags
- TinyMCE Advanced
- Widget Context
- WordPress Related Posts Thumbnails
- WordPress Twitter Bootstrap CSS
- WP cdnjs reborn
- WP OPcache
- WP Statistics
- WP Word Count
- WP-Optimize
- WP-PageNavi
- Yoast SEO

**Browser:** Firefox (Version: 59.0.2)

**Expected behavior:** Add reference, add manually, (Chicago selected), citation added next to the cursor position

**Actual behavior:** popup window from plugin with "An unexpected error occurred"
```TypeError: this.registry.citationreg.citationById[i[0]] is undefined```

**Console messages:** none

**WP/PHP debug messages:** none

**Comment by audioscavenger** [comment]
I modified the js with JSprettifier and added some console.log() here and there.
The problem starts at line 26712 where the code returns an undefined element:
```return this.registry.citationreg.citationById[t.citationID] = t,r```

console.log('26731 t.citationID '+t.citationID);
```26731 t.citationID 0xPmDdUTRxhf9OtwElFA3```

console.log(t);
```
reference-list.js:38610:16
{…}
  ​citationID: "0xPmDdUTRxhf9OtwElFA3"
  ​citationItems: […]
    ​​0: {…}
      ​​​id: "2414816960"
      ​​​item: {…}
        ​​​​URL: "df"
        ​​​​author: […]
          ​​​​​0: Object { given: "df", family: "df", literal: "" }
          ​​​​​length: 1
          ​​​​​__proto__: Array []
          ​​​​"container-title": "df"
          ​​​​"container-title-short": undefined
          ​​​​id: "2414816960"
          ​​​​title: "df"
          ​​​​"title-short": undefined
          ​​​​type: "webpage"
        ​​​​__proto__: Object { … }
      __proto__: Object { … }
      ​​length: 1
    ​​__proto__: Array []
  ​sortedItems: Array [ […] ]
  ​__proto__: Object { … }```

- r value is false
- this.registry.citationreg.citationById[t.citationID] is undefined

does that help?

**Comment by audioscavenger** [comment]
hmmmm let's be honnest. Everything was working fine one month ago. I haven't touched anything for a month and WP is up to date.
Yesterday when I reconnected, I allowed 15 plugins to update, including yours.

The problem appeared after I copied and pasted a page content to a new blank post (I don't know how to convert a page to a post, sorry).
I also realized the "preview" for _unpublished_ posts do not work anymore. 
Now, preview works for _published_ pages and posts, and draft pages, but not for draft posts: I get a blank page which height is related to the post size but the footer fill the page all the way up. Seems related to the theme as well, which I didn't update though.

I couldn't reproduce the problem with a blank post/page, but I can when I copy and paste a post/page content _that contains references_ to a new one. Then the issue appears. 

## So, you have no problem, Sir.
Just inform your users they cannot **copy and paste content with references** to a new blank post/page as it will break the plugin for that new post. Deleting all the references manually in the content is not sufficient, as there must be some hidden leftovers somewhere.
You can duplicate a post/page with references (with duplicator plugin) and it will work just fine. To copy and paste content with references, you must paste it to a temporary media such as Winword and then copy from it, so the hidden reference links will not be included.

I still don't know what to do with my preview issue for new posts :'(

**Comment by dsifford** [comment]
> The problem appeared after I copied and pasted a page content to a new blank post (I don't know how to convert a page to a post, sorry).

Yes, this isn't supported for various technical reasons. The way that I'm able to keep the plugin "aware" of citation positions and overall document state is by keeping a pretty detailed log of  metadata attached to the post itself as you're writing it. 

If you copy content from one post to another, the metadata from that post is lost. So, in effect, the plugin on the new page becomes completely unaware of the citations existing in the document.

> Now, preview works for published pages and posts, and draft pages, but not for draft posts: I get a blank page which height is related to the post size but the footer fill the page all the way up. Seems related to the theme as well, which I didn't update though.

This definitely sounds like a theme issue. Preview should definitely still work for this plugin.

> Just inform your users they cannot **copy and paste content with references** to a new blank post/page as it will break the plugin for that new post.

I make mention of this in the [wiki](https://github.com/dsifford/academic-bloggers-toolkit/wiki#changing-citation-number-or-position)

> To copy and paste content with references, you must paste it to a temporary media such as Winword and then copy from it, so the hidden reference links will not be included.

If you open the menu in the reference list, there's a "destroy all references" button that will wipe your content clean of any html and citations which should make it easier to copy content to some place else.


Sorry for the trouble!

**Comment by audioscavenger** [comment]
I didn't RTFM. thanks for pointing that out ;)
