### ISSUE TITLE
Error on not updating reference list

### ISSUE THREAD

**Issue by helen-oneill** [dsifford/academic-bloggers-toolkit#465]
Hi,

I am getting this error:

An unexpected error occurred

TypeError: Cannot read property 'properties' of undefined

Please report this error, including the steps taken to trigger it, here: 
https://github.com/dsifford/academic-bloggers-toolkit/issues

I think It's because I am using one large reference list for multiple pages, updating it then trying to continue using it and insert a reference on those pages without updating/importing the new list. (now I read that it sounds rather dumb, but I'm still getting my head around this).

I have many references but spread over many pages, say an average of 4 a page with currently around 50 pages. For wordPress is it best to have one reference list per page?

Cheers for the help,

Helen

**Comment by dsifford** [comment]
Sorry to hear you're having trouble!

> I think It's because I am using one large reference list for multiple pages, updating it then trying to continue using it and insert a reference on those pages without updating/importing the new list.

Yes, this sounds like it could be the culpret.

> I have many references but spread over many pages, say an average of 4 a page with currently around 50 pages. For wordPress is it best to have one reference list per page?

Yes, you should have one reference list per post.

If you have a reference being used in more than one post, you should add that reference individually into each post.

----

It sounds to me like you're trying to both cite and _manage_ your references within WordPress. I'd strongly urge against that. 

I'd instead recommend using Zotero, Mendeley, Endnote, Readcube, etc, etc for managing your references. Within those apps, you can group and export subsets of references into RIS format that you can then import into the plugin in WordPress. That's the ideal scenario.

**Comment by dsifford** [comment]
Closing this since it's pretty old and I haven't heard back.

**Comment by helen-oneill** [comment]
Hi,
Not sure you will receive this now it is closed, however I apologise for forgoting to respond. I have always been using Endnote, but I see now that my folders weren't fine scale enough, I had to divide my subfolders in to sub-subfolders if that makes sense! all working well now though. 
Many thanks,
Helen
