### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by sprungmarker** [dsifford/academic-bloggers-toolkit#467]
**ABT Version:** 4.13.3
**PHP Version:** 7.2.1 
**Theme:** Twenty Seventeen
**Browser:** Mac Firefox 60.01

**Expected behavior:** usable with keyboard und Screenreader

**Actual behavior:**

- Tooltip and close button is not usable with keyboard and screenreader
- Footnotes and reference list are not semantic - should be html list (ul or ol), no heading

**Comment by dsifford** [comment]
Nice catch! I spent quite a bit of time making the backend accessible, but I clearly overlooked the most important part.

PRs accepted.

**Comment by sprungmarker** [comment]
thx :)

**Comment by dsifford** [comment]
Both of these issues will be resolved on the next update.

**Comment by dsifford** [comment]
Done
