### ISSUE TITLE
Styling Static publication lists

### ISSUE THREAD

**Issue by josinc** [dsifford/academic-bloggers-toolkit#470]
**ABT Version:** 4.13.3

**PHP Version:** 5.4.45

**Theme:** Newspaper

I have added Custom CSS for the styling of Reference list in the 'Override CSS' panel of ABT Settings page. But it doesn't seem to affect the static publication lists added to pages. How can Static publication lists be formatted in the same manner?

-Josin

```

**Comment by dsifford** [comment]
I'm not sure without being able to see exactly what you're trying to do. 

Maybe try putting your css overrides in your theme or child theme's stylesheet, rather than using the override box?

**Comment by josinc** [comment]
Please find following two links. Go to the bottom of the page where you can find referenced added using ABT. One is Static publication list and other is normal reference list.

[Link-1 Page with Static publication list](https://amazingzoology.com/this-ancient-bird-hatchling-preserved-in-amber-provides-insights-into-early-bird-evolution/)
[Link-2 Page with Normal reference list](https://amazingzoology.com/makes-poison-dart-frog-resistant-poison/)

Following is the custom CSS used. This code is applied in Link-2 but not applied in Link-1.
`.abt-bibliography {
	font-size: 12px;
}`

**Comment by dsifford** [comment]
Ah, I see.. 

Yeah, link 1 uses a different selector: `.abt-static-bib`, rather than `.abt-bibliography`.

So changing your css to the following should resolve your issue:

 ```css
.abt-bibliography,
.abt-static-bib {
    font-size: 12px;
} 
```

Hope that helps.
