### ISSUE TITLE
DOI causes error

### ISSUE THREAD

**Issue by weings01** [dsifford/academic-bloggers-toolkit#472]
**ABT Version:** 
4.13.3

**PHP Version:** 
7.1

**Theme:**
genesis magazine pro

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**
added DOI 10.1053/j.jvca.2017.08.049 and got an error message

**Actual behavior:**

**Console messages:**
```js
// Paste messages here
we are loving the plugin on the emcrit site, brother!

**Comment by dsifford** [comment]
Sorry for the huuuuge delay here. 

Just tried this and it appears to work for me. 

(Support for the new editor coming down the pike shortly).
