### ISSUE TITLE
Exceeding 128M POST request limit with 70 references

### ISSUE THREAD

**Issue by CoryTrevor** [dsifford/academic-bloggers-toolkit#474]
Hi

This plugin is so awesome, thanks for developing it. It makes it so easy to write properly referenced articles in WP.

I've got a page that's up to 70 references (and will eventually have around 90) but it's now exceeding the post request size limit on the server when I save it. If I go back and remove a few references then it will save properly, but then if I add a few more and try and save it will exceed the limit and come up with the error.

According to phpinfo, post_max_size = 128M on the server. 128Mb seems quite high so was just wondering if that sounds about right for a 70 reference post or is it likely that something is else going on?

Thanks

ABT version: 4.13.3

PHP version: 7.1.18

Theme: Divi

Plugins: Only using Academic Bloggers Toolkit

Browser: Chrome 67.0.3396.99

Expected behaviour: Save post

Actual behaviour:
Request Entity Too Large
The requested resource
/wp-admin/post.php
does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

**Comment by dsifford** [comment]
That is correct. 

The reference engine required to parse out citations unfortunately requires a relatively complex and large set of metadata to be maintained behind the scenes. This metadata is stored as json-formatted plain text in each post's postmeta database table and, as you've already discovered, this large chunk of data needs is POSTed when you load the editor page.

Nothing I can do about this in the short term. Increasing your `post_max_size` should fix this though.

**Comment by CoryTrevor** [comment]
Hi Derek

Thanks for getting back to me and clarifying that.

I've now located the reference metadata for the page in the _abt-reflist-state
row in the postmeta table and I see what you mean about it being a lot of
data, but if I copy and paste it all into a text document it only comes to
585kb. So in theory even if there were 100 references it shouldn't be any
more than 1mb of reference metadata being posted.

So if the post_max_size on the server is 128mb like it says it is then it
shouldn't even be using 1% of that to post all the reference data for a 70
reference post. So I suspect there's something else limiting the maximum
post size on the server so I'll follow up with them.

Cheers

**Comment by dsifford** [comment]
The post data size for each page load is the combination of every piece of data being loaded on the page, not just the abt-reflist-state row.

**Comment by CoryTrevor** [comment]
Yeah that's true, so the total size would be a bit larger than that.

My host was able to tweak some Apache settings and now it's working great
with more than 70 references. In case anyone else runs into this issue, it
wasn't post_max_size that was the problem, it was these Apache directives
that needed the limits increased:

SecRequestBodyLimit
SecRequestBodyNoFilesLimit
SubstituteMaxLineLength

Cheers
