### ISSUE TITLE
aligning problem

### ISSUE THREAD

**Issue by zezoalbayari** [dsifford/academic-bloggers-toolkit#477]
Hi 
thanks for such great plug-in , hope you'll keep updating it . 
I'm having an issue aligning the numbers to left in bibliography. as my website theme writting style is right to left (Arabic language) but All the citation are in English , I tried to play with overriding CSS but I only manged to align the text left .
 any help ?

**Comment by dsifford** [comment]
Hi @zezoalbayari 

Sorry for the trouble. I plan on digging in and updating the plugin for the new gutenberg editor soon (when the API stabilizes).

I'll take a look at better RTL support when that happens.

**Comment by dsifford** [comment]
See #271, #378, #474 for details on how to mitigate your issue.

**Comment by zezoalbayari** [comment]
Me and my hosting support team , have been trying the during the previous days to get things working , but it doesn't work. there last reply was to ask you if you can provide exact instructions on the issue.
another question, does this problem will be solved with the update you'll release with gutenberg (since gutenberg works as blocks so probably not the same one Post-Http request ?.

this is their last reply "
I have added the recommended directives in the public_html/.htaccess file:
Code:
SubstituteMaxLineLength 10m
LimitRequestBody 10240000

Please test again and if the issue still persists, you should contact the developers of the plugin for further investigation of the issue. If we should modify system variables, please request from the developers the exact instructions to be provided so we can review them and implement the modifications is the server's environment allows that. "

**Comment by dsifford** [comment]
As far as I know, those additions should resolve the problem. You may need to flush out your cache for the changes to take effect.

Re: "will this issue still persist after gutenberg is supported" -- Yes. The same data will need to be saved as post meta regardless of the editor being used. This is a downstream problem with the citation processor at its core. Not something I can fix without doing a complete rewrite of the processor, unfortunately.

Still haven't been able to allocate time to work on this. Hopefully soon.

**Comment by dsifford** [comment]
@zezoalbayari Sorry for the huge delay in getting back to you... I'm working on the next plugin release and I just realized that you can fix this right now with just a small addition of CSS.

To force LTR directionality of your bibliographies, simply add the following to your site's CSS...

```css
.abt-bibliography {
  direction: ltr;
}
```

Sorry it took so long for me to realize this!
