### ISSUE TITLE
Issues deleting all references

### ISSUE THREAD

**Issue by helen-oneill** [dsifford/academic-bloggers-toolkit#484]
Hi,

I haven't encountered this issue before since using ABT - I am trying to delete an old reference list (consisting of 54 reference) which I imported a few months ago. To do this I select all 54 references click the hamburger, click delete and they disappear, great. I then import the new reference list (of 7) as I have done many times previously, insert them, and click update, but the old reference list keeps reappearing in its place. I have clicked 'update' at multiple stages throughout this process and it still doesn't seem to make a difference. 54 uncited references keep appearing in the new reference list's place and I cant get rid of them.

Any thoughts on what to do about this?

ABT Version 4.13.3 

Maisha theme

Using Chrome

Thanks for this plugin I think it's really great.

Helen

**Comment by helen-oneill** [comment]
Following on from that - when I view the page after inserting in 1 of the new 7 references it appears as it should. however when I go to edit the page it states 54 uncited items. Not sure what's going on.

Thanks

**Comment by dsifford** [comment]
Hi @helen-oneill,

Try instead clicking the hamburger, then clicking "destroy all references". That should resolve the issue.

**Comment by dsifford** [comment]
Haven't heard back. I'm going to assume that resolved your issue.

Let me know if not and I'll reopen the issue.

**Comment by helen-oneill** [comment]
Hi Derek,

Apologies I got side-tracked with other things.
I haven’t been able to  resolve the issue. I have tried selecting the hamburger, select ‘delete references’ (you used the term destroy - are we talking about the same thing?), I click ‘update’ and they all appear again.

Cheers,

Helen

P.S. I have a training workshop this week so again I may be slow to reply

**Comment by dsifford** [comment]
See here: https://github.com/dsifford/academic-bloggers-toolkit/wiki#removing-all-references

**Comment by helen-oneill** [comment]
Yes, that is exactly what I am doing. I have gone through the process of deleting an incorrect reference list and importing a new one at least 20 other times during the past few weeks without a problem. For some reason, on this particular page, after I delete all references and ‘update’, the old references reappear.

**Comment by dsifford** [comment]
Hm.. Hard to say for sure then what could be causing the issue. 

If you are able to make me an account on your site with at least editor permissions and let me know what page is affected, I can check it out when I get a moment to spare. 

email:  dereksifford@gmail.com
