### ISSUE TITLE
Allow plugin to work offline (stub rollbar error logger)

### ISSUE THREAD

**Issue by hamalrad** [dsifford/academic-bloggers-toolkit#493]
> An unexpected error occurred
> 
> TypeError: Cannot read property 'properties' of undefined

To reproduce:
1. Write an article, add some references.
2. Switch from visual editor to text editor
3. Select all the text, copy/cut
4. Select all the text again and paste
5. Go back to visual editor, try to add another refrence
6. ERROR

(Why am I even doing this?
During my train commute, my internet connection died, so I couldn't save a draft of everything I wrote... so I wanted a temporary backup of everything I had written until I could get back online....)

**ABT Version:** 4.13.3
**PHP Version:** 5.4.24
**Theme:** Hueman
**Plugin List:** (Problem presists after disabling all plugins)
**Browser:** Google Chrome (Version:  68.0.3440.118)
**Expected behavior:** Add New refrence
**Actual behavior:** Error
**Console messages:**
```js
Failed to load resource: the server responded with a status of 400 ()
https://api.rollbar.com/api/1/item/
```

**Comment by dsifford** [comment]
Fair point. I'll keep this in mind when I can finally find a moment to work on updating the plugin again, which will hopefully be soon(ish).
