### ISSUE TITLE
Reference List on Pages

### ISSUE THREAD

**Issue by someonehere15** [dsifford/academic-bloggers-toolkit#50]
I just noticed that the Reference List is not appearing when editing Pages, and it's not on the screen options. Is it just me? If not, can you enable it for pages at least.

BTW, great job on everything until now. It's a great plugin.

**Comment by dsifford** [comment]
Good catch! I'll work on getting this pushed out in the next patch update.

**Comment by someonehere15** [comment]
I just noticed that in the editor for Pages the icon appears twice, one of which is not functional, nothing happens. It does not happen for posts though.

**Comment by dsifford** [comment]
@someonehere15 Good catch.. I'll get a fix pushed out tomorrow sometime 👍
