### ISSUE TITLE
Plugin doesn't initialise if Post-body not visible 

### ISSUE THREAD

**Issue by songsta** [dsifford/academic-bloggers-toolkit#500]
**ABT Version:**  4.13.3

**PHP Version:** 7.2

**Theme:** Generate Press

**Plugin List:**
- Toolset

**Browser:** Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Expected behavior:** The spinner should stop spinning and the Reference List meta-box should show the icons. 

**Actual behavior:** The spinner keeps spinning.

**Console messages:**
```js
Uncaught Error: [mobx] An invariant failed, however the error is obfuscated because this is an production build.
    at Ne (mobx.umd.min.js?ver=4.2.0:2)
    at Ce (mobx.umd.min.js?ver=4.2.0:2)
    at mobx.umd.min.js?ver=4.2.0:3
post.php?post=101&action=edit:1 Uncaught (in promise) Error: TinyMCE editor doesn't appear to be available in this scope
    at tinymce.ts:232
api.rollbar.com/api/1/item/:1 Failed to load resource: the server responded with a status of 400 ()
post.php?post=101&action=edit:1 Mixed Content: The page at 'https://188.166.105.174/wp-admin/post.php?post=101&action=edit' was loaded over HTTPS, but requested an insecure script 'http://188.166.105.174/wp-content/plugins/organize-series/js/series.js?ver=2.5.11'. This request has been blocked; the content must be served over HTTPS.

```

I use Toolset to create custom post types for my site and I hide the post-body field for some of the custom post types as I don't use it and I don't want it to show for the user. However, it seems as if this plugin is looking for that field to be visible, as the spinner just keeps spinning when I'm editing one of these custom post types. If I'm editing a post type where the post-body is visible, the spinner stops spinning and the icons appear correctly.

**Comment by dsifford** [comment]
Yeah, this is by design. The (current) version of the plugin has a tight integration to the tinymce editor. As such, the reference list would go haywire if a user attempted to add a reference or modify references when tinymce is not available.

If you just would prefer to disable the reference list on posts that don't have an editor, you can check [here](https://github.com/dsifford/academic-bloggers-toolkit/wiki/Developer-Hooks) for hooks to do that.

**Comment by songsta** [comment]
Thanks for the response. Sorry I only saw it now. 

Perhaps a bit more detail that I didn't give in the first post - I'm adding custom fields that _do_ have the tinymce editor active. Toolset allows me to create custom WYSIWYG fields that use the editor. Would it be possible to allow references in these fields too?

**Comment by dsifford** [comment]
> I'm adding custom fields that _do_ have the tinymce editor active. Toolset allows me to create custom WYSIWYG fields that use the editor. Would it be possible to allow references in these fields too?

Unfortunately, no. For technical reasons, the reference list and a single editor must be coupled together tightly. Not possible to have multiple editors at this time.

This _might_ be possible when I support gutenberg. But no promises.

**Comment by songsta** [comment]
Ah ok. Thanks for the feedback.
