### ISSUE TITLE
Issue putting content below the references list

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#514]
Hi Derek,

Hope all is well. One small bug (or maybe it's a feature request). On pages, I am manually adding shortcode to the bottom of the page to load DISQUS comments on that page. I am able to do this below the references list and save the page with no problem. And in fact, it will work. Comments will appear below the references list at the the bottom of the page. The issue however is that in the Editor, with subsequent updates to the page, the references list is automatically put back at the bottom. Thus, unless I keep remembering to move the DISQUS shortcode below the references list, I will after 1 or 2 updates find that the comments are loading above the references list.

This is an issue that can be worked around, so no big deal. But it would be nice to have a permanent solution.

**Comment by dsifford** [comment]
Fixed.
