### ISSUE TITLE
Text and citations get relocated to below the references list.

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#517]
See this video for steps to reproduce.
https://www.youtube.com/watch?v=iXr2YOhZJRY&feature=youtu.be
The first 1:30 is documenting a probably unrelated bug which I have started another thread for already. The last 45 seconds illustrates the bug I am talking about.

Again, not a major issue as it can be worked around by just deleting and reinserting the buggy citations.

**Comment by dsifford** [comment]
Fixed.
