### ISSUE TITLE
Not working with Gutenberg Editor

### ISSUE THREAD

**Issue by gumush** [dsifford/academic-bloggers-toolkit#523]
**ABT Version:** 

PHP Version | 7.0.32

Gantry5 Helium Theme

Gantry 5 Framework Version 5.4.26
Gutenberg Version 4.3.0

Tool icons under Reference List 

Rolling Circle under Reference List 

**Console messages:**
```js
// Paste messages here
No error 
```

**Comment by dsifford** [comment]
Yep, the plugin in its current form will not work with gutenberg. I started working on an update last week, but it's going to require almost an entire rewrite for it to work. So support is coming, but not sure precisely when.
