### ISSUE TITLE
Fully localize the options page and all menus

### ISSUE THREAD

**Issue by dsifford** [dsifford/academic-bloggers-toolkit#53]

**Comment by dsifford** [comment]
@Vitaliy-1 @Tammakit & other multilingual plugin users out there who may be following this discussion:

I'm working on translating this plugin to multiple languages and I need your help to do it!

I'm using a service called POEditor, which allows for crowd-sourced translations from the community on projects like these. 

If you're interested in translating this plugin into your native language, please visit [this link](https://poeditor.com/join/project/PGYLKWQM5h) and submit a translation. 

Thanks in advance!

**Comment by Tammakit** [comment]
@dsifford I joined for Thai.

**Comment by dsifford** [comment]
@Tammakit Awesome! Just approved you. Thanks 😄
