### ISSUE TITLE
<!-- nextpage --> would prevent plugin from showing tooltip popups.

### ISSUE THREAD

**Issue by synyan** [dsifford/academic-bloggers-toolkit#530]
**ABT Version:4.13.3 

**PHP Version:5.4.45 

**Theme:Kogi

**Plugin List:**
- Not relevant

**Browser:** Google Chrome (Version: xxx)

**Expected behavior: Abt-tooltip shows

**Actual behavior: Article is very long, so I apply < !-- nextpage -- > all the time. However by using < !-- nextpage -- > it would prevent plugin from showing tooltip popups.

**Console messages:No errors.
```js
// Paste messages here

```

**Comment by dsifford** [comment]
`<!-- nextpage -->` seems like something that was added with either another plugin or your theme. It's not a standard feature of wordpress and, because of that, it's not something I plan on supporting.

**Comment by synyan** [comment]
OK, thank you for the swift response... I am wondering how ppl create an Academic post without paginating? If you could give me a hint it would be great... Thank you!

**Comment by geminorum** [comment]
`<!--nextpage-->` is “a standard feature of wordpress”. for more info : [Styling Page-Links](https://codex.wordpress.org/Styling_Page-Links)

**Comment by dsifford** [comment]
@geminorum Even in gutenberg? I haven't seen anything on this and it seems like an antipattern for SEO.

**Comment by dsifford** [comment]
@synyan Every medical journal I've ever read online (especially the fancy wiley ReadCube journals) all have all of their content on a single page. You just gotta scroll.

**Comment by dsifford** [comment]
Update: This is going to be fully supported in the new editor on the next release. It will not be supported in the old editor, however, you can convert from the old editor to the new editor format in one click if needed.

**Comment by dsifford** [comment]
Done
