### ISSUE TITLE
Hello! It appears the ABT works for a few minutes, but then it breaks and serves this error:  TypeError: Cannot read property 'properties' of undefined  Please report this error, including the steps taken to trigger it, here:  https://github.com/dsifford/academic-bloggers-toolkit/issues

### ISSUE THREAD

**Issue by picklecatdog** [dsifford/academic-bloggers-toolkit#532]
**ABT Version:** I don't know. How do you tell>?

**PHP Version** 7.2.12-1+ubuntu18.04.1+deb.sury.org+1

**Theme:** WPAstra v1.6.1

**Plugin List:**
  Select Academic Blogger's Toolkit  
 
  
    Select Astra Premium Sites  
 
  
    Select Astra Pro  
 
  
    Select Beaver Builder Plugin (Pro Version)  
 
  
    Select Beaver Themer  
 
  
    Select Cooked  
 
  
    Select Duplicate Page  
 
  
    Select Easy Social Share Buttons for WordPress  
 
  
    Select Head, Footer and Post Injections  
 
  
    Select PowerPack for Beaver Builder  
 
  
    Select Quick Page/Post Redirect Plugin  
 
  
    Select Schema Pro  
 
  
    Select Simple Drop Cap  
 
  
    Select Simple Share Buttons Adder  
 
  
    Select Sticky Menu (or Anything!) on Scroll  
 
  
    Select Ultimate Addons for Beaver Builder  
 
  
    Select User Role Editor  
 
  
    Select WordPress Importer  
 
  
    Select Yoast SEO Premium  
 
  
    Select Yoast SEO: Search index purge  
 
  
    Select Yoast SEO: Video  

-PHP libxml Extension
-Enabled
PHP dom Extension
Enabled

PHP libxml Extension
Enabled

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:** To input the pubmed ID and have the ABT create the bibliography.

**Actual behavior:** ABT wont accept any pubmed IDs and serves this message: 70.0.3538.110 (Official Build) (64-bit

**Console messages:**
```js
// Paste messages here

/* <![CDATA[ */
var qpprData = {"msgAllDeleteConfirm":"Are you sure you want to PERMANENTLY Delete ALL Redirects and Settings (this cannot be undone)?","msgQuickDeleteConfirm":"Are you sure you want to PERMANENTLY Delete ALL Quick Redirects?","msgIndividualDeleteConfirm":"Are you sure you want to PERMANENTLY Delets ALL Individual Redirects?","securityDelete":"5cb4a3f90b","protocols":["http","https","ftp","ftps","mailto","news","irc","gopher","nntp","feed","telnet","mms","rtsp","svn","tel","fax","xmpp"],"msgDuplicate":"Redirect could not be saved as a redirect already exists with the same Request URL.","msgDeleteConfirm":"Are you sure you want to delete this redirect?","msgErrorSave":"Error Saving Redirect\\nTry refreshing the page and trying again.","msgSelect":"select a file","msgFileType":"File type not allowed,\\nAllowed file type: *.txt","adminURL":"https:\/\/truth.co\/wp-admin\/admin.php","ajaxurl":"https:\/\/truth.co\/wp-admin\/admin-ajax.php","security":"f5814d64d2","error":"Please add at least one redirect before submitting form"};
/* ]]> */

```

**Comment by dsifford** [comment]
Assuming you're running the latest version of wordpress with the new block editor? If so, then yeah the plugin is broken for that at the moment. Working on a giant overhaul update that should fix these problems and fully support the block editor.

**Comment by dsifford** [comment]
> Though, we're not using the latest version of WordPress.

You'll need to update WordPress to at least version 5.0 to install the update when I get it released. Also of note, there is a [gigantic security risk](https://wordpress.org/news/2018/12/wordpress-5-0-1-security-release/) affecting all WordPress sites before version `v5.0.1` so it'll really benefit you to update regardless.

> One thing to note about our issue is that ABT works for an hour or so and then crashes. It's a problem that both my remote writer and myself  have experienced daily.

The update _should_ be a bit more stable. I've changes some of the fundamental ways I manage and process data which should fix those issues.

> Does the widget update automatically?

Nope, you'll need to update it from the plugins page when I push out the update.
