### ISSUE TITLE
ABT no longer working once Wordpress updated to version  5.0.2 . PHP is at version 5.6.38 and should be at 7.0 Can someone please help me update the PHP to 7.0?

### ISSUE THREAD

**Issue by sash3x** [dsifford/academic-bloggers-toolkit#534]
**ABT Version:** 4.13.3

**PHP Version:** 5.6.38

**Theme:** customized 2016

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Working on an update. Should be out soon.

**Comment by philipskokoh** [comment]
Looking forward to the update for Wordpress 5.0.3.

**Comment by dsifford** [comment]
Still working on it. It's nearly done. Unfortunately since I make no money from this whatsoever, I'm only able to work on this in my spare time.

If other priorities don't get in the way, it should be out either this weekend or next weekend at the lastest.

**Comment by sash3x** [comment]
I am using the classic editor bc when i was using the new block editor, all my existing references disappeared. Is the this cause of having a PHP not 7.0 ? My current PHP is 5.6.40, which i am looking to get upgraded to 7.0 (my wordpress version is 5.0.3). 

Thanks again for helping me out!

**Comment by dsifford** [comment]
Correct. PHP 7 is required.

**Comment by sash3x** [comment]
cool beans, i will get that upgraded and try again, If i encounter any further issues i will keep you posted!

~cheers
