### ISSUE TITLE
Version 5.0.2 and 5.0.0 stops Wordpress with 500 errors

### ISSUE THREAD

**Issue by ruffythepirate** [dsifford/academic-bloggers-toolkit#540]
**ABT Version:** 
5.0.0 / 5.0.2

**PHP Version:** 
5.6

**Theme:**
Motif v1.0.0

Wordpress version: 5.0.3

**Plugin List:**
- academic-bloggers-toolkit
- backwpup
- Bop Search Box Item Type For Nav Menus
- Captcha
- Page-list
- TablePress
- Under Construction
- Updater by BestWebSoft
- WP-ShowHide

**Expected behavior:**
When trying to active the ABT plugin, the plugin gets activated.

**Actual behavior:**
Wordpress writes the following: 
Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected '{', expecting identifier (T_STRING) in /mnt/web009/d0/68/57453968/htdocs/WordPress_01/wp-content/plugins/academic-bloggers-toolkit/academic-bloggers-toolkit.php on line 29

**Console messages:**
Error seems to happen before page is rendered. To be able to upgrade the plugin to 5.0.2 (from 5.0.0) I had to deactivate all plugins, because the page always just returned 500. In the error logs, the same error as displayed above is shown. Unfortunately, the upgrade to 5.0.2 didn't seem to solve the issue

Other comments:
The page does contain custom CSS, which I saw suggested in some other bug report might be the issue when upgrading the plugin. Unfortunately my Wordpress does not suggest upgrading the ABT plugin further than version 5.0.2. Our page used to work, we just recently discovered that it was down.

**Comment by dsifford** [comment]
PHP 5.6 is no longer supported. You'll need to update your PHP version to at least 7.0, which I would recommend regardless because PHP is no longer releasing security updates for 5.6.

**Comment by ruffythepirate** [comment]
Alright, thanks for the very quick and clear feedback!
