### ISSUE TITLE
Reference management window is gone v 5.0.2

### ISSUE THREAD

**Issue by heritiera** [dsifford/academic-bloggers-toolkit#541]
**ABT Version: 5.0.2

**PHP Version:** 7.0.29

**Theme:**MH Magazine Lite (Child)

**Plugin List:**
- Plugin 1 ABT
- Plugin 2 Admin columns
- Plugin 3 Askimet Anti-Spam
- Plugin 4 CM Tooltip Glossary
- Plugin 5 Cookie Notice
- Plugin 6 Jetpack
- Plugin 7 Official Statcounter
- Plugin 8 Pods
- Plugin 9 Wordpress post-tabs
- Plugin 10 WP PubMed ref
- Plugin 11 Tabby link to tab
- Plugin 12 Tabby responsive tabs

**Browser:** Google Chrome (Version: 71.0.3578.98)
Safari (Version: 12.0.3)

**Expected behavior:** In editing a page, I expect the panel to add or manage references to appear on the right hand side above the "publish" panel.

**Actual behavior:** The panel is missing... appears nowhere on the screen that I can find. Although all previously added references show up on the pages, I can not add or edit any new references.

**Console messages:**
```js
// Paste messages here
WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Unexpected response code: 403
```

**Comment by dsifford** [comment]
Is this with the new editor?

**Comment by heritiera** [comment]
classic

On Feb 3, 2019, at 10:50 AM, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this with the new editor?

**Comment by heritiera** [comment]
classic - but, I am using the editor with the "Pods – Custom Content Types and Fields” installed, and am working on custom posts/page types. Only the classic editor is available there.

On Feb 3, 2019, at 10:50 AM, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this with the new editor?

**Comment by dsifford** [comment]
I'm not sure what "pods" are, but the plugin only works on editors provided by wordpress. No custom editors are supported.

**Comment by heritiera** [comment]
Thanks. It looks and acts like the classic.  I will check with the pods folks too

On Feb 3, 2019, at 12:44 PM, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure what "pods" are, but the plugin only works on editors provided by wordpress. No custom editors are supported.

**Comment by heritiera** [comment]
Or, finally, is a previous version of ABT available still? I had no problems until the upgrade.

On Feb 3, 2019, at 12:44 PM, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure what "pods" are, but the plugin only works on editors provided by wordpress. No custom editors are supported.

**Comment by heritiera** [comment]
The solution -
I installed the wp classic editor plugin, set it to classic, and opened a page to edit. ATK now works like it used to.
And, thanks for this effort on your part. I do appreciate it.
jc


On Feb 3, 2019, at 12:44 PM, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure what "pods" are, but the plugin only works on editors provided by wordpress. No custom editors are supported.

**Comment by glorious1** [comment]
In case you didn't spot it, there is an icon for the plugin in upper right, an academic hat.  Also you might have to click in the content.  It seems the old page content is seen as one big block by the block editor.

**Comment by dsifford** [comment]
> Also you might have to click in the content. It seems the old page content is seen as one big block by the block editor.

In those cases, on the classic editor block, if you click the 3 dots icon you can select "convert to blocks" to transform it all into the new format.

**Comment by heritiera** [comment]
Thanks. The best solution seems to have been to install the classic editor plugin. Without that, the specialized posts (PODS) don’t talk to ABT well. Thanks for all your help and thanks for developing the plugin.
jc

On Feb 15, 2019, at 12:38 PM, Derek Sifford <notifications@github.com<mailto:notifications@github.com>> wrote:


Also you might have to click in the content. It seems the old page content is seen as one big block by the block editor.

In those cases, on the classic editor block, if you click the 3 dots icon you can select "convert to blocks" to transform it all into the new format.
