### ISSUE TITLE
File/plugin not installable

### ISSUE THREAD

**Issue by helpneeded123** [dsifford/academic-bloggers-toolkit#542]
Hello,

I downloaded the zipfile and tried installing it on WordPress, but WordPress produces an error. It says no installable plugin file could be found. I am running the latest WordPress.org version.

**Comment by helpneeded123** [comment]
Hello,

I think I found the issue. I downloaded the latest version from WordPress instead. This file was installable. However, the plugin can not be activated because of a fatal error. Probably because I am running a PHP version lower than 7.0. I don't want to update to the latest PHP version. Is there a way to get this plugin compatible with PHP < 7.0?

**Comment by dsifford** [comment]
Hi there.

You are correct. The plugin requires PHP version >= 7.0 as indicated by the plugin page (screenshot below).

I have no interest or desire to support outdated and deprecated PHP versions, so if you'd like to use it simply update your server's PHP version.

![image](https://user-images.githubusercontent.com/5240018/52358571-3b071100-2a06-11e9-8c9f-83388ae77f02.png)
