### ISSUE TITLE
Error inserting citations using Elsevier styles

### ISSUE THREAD

**Issue by spaulaus** [dsifford/academic-bloggers-toolkit#543]
**ABT Version:** 
5.0.2

**PHP Version:** 
7.2

**Theme:**
http://themeworx.net/details/corporate/corpworx

**Plugin List:**
- Academic Blogger's Toolkit
- W3 Total Cache

**Browser:** Google Chrome 72.0.3626.96

**Expected behavior/Steps to reproduce:**
1. Enabled `Elsevier (numeric, with titles)` reference type. Confirmed with other variants of the Elsevier numeric styles.
1. Add reference from DOI: 
   * Breaks when cited: `10.1063/1.3586170`
   * Works when cited: `10.1016/j.apradiso.2004.02.024`
![image](https://user-images.githubusercontent.com/1553042/52535513-5f702f80-2d1d-11e9-806e-067790604ee3.png)
2. Type text, select reference, and click "Insert Citation"
![image](https://user-images.githubusercontent.com/1553042/52535538-92b2be80-2d1d-11e9-8239-7b62e071e2b3.png)
3. Citation is inserted. 
4. Bibliography block is added / updated

**Actual behavior:**
The citation is inserted, but the bibliography block is destroyed. 
![image](https://user-images.githubusercontent.com/1553042/52535575-0b197f80-2d1e-11e9-8fc9-7f25ea627dba.png). 

**Console messages:**
https://gist.github.com/spaulaus/362776a566cf14a31b6e54302c54e966

**Comment by dsifford** [comment]
I wish more people would report issues like you. 

Thanks for the clarity. I'll try to look into this soon.

**Comment by spaulaus** [comment]
No problem! We're all in this together. Let me know if you need additional information.

**Comment by dsifford** [comment]
@spaulaus Goooooooooooooood find. Just got this sorted out locally. This was a pretty wild edge case. Glad to get it smoothed out.

I'll be pushing an update soon that includes the fix for this and a fix for a recent bug in wordpress core preventing the proper storage of citation metadata in postmeta.

Thanks again.

**Comment by spaulaus** [comment]
@dsifford : Awesome! Thanks for the quick turn around. Confirmed as working from my side. Out of curiosity, what was it about that DOI that caused the problem? 

![image](https://user-images.githubusercontent.com/1553042/52905087-e2ecbd80-3202-11e9-8d16-097c1e06ea5c.png)

**Comment by dsifford** [comment]
The data returned from crosscite is in a format that is not aligned with the CSL JSON specification (even though they claim to be). So when processing that particular style, when it hit a field that had the incorrect type, a cascading error occurred.

**Comment by spaulaus** [comment]
Ah! The old documentation switcheroo. Thanks again for your help with this!
