### ISSUE TITLE
Usage Instructions link not working

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#544]
**ABT Version:** 5.0.2

**PHP Version:** 7.2.15

**Theme:**GeneratePress

**Plugin List:**
Quite a few

**Browser:** Firefox

**Expected behavior:** In Page editing window, going into ABT's "More Options" menu and clicking "Usage Instructions", I expect it would open a window or tab and go to the github site.

**Actual behavior:** Nothing happens.

**Console messages:**
```js
// Paste messages here
```
JQMIGRATE: Migrate is installed, version 1.4.1 load-scripts.php:9:542
onmozfullscreenchange is deprecated. components.min.js:12:81117
onmozfullscreenerror is deprecated. components.min.js:12:81117

**Comment by dsifford** [comment]
I can't reproduce this unfortunately. I'll leave this open to see if more people turn up with the same problem.

**Comment by glorious1** [comment]
Thanks, looks like it is some Firefox thing (v. 65.0.1).  Tried in Safari and it worked.  Restarted Firefox, still didn’t work.

**Comment by dsifford** [comment]
Might want to open an issue with those logs here: https://github.com/WordPress/gutenberg/issues

The `onmozfullscreenchange` might have something to do with it. It's related to the `external link` component in that repo.
