### ISSUE TITLE
All references went to Uncited after update

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#545]
**ABT Version:**  5.0.3

**PHP Version:** 7.2

**Theme:** GeneratePress

**Plugin List:**
Tried with all plugins deactivated except ABT

**Browser:** Firefox 65.0.1 and Safari 12.0.3

**Expected behavior:** After updating ABT to 5.0 and new Wordpress, opening a pre-existing page with references for editing.  Expect cited references to show as cited in ABT.

**Actual behavior:** In all pages I have checked, all references are in the Uncited section of the plugin.  However, the citations and the bibliography remain.  On the front end, most pages look fine and are functional.  However in at least one page on the front end, the popups are no longer popping.

**Console messages:**
```js
// Paste messages here
Firefox:
JQMIGRATE: Migrate is installed, version 1.4.1 load-scripts.php:9:542
onmozfullscreenchange is deprecated. components.min.js:12:81117
onmozfullscreenerror is deprecated. components.min.js:12:81117

On the front end, for a page for which the citation popups don't pop, I see this console msg.  It doesn't appear on a page for which popups work:
TypeError: e.itemContainer.children.namedItem(...) is null[Learn More] index.ts:124:27 
    	citations index.ts:124 
       map (index):286 
        t index.ts:123 
        157 index.ts:184 
Safari:
JQMIGRATE: Migrate is installed, version 1.4.1
```
![all uncited](https://user-images.githubusercontent.com/6004417/52901863-aea2de00-31bd-11e9-8406-e4f797d14bf6.png)

**Comment by dsifford** [comment]
This was a bug with the update before the last update which has now been fixed.

**Comment by glorious1** [comment]
Sorry, I don’t quite follow.  This problem is showing up in 5.0.3, which seems to be latest update.  Every page I newly open for editing has all the references in Uncited.  Do I need to do something to trigger getting them recognized as cited?

Then there is the probably separate issue on one or a few pages where the popups don’t work, and the associated javascript error.  I probably should have submitted it separately. 

With just one or two pages, it would be feasible to delete all the references and do them over again to fix the second problem.

**Comment by dsifford** [comment]
> Every page I newly open for editing has all the references in Uncited.

That is correct. The last update used a WordPress core API that WordPress broke (and that is still broken) causing citations to not save properly in the post when posts saved. 

This update fixes that issue by circumventing the WordPress save API so all new posts will properly save post metadata.

The unfortunate downside is that all posts between around sometime 2(ish) weeks ago and yesterday will have been affected and there's no way to recover those references without adding them all over again.

**Comment by dsifford** [comment]
It should be known that this is an issue with WordPress core code. Not this plugin. The update I pushed yesterday just circumvents the still existing issue with wordpress core.

**Comment by glorious1** [comment]
> The unfortunate downside is that all posts between around sometime 2(ish) weeks ago and yesterday will have been affected and there's no way to recover those references without adding them all over again.

Understood, but this is happening with all pages, some of which have not been revised or even opened in over 7 months.

**Comment by dsifford** [comment]
Ah yes, that's a feature. 

Until posts are converted, references cited in the old "classic" editor are not tracked. They're still there though.

**Comment by glorious1** [comment]
Whew, that’s a relief.  Now I can see a lot of things have changed in the html and css also.  Now the popups pop on hover instead of clicking.  It makes sense, but I’m gonna miss those cool spinning X’s to close them ;-)

I hope I can ask one css question.  In my csl file, I have a property/value:
second-field-align="margin"
This meant the first field (reference number) is put left of the margin this amount, and subsequent lines are aligned with the margin.  I would add a css margin-left to .csl-entry, and the reference number moved left that amount.  A screenshot is attached.

I can't get that to work anymore.  Is it readily obvious to you how I might reproduce that behavior?
![screen shot 2019-02-16 at 12 01 05 pm](https://user-images.githubusercontent.com/6004417/52904754-57186880-31e5-11e9-930d-00d199369666.png)

**Comment by dsifford** [comment]
Can you show an example of what it looked like before and after?

**Comment by glorious1** [comment]
Yes, the above (attached to previous msg) is similar to before - I have not updated that page since the transition, although I've been working on adapting the css so that influences the look. But the hanging indent you see there is the key thing I am trying to achieve in the new system.
Attached below is page I have updated.
![screen shot 2019-02-16 at 12 58 00 pm](https://user-images.githubusercontent.com/6004417/52905151-eecc8580-31ea-11e9-9381-5d384342d398.png)

**Comment by dsifford** [comment]
Do you have existing css that could potentially be modifying how it looks now or is the style exclusively coming from the plugin? If the former, can you try commenting out the custom css styles and show what it looks like at baseline?

**Comment by glorious1** [comment]
Yes, I do have some css.  Here is how the updated page looks with my css disabled and browser cache cleared:

![screen shot 2019-02-16 at 4 15 47 pm](https://user-images.githubusercontent.com/6004417/52906707-5e9c3980-3206-11e9-9b75-aa1ba9dbf04b.png)

**Comment by glorious1** [comment]
I'm getting more confused.  Without any of my css, pages I updated yesterday have no outdent, while one I updated this morning does.   Yesterday:
![screen shot 2019-02-17 at 7 02 15 am](https://user-images.githubusercontent.com/6004417/52914881-66012880-3282-11e9-8b65-77fc4f3e5be0.png)
 and today:
![screen shot 2019-02-17 at 7 02 51 am](https://user-images.githubusercontent.com/6004417/52914883-6f8a9080-3282-11e9-91da-103d915077cc.png)

**Comment by dsifford** [comment]
Difficult for me to really understand fully without having a link to a page to see, but one thing I will say is that the old bibliography and new bibliography have slightly different html formatting, the newer being better for accessibility and screen readers.

So that is likely the cause for disparity between the old and new posts.
