### ISSUE TITLE
Hate Gutenberg

### ISSUE THREAD

**Issue by yigitkirca** [dsifford/academic-bloggers-toolkit#546]
**ABT Version:** 5.0.3

**PHP Version:** 7.2.6

**Theme:**  Goodlife

**Browser:** Firefox Quantum (Version: 65.0.1)

**Expected behavior:** Works in classic editor.

**Actual behavior:** Not appear in classic editor.

**Console messages:**
```js
// Paste messages here


Hi. I really like the inline widget for the classic editor. I hate Gutenberg like most of WP users & developpers. Even WP create a plugin for classic editor. So it would be cool if you add the old version for non-Gutenberg users.

Also there was a “Generic – Note” part. I used it for translated quotes. That’s all. I wait a new update. Cheers.

```

**Comment by helen-oneill** [comment]
I am having a horrible time with ABT in the new Gutenberg editor. 
I follow the method I used previously of exporting from Endnote as .ris, Import the .ris file into the reference list, and attempt to 'add reference' by clicking '+' which it then asks for a DOI, PMID or PMCID or 'add manually'. I frequently have ISSN's recorded in Endnote but not the others. What is going on/what am I doing wrong?! Can someone help?

**Comment by glorious1** [comment]
helen-oneill, in the popup you refer to that asks for DOI/PMID etc, you need to click "Add manually" in the lower left to manually add a reference.  But if you have imported them as a ris, as you describe, that is unnecessary.  Just expand the Uncited Items section and select the reference.  You must put your cursor in a block (in the text) before or after this.  Then a left-pointing arrow will appear at the top to the left of that circled + sign.  That will insert the reference.

**Comment by dsifford** [comment]
This plugin still supports the classic editor if you have the classic editor plugin installed. But it's legacy and I don't plan on continuing support forever.

"Generic - Note" was removed because now there is support for actual footnotes.

Sorry to hear that you're not enjoying Gutenberg. I guess I'm in the minority because I think it's a gigantic step in the right direction for WP.
