### ISSUE TITLE
Gutenberg adding references not working 

### ISSUE THREAD

**Issue by helen-oneill** [dsifford/academic-bloggers-toolkit#547]
**ABT Version:** 
5.0.3

**PHP Version:** 
7.2 

**Theme:**
Maisha

<!--
Which web browser are you using (including version)
== How to find your browser version ==
Google Chrome: Enter "chrome://version" in the URL bar.
Firefox: Open the menu -> click "help" -> click "About Firefox"
Edge: Select More in the upper-right corner, and then select Settings. Then look for your version under "About this app".
Safari: Click "Safari" -> "About Safari"
Opera: Click the "Opera" button -> Click "About Opera"

**Browser:** Google Chrome (Version: xxx)
Chrome Version 72.0.3626.119

I am having a horrible time with ABT in the new Gutenberg editor.
I follow the method I used previously consisting of 1. exporting from Endnote as .ris,  2. Import the .ris file into the reference list, 3. click 'add reference' (+). i do this the same but it then asks for a DOI, PMID or PMCID or an option to 'add manually'. I frequently have ISSN's recorded in Endnote but not the others. What is going on/what am I doing wrong? Can someone help?

**Comment by dsifford** [comment]
This is not enough information for me to be able to even begin figure out what is going on. If you'd like you may reopen this with more detailed information.

**Comment by helen-oneill** [comment]
Hi Derek, thanks for the reply. 
The coding caught me out and hid the remained of my question, apologies for this. I have amended it so hopefully you now may be able to help.

Best wishes,
Helen

**Comment by dsifford** [comment]
Thanks @helen-oneill... The issue I think you're having is you're attempting to "insert" references, but you're clicking the "add reference" button.

Here's an example: 

https://www.useloom.com/share/9ec376632142463ab775db89f1a4ecff

**Comment by helen-oneill** [comment]
Hi Derek,

Thanks for your email and for the video. I can see now what is happening – you were correct in thinking that I was selecting the ‘add reference’ button instead of the ‘Insert citation’ button, however the ‘insert citation’ button disappears when the content block type is ‘Custom HTML’, in either ‘HTML’ or ‘preview’ mode.

I made a Loom for you too:
https://www.useloom.com/share/1703a91e663b4e989efb74ed9cd4e202

Cheers,
Helen

**Comment by dsifford** [comment]
@helen-oneill Ah, yep, that's by design. There's no way the plugin can manage or even be aware of citations inside a custom HTML block, unfortunately.

The same is true for shortcode blocks.

**Comment by helen-oneill** [comment]
Ok I have found a solution that seems to work by mikeicode on this issue thread: https://github.com/WordPress/gutenberg/issues/6833

mikeicode wrote:

"You can achieve this with CSS.

If you add the following CSS at Appearance → Customize → Additional CSS:

/* --- Justify Text Option --- */
.justify-text {
	text-align: justify;
}
Then in the editor when you have a block selected you can add the CSS class justify-text in the right bar under "Advanced", example: https://snag.gy/SKIoHe.jpg "

I can now insert citations into justified text without issue. 

![image](https://user-images.githubusercontent.com/37096834/54241767-30481a80-4576-11e9-8678-1b37672c1fc3.png)
