### ISSUE TITLE
Reference List shows endless spinner when Visual Editor is disabled

### ISSUE THREAD

**Issue by danielsefton** [dsifford/academic-bloggers-toolkit#55]
The Reference List shows an endless spinner when loading the Edit Post page with the "Text" tab selected. It only loads if you click on the Visual editor.

I usually have the visual editor disabled by default since I prefer to be in control of the HTML - the visual editor can sometimes cause formatting problems.

Therefore it would be nice if it worked as it does with the visual editor, but inserts the "span" HTML wherever you have your cursor in the Text editor.

![screen shot 2016-05-02 at 12 45 28](https://cloud.githubusercontent.com/assets/832011/14998807/92844456-117d-11e6-84ba-75683b576312.png)

**Comment by dsifford** [comment]
Update: This is possible, but it's going to take a lot of work. (WordPress and TinyMCE has made this, which should be so super simple, into a gigantic chore).

Will report back with updates as progress is made

**Comment by dsifford** [comment]
@danielsefton Waiting on a reply [here](https://github.com/tinymce/tinymce-docs/issues/339) then I'll be able to get started on this.

**Comment by dsifford** [comment]
@danielsefton This won't be possible unfortunately. Finalizing the latest update now which includes real-time in-text citation parsing based on citation type and a slew of other options and it just can't be done without the visual editor.
