### ISSUE TITLE
"Unexpected error" preventing adding citations

### ISSUE THREAD

**Issue by cfjen** [dsifford/academic-bloggers-toolkit#550]
**ABT Version:** 5.0.3

**PHP Version:** 7.3

**Theme:** Custom

**Plugin List:**
- 404 to 301
- Academic Blogger's Toolkit
- Activity Log
- AddFunc Head & Footer Code
- AHAX
- Annual Archive
- Anti-Malware Security and Brute-Force Firewall
- AtlanitcBT Restrict Doctors Directory
- Black Studio TinyMCE Widget
- Campaign Monitor
- Child Theme Configurator
- Classic Editor
- Comet Cache Pro
- Cookiebot
- Custom Post Templates
- Duplicate Post
- Easy Media Gallery Pro
- Enable Media Replace
- Google Analytics +
- Link to link
- Lock Your Updates Plugins/Themes Manager
- Max Mega Menu
- Monarch Plugin
- Official Facebook Pixel
- Open external links in a new window
- PHP Settings
- Quick Page/Post Redirect Plugin
- Really Simple SSL
-Shortcodes Ultimate
- Simple Custom Post Types
- SiteOrigin CSS
- Snapshot Pro
- StarBox
- TinyMCE Advanced
- Use Google Libraries
- Wordfence Security
- WP CSV
- WP Mail SMTP
- WP Realtime Sitemap
- WP Unformatted
- WP-FormAssembly
- WP-Paginate
- WPFront Notification Bar
- WPMU DEV Dashboard
- Yoast SEO

Which web browser are you using (including version): Chrome 72.0.3626.109

Edit the following page https://www.chordomafoundation.org/targets/swisnf/ to enter DOI 10.1155/2018/4290131 as a citation

Entered DOI number and received an error that says:

An unexpected error occurred
undefined: undefined
Please report this error, including the steps taken to trigger it. 

Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details
dnh5izz.js:1 Failed to load resource: the server responded with a status of 404 ()
index.ts:124 Uncaught TypeError: Cannot read property 'outerHTML' of null
    at index.ts:124
    at Array.map (<anonymous>)
    at new t (index.ts:124)
    at HTMLDocument.<anonymous> (index.ts:184)

**Comment by dsifford** [comment]
Hm... not sure. I just tried entering the DOI provided and was able to add it with no problems.

You have quite a few other plugins listed. Have you attemped to disable some of those to see if perhaps there's some conflict one of those and this one?

Also of note: I noticed you are using the classic editor. That is still supported for the time being, but support will not be continued for much longer.

**Comment by cfjen** [comment]
Hi Derek,

The issue appears to be specific to a single page on our website.

https://www.chordomafoundation.org/targets/swisnf/

We can add citations on other pages, including the DOI that I shared, but
not on this one page. We had our website support company look at it and
they don't see anything different on this page from the others. They did a
number of WP and PHP updates thinking that could be an issue, but there was
no change and we are still getting the same undefined error.

There are 17 citations already on this page. Is there a limit to the number
of citations on a page?

Thanks,

Jen

P.S. Yes, we have a lot of plugins. The site was built in 2012 and needs
some updating.

Jennifer Roeder
Marketing and Communications Manager
Chordoma Foundation
(919) 809-6779 ext. 116
jennifer@chordoma.org

*Improving the lives of those affected by chordoma. Leading the search for
a cure.*

**Comment by dsifford** [comment]
Sorry for the delay.

Was this ever sorted out? To answer your question: No there is no limit to number of citations on a page. Sometimes though when other updates occur to the post, the metadata for the citations can get corrupted which would cause very unpredictable errors. This sounds like it could be that.

The solution would be, unfortunately, to blast all the references from the page (using the "Remove all citations" button) and re-add them.

Let me know if that doesn't work.

**Comment by cfjen** [comment]
Hi Derek,

This has not been sorted out. We will try to remove all the citations and
see if that works.

Thanks,

Jen


Jennifer Roeder
Marketing and Communications Manager
Chordoma Foundation
(919) 809-6779 ext. 116
jennifer@chordoma.org

*Improving the lives of those affected by chordoma. Leading the search for
a cure.*

**Comment by dsifford** [comment]
Closing this issue as I haven't heard back. Reopen if this is persisting.
