### ISSUE TITLE
Insert Footnotes (Gutenberg)

### ISSUE THREAD

**Issue by sourenaa** [dsifford/academic-bloggers-toolkit#553]
**ABT 5.0.4:** 

**PHP Version 7.0.33:** 

**Browser:** Pagelines

**Plugin List:**

**Browser:** Google Chrome 73.0.3683.86

**Expected behavior:** I expected the footnotes to be ordered in numbers but instead of numbers the plugin created signs like † and §

**Actual behavior:**  Instead of numbers for the footnotes the plugin created signs like † and §.

**Console messages:**
```js
// 

JQMIGRATE: Migrate is installed, version 1.4.1
The resource https://pagead2.googlesyndication.com/pagead/js/r20190403/r20190131/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
log-view.js:16 Log success!

```

**Comment by dsifford** [comment]
This is a feature, not a bug. 

The reason why footnotes use symbols and not letters/numbers is to prevent overlap between citation styles that use letters/numbers and the footnotes.
