### ISSUE TITLE
Unexpected errors and endless match format loop

### ISSUE THREAD

**Issue by ticktickatick** [dsifford/academic-bloggers-toolkit#555]
**ABT Version**
Latest

**PHP**
7.0.3 using Wordpress 5.1.1

**Theme**
- Twenty Thirteen

**Plugins**
- Academic Blogger's Toolkit
- Classic Editor
- Akismet Anti-Spam
I disabled Akismet but did not disable Classic Editor because I can't use Block Editor effectively right now. Block Editor is still beta anyway.

**Browser:** Safari Version 11.1.2 (13605.3.8)

**Expected behavior:**

Adding a Webpage citation MANUALLY:
It tells me to "Match the requested format" in both Date fields. It does not indicate what this means or what the format is. I've tried all formats I know of.

If I submit with date fields EMPTY, then it throws "Unexpected Error."

Adding a Journal citation MANUALLY
It tells me to "Match the requested format" in the Date field.  It does not indicate what this means or what the format is. I've tried all formats I know of.

If I leave the Date field empty it tells me to "fill out this field"

**Console messages:**
```js
The XSS Auditor refused to execute a script in 'http://URL REDACTED/wp-admin/post.php?post=2447&action=edit&message=10' because its source code was found within the request. The auditor was enabled because the server did not send an 'X-XSS-Protection' header. (post.php)

Error: Mismatched anonymous define() module: function (){function a(a){var b=a.toUpperCase().split(" "),c=[],d={"\u2190":37,"\u2191":38,"\u2192":39,"\u2193":40};return b.forEach(function(a){"number"==typeof a?c.push(a):d[a]?c.push(d[a]):c.push(a.charCodeAt(0))}),c}function b(){this._codes={},this._handler=null}return b.prototype._evaluate=function(a){for(var b in this._codes){var c=this._codes[b];c.index=a===c.keys[c.index]?c.index+1:0,c.index===c.keys.length&&(c.index=0,c.callbacks.forEach(function(a){a()}))}},b.prototype.addCode=function(b,c){var d=this._codes[b];if(d)-1===d.callbacks.indexOf(c)&&d.callbacks.push(c);else{if(!this._handler){var e=this;this._handler=function(a){e._evaluate(a.keyCode)},window.addEventListener("keydown",this._handler)}d={callbacks:[c],keys:a(b),index:0},this._codes[b]=d}},b.prototype.removeCode=function(a,b){if(void 0===a&&void 0===b)this._codes={};else if(void 0===b)delete this._codes[a];else{var c=(this._codes[a]||{}).callbacks||[],d=c.indexOf(b);d>-1&&c.splice(d,1)}Object.keys(this._codes).length||(window.removeEventListener("keydown",this._handler),this._handler=null)},b.Code={Batman:"\u2191 \u2191 \u2193 \u2193 \u2190 \u2192 \u2190 \u2192 B A"},window.Konami=b,b}
http://requirejs.org/docs/errors.html#mismatch (require.js)
```

**Comment by ticktickatick** [comment]
I just tested it on Firefox, which gave a more helpful "match the requested format as indicated..." However when I put in appropriately formatted dates it still threw "Unexpected error"

**Comment by ticktickatick** [comment]
It seems that it wasn't the manually added citation but other citations in the post. I removed "æ" from one author in a ctiation and "&amp;" from one title in a citation. Should note that ABT pulled both of those automatically with a DOI insertion so if it's having problems with those characters then it's own pull is failing.

**Comment by dsifford** [comment]
Thanks for the detailed info. Duly noted!

I'm working on an update for WordPress 5.2 as we speak. I'll add this to the list for that update :+1:

**Comment by dsifford** [comment]
@ticktickatick Do you have the DOIs handy for the citations that caused trouble?

**Comment by dsifford** [comment]
Also, I just noticed in your first message you wrote...

> I disabled Akismet but did not disable Classic Editor because I can't use Block Editor effectively right now. Block Editor is still beta anyway.

I stopped actively supporting the classic editor in version 5, and plan to remove support completely in one of the coming releases so just keep that in mind. The block editor is no longer considered beta. It's fully released.

**Comment by ticktickatick** [comment]
> Also, I just noticed in your first message you wrote...
> 
> > I disabled Akismet but did not disable Classic Editor because I can't use Block Editor effectively right now. Block Editor is still beta anyway.
> 
> I stopped actively supporting the classic editor in version 5, and plan to remove support completely in one of the coming releases so just keep that in mind. The block editor is no longer considered beta. It's fully released.

You might want to consider supporting ClassicPress if not the Classic Editor plugin. Many that I know in the academic field do not support the limited block editor. I see much more hate for Gutenberg than not on the Wordpress forums. If I wanted to write on Medium, I would write on Medium. 

https://deliciousbrains.com/wordpress-gutenberg/

**Comment by dsifford** [comment]
I hear ya, and I understand the frustration. However there's just too much technical debt required to support both types of editors and since I make no money for my time on this, it'll be easier for me in the long run.

I'd give the block editor another shot. They are improving it massively on each iteration and, if I may also add, are extremely receptive to suggestions/feedback if you open an issue [in their repository](https://github.com/WordPress/gutenberg/issues)

-----------

Back to this issue: Did you have that DOI handy?

**Comment by dsifford** [comment]
Not gonna be able to make the fix into this next release unless I hear back.

**Comment by dsifford** [comment]
Closing this since I haven't heard back. Reopen this if you're still having issues or if you're able to provide that DOI.
