### ISSUE TITLE
Custom citation style won't appear in the dropdown

### ISSUE THREAD

**Issue by axibert** [dsifford/academic-bloggers-toolkit#556]
I uploaded a custom citation style and gave it a unique filename and title.
I uploaded it in the settings but it can't be selected in the posts, because it does not appear in the dropdown list. What am I possibly missing here?

Thanks for your help,
Alex

**ABT Version:** 5.05

**PHP Version:** 7.3.3

**Theme:** Sahifa

**Comment by glorious1** [comment]
I find I have to type in the style name (not the file name, the name as given in the <info><title> tag) until it is different from all the canned styles, then mine appears.

**Comment by axibert** [comment]
Yes, I tried exactly that, but for me it won't show up. I already tried it with two different styles but none appears. And when I just enter the full name as in the <title> tag and hit Publish it says incorrect citation style.

**Comment by glorious1** [comment]
Just spitballing here - I would try running the style through the csl validator:
https://validator.citationstyles.org/
Choose File upload to get it in.

**Comment by axibert** [comment]
Thanks for the tool, but sadly it does not solve my issue. I also just tried it with another popular citation style where I just changed the name and it still does not show up.

**Comment by axibert** [comment]
Would be great if the developer could look into this, I still cannot use custom styles.

**Comment by dsifford** [comment]
@axibert Can you share the custom style file here so I can take a look at it?

**Comment by axibert** [comment]
Sure, here it is: https://www.dropbox.com/s/tnseg3erc0jzm3u/testalex2.csl?dl=0
I just changed the name and the title to test it out, so it basically is an unchanged APA style.

**Comment by dsifford** [comment]
@axibert I can't reproduce this on my end in the block editor.

![image](https://user-images.githubusercontent.com/5240018/56449000-5afa6100-62e2-11e9-83ac-b453b0ab9f71.png)

I am able to reproduce in the classic editor, but that's not something I'm planning on fixing seeing as I'm planning on removing support completely for the old editor in the next update as it's becoming too much of a chore to maintain both codebases in tandem and WordPress no longer supports it either.

I'd recommend checking out the block editor again. I know there's been some community resistance to using it, but if you haven't checked it out in a while you might be pleasantly surprised at how much it has improved and how quickly it continues to improve by the day.
