### ISSUE TITLE
Book editors imported as chapter authors from RIS file

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#557]
**ABT Version:** 5.0.5

**PHP Version:** 

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:** In chapters, authors and editors are imported as such.

**Actual behavior:** Book editors become chapter authors.

**Console messages:**
```js
// Paste messages here

```
This seems to be new behavior.  In the attached RIS, chapter authors were exported as tag AU; book editors as A2.  In ABT, they all become authors.
[chaps.ris.txt](https://github.com/dsifford/academic-bloggers-toolkit/files/3086166/chaps.ris.txt)

**Comment by dsifford** [comment]
Sorry for the delay. I checked this out and unfortunately there's not much I can do about making this more accurate since, per the RIS specification, the definition of `A2` varies by both publication type and by the implementer.

So just keeping it as author is the safest way since the available fields for any given citation varies in the manual reference editor.

Long story short: Just fix it after you import.

I'll probably add the ability to import CSL JSON soon(ish) which will completely resolve your issue. Zotero allows exporting in that format.

**Comment by glorious1** [comment]
OK, thanks for following up.  I've switched to Zotero from Bookends as my reference manager thinking it would increase compatibility with ABT, as both are based on CSL.  Seems not the case.

I see Bookends exports book editors with the tag 'ED', which presumably is compatible with ABT.  Maybe I should ask the Zotero folks to consider changing that.  There doesn't seem to be a way for a user to edit the tag mapping.

**Comment by glorious1** [comment]
Just in case anyone is researching this issue, I found one can edit Zotero's RIS.js translator file to make editors come out with tag ED instead of A2 or A3.  Just remove bookSection from the A2 list and book from the A3 list, and make an ED list with those two types.  Then way down under Export Functions, var exportOrder, __default, add ED.  Then they import right into ABT.

**Comment by dsifford** [comment]
I'd recommend you consider contributing that change into their codebase. Open up a PR if that solved your issues: https://github.com/zotero/zotero

**Comment by glorious1** [comment]
Thanks,

I asked on their support forum if they would consider such a pull request.  They replied no, that Zotero follows the RIS specification (which is linked to).
https://forums.zotero.org/discussion/comment/333487#Comment_333487 <https://forums.zotero.org/discussion/comment/333487#Comment_333487>

I dug up the original specification (which is now only available on the wayback machine) and they do seem to follow it:
https://web.archive.org/web/20120526103719/http://refman.com/support/risformat_intro.asp <https://web.archive.org/web/20120526103719/http://refman.com/support/risformat_intro.asp> (look for the complete documentation link to download, the excel file has the important reference type/tag matrix).

Although, I’ve also seen some discussion among the Zotero folks that RIS is a hot mess.

**Comment by dsifford** [comment]
You hit the nail on the head: RIS is a disaster, which is a shame since it's so easily parseable. 

I'm hoping to add support for CSL JSON soon which with be a direct 1:1 import, since that's what format is used internally.
