### ISSUE TITLE
Two references confusing ABT

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#558]
**ABT Version:** 5.0.5

**PHP Version:** 

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:** Import references and have them separate entitites.

**Actual behavior:** Two references in the attached RIS are making ABT go nuts.  They are the two whose titles begin with <i>Leptographium.  Here's what I've seen:
1.  Selecting one of them appears to select both.
2. Inserting inserts just the first one, which then shows up in both the Cited and Uncited reference sections.
3. After the insertion, the second reference disappears.
4. Can't intentionally delete these references until all other references are deleted.

**Console messages:**
```js
// Paste messages here

```
This appears to be unique to the two indicated references.  Have not seen it in any others (including many that have the <i> tag).
[refs2in1.ris.txt](https://github.com/dsifford/academic-bloggers-toolkit/files/3086197/refs2in1.ris.txt)

**Comment by dsifford** [comment]
The issue is because those two citations are keyed IDed using the ISBN, but the ISBN is the same. So yep, bug. I'll fix soon(ish).
