### ISSUE TITLE
Need to be able edit/remove footnotes ...

### ISSUE THREAD

**Issue by Cagetopia** [dsifford/academic-bloggers-toolkit#559]
**ABT Version:** 5.0.5

**PHP Version:** 7.2.17

**Theme:** ReHub

**Plugin List:**
- CMP
- Woocommerce
- WP Bakery Page Builder
- Yoast

**Browser:** Google Chrome (Version: 73.0.3683.103)

**Expected behavior:**
Be able to edit and remove footnotes

Even if I try to remove the footnote reference in the text of the article, it comes back. Cited or uncited references are able to be edited and removed, but footnotes are not.

Also, is there a way to see all the styles somewhere without having to select them to look at them?

Also, what is the best way to add a "REFERENCES" heading above the references and below the footnotes in the post/article?

Thanks very much!!

**Actual behavior:**
Once added, cannot be removed or edited

**Console messages:**
```js
// Paste messages here

No js errors

**Comment by dsifford** [comment]
@Cagetopia Are you using the classic editor or the new block editor?

Some of the things you're describing _should_ be available and working in the block editor. If you're using the classic editor, just be aware that support is being dropped for that and it will be gone on the next update.

> Also, is there a way to see all the styles somewhere without having to select them to look at them?

Yep. Check out this page: https://editor.citationstyles.org/about/

> Also, what is the best way to add a "REFERENCES" heading above the references and below the footnotes in the post/article?

Use the block editor.

**Comment by dsifford** [comment]
Closing this issue since I haven't heard back. Assuming you've got it all squared away. Reopen if that's not the case.
