### ISSUE TITLE
Heading missing and active links are not working after wp update 

### ISSUE THREAD

**Issue by drhaldun** [dsifford/academic-bloggers-toolkit#561]
**ABT Version: 5.0.5
**PHP Version: 7.2.17-0ubuntu0.18.04.1
**Theme: Jannah
**Plugin List:**

Which web browser are you using (including version) Safari 12.0.3

**Expected behavior: The heading for the references section (Bibliography) is missing. Reference links in the text are not active. 

<img width="1440" alt="Screen Shot 2019-05-02 at 10 24 11" src="https://user-images.githubusercontent.com/34509215/57061127-7db64d80-6cc4-11e9-914c-7210631c5d1e.png">

**Comment by dsifford** [comment]
Were these posts written with the "classic" editor?

**Comment by drhaldun** [comment]
Yes. All written with the classic editor not new block editor 

Haldun Akoglu, MD
-------------------
Assoc. Prof. Emergency Medicine 
Marmara University Dep. Emergency Medicine, Istanbul, Turkey 

Editor-in-chief, Turkish Journal of Emergency Medicine @TurkJEmergMed
Founder of www.acilci.net @acilci_net 
-------------------
E-mails: drhaldun@gmail.com - haldun.akoglu@marmara.edu.tr 
Twitter @IstanbulEMDoc

Derek Sifford <notifications@github.com> şunları yazdı (2 May 2019 17:30):

Were these posts written with the "classic" editor?

**Comment by dsifford** [comment]
Hm. I see. 

Here's some thoughts...

First, just be aware that support for the classic editor is being phased out and there will be no more updates supporting the classic editor for the forseeable future. So just keep that in mind.

Regarding the tooltips: It looks like, for whatever reason, the frontend scripts aren't being loaded on your pages that control those. So my first thought would be to see if you can investigate why that might be happening.

Regarding the legacy bibliography headings: The best fix for that would be to convert posts from the classic editor to the block editor and those will fix themselves (but I understand that for users who have potentially years of old posts, that's not totally feasible).

A solution in that case would be to drop-in a CSS shim in your site's custom CSS.

For example, if you want your bibliographies to have the heading "My Bibliography" the CSS might look like this for you...

```css
#abt-bibliography__container::before {
    content: 'My Bibliography';
    font-weight: bold;
    font-size: 1.5em;
    line-height: 2.5em;
}
```

Let me know if you're able to turn up any other details as to why those scripts aren't loading on your frontend.

**Comment by dsifford** [comment]
Haven't heard back on this. Gonna close it for now since it's a bit old. Feel free to reopen if this is still affecting you.
