### ISSUE TITLE
ABT Dissapeared

### ISSUE THREAD

**Issue by bockal** [dsifford/academic-bloggers-toolkit#562]
**ABT Version:** 5.1.0

**PHP Version:** 

**Theme:** GeneratePress

**Plugin List:** https://cinci360.com/wp-content/uploads/2019/05/broken.png
- Plugin 1 Screen shot of 16 plugins above URL
- Plugin 2

**Browser:** Google Chrome (Version: xxx) Chrome 74.0.3729.131 (Official Build) (64-bit)

**Expected behavior:** Plugin worked awesomely, then stopped appearing this week.

**Actual behavior:**

**Console messages:** No error messages to display
```js
// Paste messages here

```

**Comment by dsifford** [comment]
The classic editor is no longer supported (at least for the foreseeable future).

Convert existing posts to the new block editor if you'd like to continue using ABT.
