### ISSUE TITLE
Some fields not importing in Book type

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#567]
So I'm getting back to production, and found that three fields aren't importing to ABT in the Book reference type.  The fields are:

Zotero UI | CSL Field | RIS | ABT UI
----------|-------------|-----------|--------------
Series | collection-title | T2 | Series Title
Series Number | collection-number | M1 | Series Number
\# of Pages | number-of-pages | SP | # of Pages

Here is a RIS file with a few books where those fields don't import (only one has series)
[test.ris.txt](https://github.com/dsifford/academic-bloggers-toolkit/files/3234619/test.ris.txt)

**Comment by dsifford** [comment]
I'm having a hard time understanding your table.

Glancing at it, it shows that both Zotero and ABT UI match? So we're good?

**Comment by glorious1** [comment]
No, unfortunately.  The disconnect is between the RIS fields and ABT.  None of those fields show up in ABT after import.

**Comment by dsifford** [comment]
I see.

Well unfortunately, "fixing" for book would mean breaking for other types. T2 and T3 are used for Series Title, so changing it to support book, would break in others.

M1 is an arbitrary metadata field which is linked to `number` to best support _most_ cases.

`SP` is not `number-of-pages`. It is to be used only and exclisively for **S**tart **P**age.

So gonna close this due it being just the quirks of RIS. Hopefully I'll have time soon to work on #568. Keep an eye on that.

**Comment by glorious1** [comment]
Not to beat a dead horse, and I know you just want to forget RIS and move on, and that's fine, but just FYI the meaning of the RIS tags varies among the reference types.  Here is the tag reference for BOOK type, from the RIS standard issued by Thomson Reuters (now available at the bottom of [this page](https://support.clarivate.com/Endnote/s/article/EndNote-Directions-for-implementing-EndNote-Direct-Export?language=en_US)).

Note that
T2 is Series Title (as you said, but it doesn't import as that in a BOOK) 
M1 is Series Volume
SP is number of pages


TY  - | `BOOK`
-- | --
A3  - | Editor
A2  - | Series Editor
A4  - | Translator
AB  - | Abstract
AD  - | Author Address
AN  - | Accession Number
AU  - | Author
C3  - | Title Prefix
C4  - | Reviewer
CA  - | Caption
CN  - | Call Number
CY  - | City
DA  - | Date
DB  - | Name of Database
DO  - | DOI
DP  - | Database Provider
ET  - | Edition
J2  - | Abbreviation
KW  - | Keywords
L1  - | File Attachments
L4  - | Figure
LA  - | Language
LB  - | Label
M1  - | Series Volume
M3  - | Type of Work
N1  - | Notes
NV  - | Number of Volumes
OP  - | Original Publication
PB  - | Publisher
PY  - | Year
RN  - | Research Notes
RP  - | Reprint Edition
SE  - | Pages
SN  - | ISBN
SP  - | Number of Pages
ST  - | Short Title
T2  - | Series Title
TA  - | Translated Author
TI  - | Title
TT  - | Translated Title
UR  - | URL
VL  - | Volume
Y2  - | Access Date
ER  - | {IGNORE}

**Comment by dsifford** [comment]
I'm aware.

Unfortunately, as stated previously...

1. If I change `T2`, I'd break journal title for citing academic journals.
2. If I change `SP`, I'd break all sorts of other types of citations that use it when paired with `EP` for start and end pages.

I might be able to be convinced to change `M1`, but that should be done in the appropriate repo, not here. See: https://github.com/dsifford/astrocite
