### ISSUE TITLE
No option to edit or add references

### ISSUE THREAD

**Issue by cfjen** [dsifford/academic-bloggers-toolkit#575]
**WP Version:** 5.2.2

**ABT Version:** Unknown. There is not an option to update the plugin. The details page does not show the current version of ABT.

**PHP Version:** 7.3.7

**Theme:** Custom Snapsite Child

**Plugin List:** Many (None recently added)

**Browser:** Google Chrome | 75.0.3770.142

**Expected behavior:** See the option to add or edit references when editing a page

**Actual behavior:** The references panel is not available from the back end despite seeing references on the front end. New pages don't have the references page either, but a reference footer box appears at the end of the page.

**Console messages:** Failed to load resource: the server responded with a status of dnh5izz.js:1 404 ()

**Comment by dsifford** [comment]
I'll need to have more information to be able to understand what's going on.

Plugin list matters. Most issues that arise are due to conflicts that happen between plugins.

I will say though that the last update removed support for the old "classic" editor. So if you're trying to use it in the classic editor and it's not showing up, that's why.

**Comment by cfjen** [comment]
We are on the classic editor. That must be the issue. That creates a
challenge as our website isn't supported by the new editor.

Jen

Jennifer Roeder
Marketing and Communications Manager
Chordoma Foundation
(919) 809-6779 ext 116
jennifer@chordoma.org

*Improving the lives of those affected by chordoma. Leading the search for
a cure.*

**Please note I am out of the office on Fridays.**

**Comment by dsifford** [comment]
Sorry about that. The decision was made to drop support for the classic editor because of the amount of effort it would require to maintain both. And I make no money from my work on this plugin so reducing maintenance effort wherever I can was and remains a priority.
