### ISSUE TITLE
Open Links in New Window ("_blank")

### ISSUE THREAD

**Issue by ironmanavenger** [dsifford/academic-bloggers-toolkit#581]
Hi Derek, 
First of all, congratulations for this wonderful work! 

It's not an issue I think, just a question. Do you have anything already implemented to open links in a new window? I'm not finding it. If not, any ideas?

Best, 
Marcio

**Comment by dsifford** [comment]
Hi there.

This is not implemented currently, but it has been requested. I'm gonna close this issue in favor of the earlier issue (#560).
