### ISSUE TITLE
Crash after last update, 6 hours ago. 

### ISSUE THREAD

**Issue by ironmanavenger** [dsifford/academic-bloggers-toolkit#582]
I've just accepted the last update(published 6 hours ago according to wordpress.org) and nothing is working with the plugin active anymore. 

The error: [https://imgur.com/BqUaFZ8](url) 
Says "**The editor found an unexpected error**".
> render@https://mysite.com/br/wp-content/plugins/academic-bloggers-toolkit/bundle/editor.js?ver=4147b3b641bd0e2de06c389d6f0dd8f6:15:127817
Td@https://mysite.com/br/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:82:12
hi@https://mysite.com/br/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:102:387
Qg@https://mysite.com/br/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:144:219
Rg@https://mysite.com/br/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:145:78
Sc@https://mysite.com/br/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:158:111
Z@https://mysite.com/br/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:156:494
Kc@https://mysite.com/br/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:155:53
ya@https://mysite.com/br/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:153:161
enqueueSetState@https://mysite.com/br/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:202:411
https://mysite.com/br/wp-includes/js/dist/vendor/react.min.js?ver=16.8.4:20:448
value@https://mysite.com/br/wp-includes/js/dist/data.min.js?ver=4.4.0:1:16227
value@[native code]
https://mysite.com/br/wp-includes/js/dist/data.min.js?ver=4.4.0:1:16410
forEach@[native code]
n@https://mysite.com/br/wp-includes/js/dist/data.min.js?ver=4.4.0:1:11639
https://mysite.com/br/wp-includes/js/dist/data.min.js?ver=4.4.0:1:8808
v@https://mysite.com/br/wp-includes/js/dist/data.min.js?ver=4.4.0:1:29557
https://mysite.com/br/wp-includes/js/dist/data.min.js?ver=4.4.0:1:6308
https://mysite.com/br/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:9219
some@[native code]
e@https://mysite.com/br/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:5414
https://mysite.com/br/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:5364
promiseReactionJob@[native code]
> 
Please help on this. I've put a whole team of journalists to work using your plugin.

Best, 
Marcio

**Comment by dsifford** [comment]
Tied up at the moment until tomorrow afternoon, so I can't roll back until then.

In the meantime, you should be able to circumvent the problem by installing the `gutenberg` plugin temporarily.

I suspect the issue is due to my testing against a site with the Gutenberg plugin installed and there is clearly not feature parity between 5.2 and that plugin. Won't make that mistake again.

**Comment by vincenzo** [comment]
Just encountered this myself. 

```TypeError: Object(...) is not a function
    at render (https://www.mysite.com/wp-content/plugins/academic-bloggers-toolkit/bundle/editor.js?ver=4147b3b641bd0e2de06c389d6f0dd8f6:15:127817)
    at Td (https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:82:11)
    at hi (https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:102:385)
    at Qg (https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:144:217)
    at Rg (https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:145:76)
    at Sc (https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:158:109)
    at Z (https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:156:492)
    at Kc (https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:155:52)
    at ya (https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:153:159)
    at Object.enqueueSetState (https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:202:409)
```

**Comment by dsifford** [comment]
Ok just confirmed this has to do with unreleased features in Gutenberg that are slated to be released in WordPress 5.3.

The fix isn't worth pursuing since WordPress 5.3 is slated to be released in the next week or two. I'm just going to bump the required WordPress version up to 5.3 for this last release and advise anybody currently affected by this issue to either install the `gutenberg` plugin temporarily until 5.3 is released OR roll back to the last version until 5.3.

Sorry for the trouble!

**Comment by ironmanavenger** [comment]
Thank you Derek, it came back alive installing Gutenberg plugin as you said. 

The thing is: the references are not appearing on old posts. On the plugin it appears to be used (cited), but the text itself does not change. Is that a matter for another issue or you think it's a consequence of the same one?

**Comment by dsifford** [comment]
That seems strange. 

So, just to be clear, you're saying the inline citations and the bibliography in the post are gone? Or just the bibliography? Or just the citations?

**Comment by ironmanavenger** [comment]
With a text with no citations at all, if I try to include a new one, they both don't appear on the text. BUT, on the plugin they are identified as "CITED". I can even "Remove all citations" and they appear as "UNCITED". 

I'm trying to leave the text, logout wordpress, clear cache, come back in to see if it is just a rendering problem. But didn't appear yet.

**Comment by dsifford** [comment]
Hm, can you get a screen recording of this? Can't reproduce what you're describing on my end.

**Comment by NickG13** [comment]
Hi dsifford, will you upload the plugin so we can keep using it? I have the same problem OP said and it seems you said you would rollback it. Thanks

**Comment by vincenzo** [comment]
FYI, I decided to revert to 5.2.0, because I didn't want to install yet another plugin. Reverting also fixes the problem. I'll upgrade when WP5.3 is out.

**Comment by dsifford** [comment]
@NickG13 You can grab and install 5.2.0 from [this page](https://wordpress.org/plugins/academic-bloggers-toolkit/advanced/) or from [the releases page](https://github.com/dsifford/academic-bloggers-toolkit/releases/tag/v5.2.0) of this repository.

**Comment by NickG13** [comment]
> @NickG13 You can grab and install 5.2.0 from [this page](https://wordpress.org/plugins/academic-bloggers-toolkit/advanced/) or from [the releases page](https://github.com/dsifford/academic-bloggers-toolkit/releases/tag/v5.2.0) of this repository.

Sure mate, thanks! I'm a newbie in the wordpress world lol

**Comment by ironmanavenger** [comment]
> Hm, can you get a screen recording of this? Can't reproduce what you're describing on my end.

Hi Derek, 
I had to delete every entry of "_abt_state" meta data and **it all came back to normal** creating new ones.
