### ISSUE TITLE
Cannot edit pages or posts.

### ISSUE THREAD

**Issue by cwbullet** [dsifford/academic-bloggers-toolkit#583]
I have disabled all plugins and tied 4 themes.  If I try to create a post or page, I get an error:  "The editor has encountered an unexpected error."   

**ABT Version:**   5.2.1

**PHP Version:** 7.2

**Theme:** Panoramic but it fails with all 4 themes I have tried

**Plugin List:**
I have deactivated them all and it still fails.  

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**
Open the editor and instead I get the error:  The editor has encountered an unexpected error.

**Actual behavior:**
Error: The editor has encountered an unexpected error.

**Console messages:**

render@http://walkingoffpounds.com/wp-content/plugins/academic-bloggers-toolkit/bundle/editor.js?ver=4147b3b641bd0e2de06c389d6f0dd8f6:15:127817
Td@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:82:12
hi@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:102:387
Qg@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:144:219
Rg@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:145:78
Sc@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:158:111
Z@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:156:494
Kc@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:155:53
ya@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:153:161
enqueueSetState@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react-dom.min.js:202:411
https://c0.wp.com/c/5.2.4/wp-includes/js/dist/vendor/react.min.js:20:448
value@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/data.min.js:1:16227
value@[native code]
https://c0.wp.com/c/5.2.4/wp-includes/js/dist/data.min.js:1:16410
forEach@[native code]
n@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/data.min.js:1:11639
https://c0.wp.com/c/5.2.4/wp-includes/js/dist/data.min.js:1:8808
v@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/data.min.js:1:29557
https://c0.wp.com/c/5.2.4/wp-includes/js/dist/data.min.js:1:6308
https://c0.wp.com/c/5.2.4/wp-includes/js/dist/redux-routine.min.js:1:9219
some@[native code]
e@https://c0.wp.com/c/5.2.4/wp-includes/js/dist/redux-routine.min.js:1:5414
https://c0.wp.com/c/5.2.4/wp-includes/js/dist/redux-routine.min.js:1:5364
promiseReactionJob@[native code]
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Yep, sorry about that. 

See [here](https://github.com/dsifford/academic-bloggers-toolkit/issues/582#issuecomment-546127553) for more info.

Closing in favor of #582
