### ISSUE TITLE
5.2.1 update seems to break Gutenberg

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#585]
**ABT Version:**  5.2.1

**PHP Version:**  7.3.9

**Theme:** GeneratePress, also tried Twenty Nineteen

**Plugin List:**
Tried with only ABT active

**Browser:** Firefox 69.0.1

**Expected behavior:** Gutenberg works

**Actual behavior:** When I go to edit a page with block editor, I get "The editor has encountered an unexpected error"
![Screen Shot 2019-10-26 at 8 32 27 AM](https://user-images.githubusercontent.com/6004417/67622139-1e954980-f7cc-11e9-820b-865f2eb12f47.png)

Classic editor still works.  Using Health Check plugin, with all plugins off and 2019 theme, block editor works.  Activating only ABT breaks it.

Copied error is
render@https://forestpathology.org/wp-content/plugins/academic-bloggers-toolkit/bundle/editor.js?ver=4147b3b641bd0e2de06c389d6f0dd8f6:15:127817
Td@https://forestpathology.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:82:11
hi@https://forestpathology.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:102:385
Qg@https://forestpathology.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:144:217
Rg@https://forestpathology.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:145:76
Sc@https://forestpathology.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:158:109
Z@https://forestpathology.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:156:492
Kc@https://forestpathology.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:155:52
ya@https://forestpathology.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:153:159
enqueueSetState@https://forestpathology.org/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.8.4:202:409
t.prototype.setState@https://forestpathology.org/wp-includes/js/dist/vendor/react.min.js?ver=16.8.4:20:433
value@https://forestpathology.org/wp-includes/js/dist/data.min.js?ver=4.4.0:1:16219
value/this.unsubscribe<@https://forestpathology.org/wp-includes/js/dist/data.min.js?ver=4.4.0:1:16397
n/<@https://forestpathology.org/wp-includes/js/dist/data.min.js?ver=4.4.0:1:11659
n@https://forestpathology.org/wp-includes/js/dist/data.min.js?ver=4.4.0:1:11632
m/y</<@https://forestpathology.org/wp-includes/js/dist/data.min.js?ver=4.4.0:1:8807
v@https://forestpathology.org/wp-includes/js/dist/data.min.js?ver=4.4.0:1:29557
b/</<@https://forestpathology.org/wp-includes/js/dist/data.min.js?ver=4.4.0:1:5879
O/</</<@https://forestpathology.org/wp-includes/js/dist/data.min.js?ver=4.4.0:1:6307
a/</</<@https://forestpathology.org/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:9567
dispatch@https://forestpathology.org/wp-includes/js/dist/data.min.js?ver=4.4.0:1:32017
i/<@https://forestpathology.org/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:9218
e/<@https://forestpathology.org/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:5434
e@https://forestpathology.org/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:5410
o/<@https://forestpathology.org/wp-includes/js/dist/redux-routine.min.js?ver=3.2.0:1:5363

**Console messages:**
```js
// Paste messages here
JQMIGRATE: Migrate is installed, version 1.4.1 load-scripts.php:8:552
onmozfullscreenchange is deprecated. components.min.js:12:80764
onmozfullscreenerror is deprecated. components.min.js:12:80764
TypeError: "Object(...) is not a function"
    render sidebar.tsx:18
    Td react-dom.min.js:82
    hi react-dom.min.js:102
    Qg react-dom.min.js:144
    Rg react-dom.min.js:145
    Sc react-dom.min.js:158
    Z react-dom.min.js:156
    Kc react-dom.min.js:155
    ya react-dom.min.js:153
    enqueueSetState react-dom.min.js:202
    setState react.min.js:20
    value data.min.js:1
    unsubscribe data.min.js:1
    n data.min.js:1
    n data.min.js:1
    y data.min.js:1
    v data.min.js:1
    b data.min.js:1
    O data.min.js:1
    a Redux
    dispatch data.min.js:1
    Redux 4
react-dom.min.js:117:150

​

```

**Comment by dsifford** [comment]
See #582
