### ISSUE TITLE
Citations and refs all there, but ABT sidebar shows no refs cited - all lost on adding new cite

### ISSUE THREAD

**Issue by glorious1** [dsifford/academic-bloggers-toolkit#587]
**ABT Version:** 5.2.0

**PHP Version:** 

**Theme:**GeneratePress and Twenty Nineteen

**Plugin List:** Did it with Troubleshooting - no other plugins

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:** Old citations still intact, then can add new ones.

**Actual behavior:** Revisiting an older page, I found the citations and references (24 of them) were all good, and the page looks perfect on front end.  However, the ABT reference list in sidebar shows them all as uncited.  When I add a citation, all the other citations convert to [NO_PRINTED FORM] and those refs are lost from the bibliography at bottom.  I have many pages to maintain, and am very afraid if I have to redo all the citations every time I go back to edit a page.

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Yikes.

How old is this "older" page? Is it any post that has been saved and revisited or only posts that are literally old?

Have these older posts been converted to block form?

**Comment by dsifford** [comment]
Re: `NO_PRINTED_FORM` -- that generally happens when the citation style doesn't specify (or incorrectly specifies) inline citations. Have you tried a different style? Are you using a custom style?

**Comment by glorious1** [comment]
This page was first published 2017, but was converted to blocks at some point, and I recall having to redo all the citations in it once or twice.  The last time it was edited was 4 days ago, but no changes to references (except for copying and pasting text with citations).

The last time I made reference changes was May of this year.

This is a custom style, but normally it has worked fine.  I just switched to a standard one and NO_PRINTED_FORM is there where citations should be, but of course all the references are in the Uncited section.

**Comment by dsifford** [comment]
> (except for copying and pasting text with citations)

Can you explain what you mean by this?

**Comment by glorious1** [comment]
It means that while editing 4 days ago, I copied (or cut) some text that included inline citations, and pasted it elsewhere in the page.  Is that a no-no?

**Comment by dsifford** [comment]
That's a big, big no-no. (see [here](https://github.com/dsifford/academic-bloggers-toolkit/wiki#changing-citation-number-or-position))

Sorry for not being more clear about this. Open to suggestions as to how I can make that more clear.

**Comment by dsifford** [comment]
The gist of this issue is that the processor keeps track of each group of citations specifically by their unique identifier. If you copy/paste, you'll be duplicating identifiers in the code that are supposed to be unique. Once a citation containing that unique identifier is adjusted, if the processor comes across a citation with the same identifier again, it'll freak out.

**Comment by glorious1** [comment]
That’s pretty damn clear in the guide.  Guess I never read it or more likely forgot.

So even cut and paste is bad I guess.  Have to delete the citations first, then reinsert after moving the text.

There’s other weird stuff.  These messed up pages have some random citation style showing when I go to Change Citation Style, although they are still using the correct style.

Some pages are fine, others have just one citation that is in the Uncited instead of Cited group, another has no references in either Cited or Uncited, though it still has the citations in text and reference list below.

I’m prepared to believe that this is all due to moving text with citations around, and will certainly avoid that in future.  Thanks!

**Comment by dsifford** [comment]
Cut and paste should theoretically be fine. But if you can avoid it, that would probably be the safest bet.

Re: the cited/uncited weirdness -- those lists also use the unique identifier to determine which are cited or not so, like you suggested, that might be also due to the copy/paste issue.
