### ISSUE TITLE
Unable to add more than one citation to a post

### ISSUE THREAD

**Issue by devinberg** [dsifford/academic-bloggers-toolkit#589]
**ABT Version:** 5.2.2

**PHP Version:** 7.2

**Theme:** GivingPress Lite

**Plugin List:**
- Jetpack
- Akismet
- Stripe Payments
- WP Super Cache
- WPForms Lite

**Browser:** Firefox (Version: 70.0.1)

**Expected behavior:** Add references to a blog post.

**Actual behavior:** I was able to add one reference. Upon trying to add a second, clicking the "Insert citation" button would move the reference from "Uncited Items" to "Cited Items", but would not insert any in-text citation or add the reference to the bibliography. If I select the area in the text where the citation was inserted and delete it, the reference moves back from "Cited Items" to "Uncited Items". 

**Console messages:**
```js
uncaught exception: citeproc-js error: Citation with previously referenced citationID 62c0bf42-9d93-4ee3-bd19-8ee7827fdc08

```

**Comment by dsifford** [comment]
Looks like there's a conflict happening somewhere in the post due to the a unique citation identifier being used more than once.

Did you by chance copy and paste citations around in the post in question?

Does this happen on a brand new post?

**Comment by devinberg** [comment]
This was on a new post, I hadn't done anything in terms of copying/pasting citations or moving anything around. I just tried creating a new, unrelated post and was able to add two citations without issue.

I went back now and started the original post from scratch and was able to add the citations that I originally had tried.

My guess as to the issue is: I had auto added one citation by DOI. Then I wrote a little more text and tried to add a second citation, again via DOI. The import of that second citation was missing some info so I removed it and had to add it manually to fill in the missing info. Perhaps adding the citation manually somehow used the same identifier as the one I had tried to create automatically.

**Comment by dsifford** [comment]
> The import of that second citation was missing some info so I removed it and had to add it manually to fill in the missing info. Perhaps adding the citation manually somehow used the same identifier as the one I had tried to create automatically.

Can you describe a little more how you went about doing this? Just want to make sure the UX doesn't have any pain points that need adjusting and/or the instructions are clear enough.

**Comment by devinberg** [comment]
Basically (from what I can remember), I created the citation by DOI, but the automatically imported data was missing information. So I deleted that one using the (-) button. Then I went to manually add the reference back in and started getting the error. I've tried recreating the issue on a new post, but haven't been able to do so. Sorry I'm not being very helpful. Perhaps it was more of a one-time fluke.

**Comment by dsifford** [comment]
Hmm.. Very strange indeed.

Yeah, it'll be tough to debug without being able to reliably reproduce. I suppose we can just call this a fluke for now. If you're able to get this to happen more reliably, reopen this issue and we'll go from there. 

Sorry for the trouble! Thanks for the info nevertheless.
