### ISSUE TITLE
Inconsistency with reference button

### ISSUE THREAD

**Issue by Moritz-Pfeifer** [dsifford/academic-bloggers-toolkit#591]
**ABT Version:** Version 4.13.3 (but tried on newest version as well) 

**PHP Version:** 7.2.

**Theme:** Amory 

**Plugin List:**
Advanced Floating Content
Akismet Anti-Spam
Classic Editor
Column Shortcodes
Custom 
Permalinks
Custom Sidebars
DK PDF
Drop Caps
Easy Social Share Buttons for WordPress
Essential Grid
Font Awesome
Formidable Forms
Formidable Forms Pro
Formidable Locations
Formidable PayPal Standard
GDPR Cookie Consent
HTML in Category Descriptions
JC Submenu
Max Mega Menu
Max Mega Menu - Pro Addon
MC4WP: Mailchimp for WordPress
MonsterInsights Pro
Secondary 
Title
Slider Revolution
Sticky Menu (or Anything!) on Scroll
UpdraftPlus - Backup/Restore
Widget CSS Classes
Widget Title Links
WordPress HTTPS
WP Gallery Custom Links

**Browser:** Google Chrome (Version: Version 77.0.3865.120 (Official Build) (64-bit))

Reference button should look like this: https://eefb.org/retrospectives/vera-chytilovas-ceiling-strop-1961/

**Actual behavior:**
But is missing on some newer pages: https://eefb.org/retrospectives/kira-muratovas-long-farewells-dolgie-provody-1971/

I have no idea why. 

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Did you enable "toggle" mode in the bibliography settings sidebar? You must do that in every new post now. That change was made when the plugin updated to support the gutenberg editor.

**Comment by Moritz-Pfeifer** [comment]
Hi Darek! Thanks for the quick reply; You mean the pin icon? I enabled it,
but it just makes the sidebar sticky for the time that I'm in the post
editor. Or perhaps you mean something else?


Collège universitaire
Campus européen franco-allemand
94, avenue du Maréchal de Lattre de Tassigny 54000 Nancy
T. +33 (0)6 02 30 17 24
moritz.pfeifer@sciencespo.fr <francois.laval@sciencespo.fr>
http://college.sciences-po.fr/sitenancy
[image: Twitter Sciences Po] <https://twitter.com/sciencespo> [image: Logo
Facebook] <https://www.facebook.com/scpo.campus.nancy> [image: LinkedIn
Sciences Po] <https://www.linkedin.com/edu/school?id=12454>

**Comment by dsifford** [comment]
Yep, sorry I meant something a little different.

Assuming you have the latest version of the plugin installed and you're working on a post in the new editor, do the following...

1. Click into the references block so it's highlighted.
2. Click the little gear icon in the top right of the screen to show the block settings sidebar.
3. Click "enable toggle" in the settings.

Let me know if that works for you.

**Comment by Moritz-Pfeifer** [comment]
Hi Derek! Hm, I don't have the latest version. I'm using version 4.13.3 When I update to the latest version, however, the reference sidebar disappears from my backend. Although when I looks at the source code the toolkit should be there and my browser seems to find it via ctrl+s as well (veeeeery strange). I have no idea why it's invisible. Maybe it's a compatibility issue? 

That said, in the older version I don't see any gear icon. When was it implemented?

**Comment by Moritz-Pfeifer** [comment]
Checked version 5.2.0 as well and the invisibility issue is the same /-:

**Comment by dsifford** [comment]
The latest version is only compatible with the new editor. ☹️

**Comment by Moritz-Pfeifer** [comment]
The Gutenberg editor?

**Comment by Moritz-Pfeifer** [comment]
But even there I can't see the reference sidebar...

**Comment by dsifford** [comment]
The reference sidebar is only available when a bibliography is selected. It's the sidebar that shows when the sidebar with the gear icon is active.

**Comment by Moritz-Pfeifer** [comment]
Hm, I don't know if it's me. But I can neither select my bibliography nor is their an inactive or active sidebar. Check the screenshot. https://ibb.co/0ZnNRfS It simply looks like the plugin has disappeared...

**Comment by dsifford** [comment]
Looks like you're using the old editor. I dropped support for the classic editor a few versions ago.

**Comment by Moritz-Pfeifer** [comment]
Ah, ok, you mean instead of the block editor? Yes, that seems to be the issue then. Well I can't really switch but that's a problem that you can't solve then. Anyway, thanks for letting me know where the problem lies! Cheers

**Comment by Moritz-Pfeifer** [comment]
Although, no I switched to block editor and I still can't see the sidebar!

**Comment by Moritz-Pfeifer** [comment]
Last question: does that mean that when I switch to Block Posts that I have to rework all older posts w/r/t the toggle function?

**Comment by dsifford** [comment]
Nope. If you use the "convert to blocks" functionality, it'll set the proper options smartly based on your historic settings.

**Comment by Moritz-Pfeifer** [comment]
Yes, got it! Thanks for the clarifications!
