### ISSUE TITLE
Some Menu Icons and Function are Missing

### ISSUE THREAD

**Issue by janos-farkas** [dsifford/academic-bloggers-toolkit#592]
**ABT Version:** 
5.2.2

**PHP Version:** 
7.13.12

**Theme:**
Tewentytwenty

**Plugin List:**
- ABT only

To see and use 1.d,e 2a,d 3. 5 as shown at https://github.com/dsifford/academic-bloggers-toolkit/wiki#visual-aids

Listed items are not visible

**Console messages:**
```js

load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.3:8 JQMIGRATE: Migrate is installed, version 1.4.1
```

**Comment by dsifford** [comment]
I've unfortunately been slow to get the docs in the wiki caught up. The fields detailed there reference the menu icons/functions in the old sidebar that we had when we supported the classic editor.

There's been no decrease in features since then though. Can you tell me what you're looking for? I'll try to point you in the right direction.

**Comment by janos-farkas** [comment]
Here are the features I have not been to use
1. Add References using ISBN number
2. Insert Footnote. (Do not see an icon in the block editor to do it)

Yet to test importing references.

**Comment by dsifford** [comment]
1. Click add reference (the same as you would for adding by DOI, PMID, etc). Then click add manually and select "book" or "chapter". Then you should be able to import by ISBN.
2. With your cursor in a block, there should be an icon in the same menu that "bold" and "italics" is. It might be buried in a collapsed list.

**Comment by janos-farkas** [comment]
1. >> Thank you for clarifying it, was expecting it in the same menu as DOI/PMID/PMCID.
2. >> Do not see the icon you are referring to, neither see "bold" and "italics" (this is the only block missing those). I see only two icons for: "Changing block type or style" and "More Options".

**Comment by dsifford** [comment]
For 2, it's not in the sidebar. It should be in the main editing toolbar. Where bold, italics, hyperlinks, etc is.

**Comment by janos-farkas** [comment]
That is where I am looking at, the block specific to this plugin, correct? 

Other blocks like Heading, Paragraph, Group blocks have multiple icons including bold, italics, hyperlink. 

In the block used by the plugin, I see only the two I've mentioned.

**Comment by dsifford** [comment]
Nope, the footnote functionality is in the same area as the bold, hyperlink, etc.

**Comment by janos-farkas** [comment]
This is what I see with the block the plugin is using [https://i.imgur.com/SYClTv5.png](url)
This is what I see with a standard paragraph block of WP [https://i.imgur.com/uqmy5mP.png](url)

**Comment by dsifford** [comment]
In the second image, see the little down arrow? Click that and it should be there.

**Comment by janos-farkas** [comment]
Thank you, that makes sense since footnotes should be added from the content.

Re: 1 >> I tried adding references form  ISBN described above (click add manually and select "book" ) and was not able to do it. tried both 10 and 13 characters ISBN's eg. 892559837X; 978-8925598376. What am I missing?

**Comment by dsifford** [comment]
That uses the Google Books API and unfortunately not all books are indexed. It's generally pretty hit or miss. 

So in that case, you'd just have to fill out the form manually.

**Comment by janos-farkas** [comment]
Thank you for clarifying it. That also explains to me why this function is under manual entry and not with the DOI/PMID/PMCID menu.
Tried the import both with RIS and BibTex, both of those worked seamlessly.

Derek, your plug-in is FANTASTIC. Congratulations and thank you!
