### ISSUE TITLE
How do you reference a web page that lists no author?

### ISSUE THREAD

**Issue by janos-farkas** [dsifford/academic-bloggers-toolkit#593]
**ABT Version:** 
5.2.2

**PHP Version:** 
7.3.12

**Theme:**
Twentytwenty

**Plugin List:**
- ABT only

**Expected behavior:**
Allow the use of citation without mandating the entry of the author field, since the selected citation style supports that: [https://apastyle.apa.org/learn/faqs/web-page-no-author](url)

**Actual behavior:**
The plugin does not allow to create a citation without Author who is not known,( like a lot of web pages) even the citation style supports that e.g. American Psychological Association 6th edition

!-- Open your javascript console on the affected pages by pressing F12 and paste any errors/messages below -->
**Console messages:**
```js

load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.3:8 JQMIGRATE: Migrate is installed, version 1.4.1
```
```

**Comment by dsifford** [comment]
You should be able to do that if you simply click the `x` next to the blank author boxes. That will delete the input fields for the author name and allow you to submit.

**Comment by janos-farkas** [comment]
Thank you, that worked.
