### ISSUE TITLE
The hamburger and pin button does not show

### ISSUE THREAD

**Issue by mguba** [dsifford/academic-bloggers-toolkit#600]
Hi Derek
I am obviously not a pro and cannot find all the requested information. The dynamic bibliography wprks well the static not I cannot find the pin and hamburger button on the manu. I am currently using the squaretype theme

Version 5.2.2
--

**ABT Version:** 

7.3.13
--

**Theme:**

**Plugin List:**
- Plugin 1
- Plugin 2

**Browser:** Google Chrome (Version: xxx)

**Expected behavior:**

**Actual behavior:**

**Console messages:**
```js
// Paste messages here

```

**Comment by dsifford** [comment]
Hi there. Sorry about that. I've been super neglectful in updating the docs as I've been extremely busy with my day job as of recently.

It sounds like you're just wondering how to accomplish the "static bibliography" functionality. 

That functionality has been converted into a WordPress block. Simply open up the blocks menu and search for the word "static" and you should be able to locate it.

**Comment by jlmgarvayo** [comment]
I have a similar problem. The issue is that the buttons (hamburger and pin) don´t appear at all. 

Attached I send an image of the WordPress editor

![Imagen1](https://user-images.githubusercontent.com/60145913/72818335-98be5880-3c6b-11ea-86fb-53a2fc54070d.jpg)

Thanks in advance for your help

**Comment by dsifford** [comment]
@jlmgarvayo Hamburger and pin buttons have been removed since supporting the new editor. What functionality were you looking for?

**Comment by jlmgarvayo** [comment]
@dsifford, thank you for your rapid response.
I'm trying to cite a reference, but without the "Insert Selected References" button I don't know how to do it.

**Comment by dsifford** [comment]
@jlmgarvayo No worries... The insert references button will show up when you have your cursor in a block that is able to accept a citation (so generally speaking, that means any "regular text" block -- text, table, etc).

**Comment by jlmgarvayo** [comment]
Oh, I understand. I've been doing a lot of proofs but in other types of blocks. Thanks a lot!
