### ISSUE TITLE
Plugin is not visible on post edit screen

### ISSUE THREAD

**Issue by adsii1970** [dsifford/academic-bloggers-toolkit#602]
**ABT Version:** 5.2.2

**PHP Version:** 7.3.13

**Theme:** Coraline. I have not had any conflicts with this plugin until the last update. 

**Plugin List:**
-  Academic Blogger's Toolkit
-  Akismet Anti-Spam
- Classic Editor
- Custom Link Widget
- Custom Meta Widget
- Custom Post Limits
- Custom Twitter Feeds
- Disqus for WordPress
- Eonet Manual User Approve
- Facebook Comments Plugin
- Genie WP Favicon
- Google Fonts Typography
- Jetpack by WordPress.com
- Simple Login Captcha
- WP About Author
- WP User Avatar
- Yoast SEO

**Expected behavior:** In previous versions, the plugin's interface was on the upper right corner of the screen. Now, it does not appear anywhere on the new post or edit post page. I cannot enter sources in at all.

**Actual behavior:** The user interface to input the references is not available on the edit post screen.

**Console messages:**
```js
//This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. post.php
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:552
downloadable font: no supported format found (font-family: "jetpack" style:normal weight:400 stretch:100 src index:1) source: (end of source list)
downloadable font: no supported format found (font-family: "Noticons" style:normal weight:400 stretch:100 src index:1) source: (end of source list)
bootstrap-slider.js - WARNING: $.fn.slider namespace is already bound. Use the $.fn.bootstrapSlider namespace instead. eonet_admin.min.js:1:55503
Deprecated TinyMCE API call: <target>.onNodeChange.add(..) plugin.min.js:1:90
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. tinymce.min.js:2:9108
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! post.php
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. tinymce.min.js:2:9108
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://7b60195e-dd12-47e0-b64e-09c2410b4fe3/0.js
Source Map URL: 0.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://7b60195e-dd12-47e0-b64e-09c2410b4fe3/1.js
Source Map URL: 1.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://7b60195e-dd12-47e0-b64e-09c2410b4fe3/inject.js
Source Map URL: inject.js.map
```

**Comment by dsifford** [comment]
Support for the classic editor was dropped several releases ago, unfortunately. Sorry about that, but just don't have the bandwidth to support both! :(

**Comment by adsii1970** [comment]
Yes, I discovered that was the issue about an hour after I reported it. Thanks for the help anyway. 

And I hate the “new” interface.  (grumble, grumble)

 

Thanks for the quick response.
