### ISSUE TITLE
Jump to reference at the end

### ISSUE THREAD

**Issue by someonehere15** [dsifford/academic-bloggers-toolkit#61]
Could you add anchors or similar to the references, so that when an inline citation is clicked, it jumps right at the full reference at the end of the post?

**Comment by dsifford** [comment]
I opted for tooltips, rather than anchors for this because I feel like jumping to a reference interrupts the flow of the person's reading. 

Question: What do you think the benefit of anchors is over tooltips? In my mind, the tooltip shows you the full reference, with clickable links, so there really isn't a downside.

When the person is done and he/she wants to export the reference, then he/she can scroll to the bottom and do it. (They'll be at the bottom when they're done reading anyway!)

**Comment by someonehere15** [comment]
Well, as I wrote on the other thread, tooltips may not work on every theme, and besides, IE may be problematic, not saying I found any bugs now, but just in general. and having the possibility to jump at the end for thos who want to may be a compatible alternative.

**Comment by dsifford** [comment]
Unfortunately, there really isn't a way to get this to work both ways. On mobile, I need to have the "touch" event free for rendering tooltips. 

To clarify: On IE, there is most definitely an issue rendering tooltips. However, I don't believe it is worth the hassle to work harder for people who prefer a worse browsing experience at baseline. If they enjoy the hassle of browsing with IE, they can have the added hassle of scrolling down to the bottom to view references (IMHO).

Microsoft is currently phasing IE out of existence (in favor of edge). So there really is no point in building in tons and tons of polyfills for a browser that's on it's deathbed. 

Re: theme conflicts -- Not sure why there is one with the theme you mentioned. I suppose I'll have to look into it. But really, like I said before, all a tooltip is is a DIV element rendered on the fly, with absolute position, placed above or below the citation. When you scroll away, it's destroyed from the page. 

There's a good chance that the customizer theme people just wen't too crazy with their `z-index` css (something I'd have no control over).

You might be able to try adjusting your tooltips css to include `z-index: 1000000000000;` and see if that helps.

**Comment by dsifford** [comment]
Closing this for now. Feel free to reopen if you think there's more to be discussed.
