### ISSUE TITLE
footnote popup

### ISSUE THREAD

**Issue by tosokuzma2020** [dsifford/academic-bloggers-toolkit#612]
Hello there!

Hope you're all well :>

I'm an avid fan of ABT and am still using it even after WP switched to Blocks (yay!). Lately, I've realized that I'm experiencing a minor issue though: I realized that in recent posts the footnotes are not accessible via popups anymore. In old posts, you could just hover over a footnote and it would show the hyperlinked content.

See this old post for a footnote (in paragraph 1) over which you can just hover to access content:
https://eefb.org/retrospectives/the-philosophical-farce-of-daisies/

See this newer post for a footnote (in paragraph 1) where hovering does NOT display the footnote content:
https://eefb.org/retrospectives/vladimir-motyls-the-white-sun-of-the-desert-beloye-solntse-pustyni-1970/

Thank you, and stay safe!

WP 5.4.1 (Block Editor), ABT 5.2.2

**Comment by tosokuzma2020** [comment]
Oh haha I guess my question is if you know what the problem could be?

**Comment by dsifford** [comment]
Footnotes were separated from citations when the plugin was updated for the block editor due to it being too difficult to deal with those two types of things simultaneously. Functionality for hover I believe was removed at that time too for footnotes specifically.

**Comment by tosokuzma2020** [comment]
Hey there, thank you for your reply! I am sorry but I think I expressed myself wrongly: I actually did mean **citations rather than footnotes** (I keep confusing the two, but I am aware of both functions as I used to work with the footnote function for a short while, but have managed to revert to the citation function). In both posts I posted above, the citations were added through the regular reference link function and are visible in the ABT window as cited items (see image below). So they're not footnotes, but citations, and yet the hyperlink/hover does not seem to work. Do you have any idea what the issue could be?

![image](https://user-images.githubusercontent.com/60691956/82899195-d8b78400-9f5a-11ea-93f2-f3cda1789d0e.png)

**Comment by dsifford** [comment]
I notice in your screenshot you're using the old editor. I'm unable to provide any guidance to inconsistencies or bugs related to the old editor because support was dropped several releases ago for that editor.

**Comment by tosokuzma2020** [comment]
Wow I see, I didn't even know we were using the old editor! I am going to look into that, thanks!!
