### ISSUE TITLE
Duplicate a Reference

### ISSUE THREAD

**Issue by sid-khullar** [dsifford/academic-bloggers-toolkit#616]
Sometimes, especially in the case of books, one has multiple references from multiple chapters and a lot of the same book information needs to be entered repeatedly. It would be nice if we could duplicate a reference and then edit the required parts.

BTW: If you need help maintaining this brilliant tool, I'm happy to help however I can. Please mail me at siddhartha.khullar@gmail.com

**Comment by glorious1** [comment]
For that kind of work, I think you are better off preparing the references in Zotero, then export as RIS and import into ABT.  Zotero allows duplication and is much easier to edit in.

**Comment by sid-khullar** [comment]
Thank you.
