### ISSUE TITLE
Tooltip not showing with Customizr

### ISSUE THREAD

**Issue by someonehere15** [dsifford/academic-bloggers-toolkit#62]
I tried to use the Customizr theme, and noticed that the ABT tooltips do not show up with that.
Based on [this link](https://gist.github.com/eri-trabiccolo/76efe3633e44ed75105b) which enables tooltips for another plugin with Customizr (because it uses Bootstrap and conflicts witht its own tooltip), I modified it for ABT:
```
function re_enqueue_abt_script() {
// first dequeue it        
wp_dequeue_script('abt_frontend_js');
// enqueue it after tc-scripts
wp_enqueue_script('abt_frontend_js', plugins_url('academic-bloggers-toolkit/lib/js/Frontend.js'), array('tc-scripts') );
}
add_action( 'wp_print_scripts', 're_enqueue_abt_script', 100 );
```
It doesn't seem to work however. Any chance you could help me out?

**Comment by dsifford** [comment]
Not totally sure. What I do know is that `wp_print_scripts` has been depreciated since WordPress 3.3, so that might be some of the issue.

Tooltips for this plugin are just HTML elements created and destroyed on the fly. There really shouldn't be any reason why they shouldn't work.

Perhaps send a screenshot? Also, (if you're on chrome or firefox) press F12 and copy and paste any errors in the "console" if they exist.

**Comment by someonehere15** [comment]
Yes, you are right about `wp_print_scripts`, did not check. I did however just try with `wp_enqueue_scripts` and still nothing. I can send you a screenshot but basically nothing happens nor changes, on the console also nothing.

**Comment by dsifford** [comment]
What led you to that code snippet? I imagine this is an indication that other people have had issues with the theme as well? Have you tried contacting the customizr theme people and filing an issue there?

**Comment by someonehere15** [comment]
I could only find one question about it, [here](http://presscustomizr.com/support-forums/topic/jquery-tooltips-suppressed/). I cannot contact them on their forum because that is only for pro users, and I don't have that yet.
I was hoping to fix it myself but the solution there doesn't work for me.

**Comment by dsifford** [comment]
Ah, I see..

Yeah I'm not using any external plugins (eg. jQuery) with my plugin. It's all done in vanilla JS, so you shouldn't be having the issue that the person on that forum was having. 

In other words, it shouldn't matter what order this is loaded for it to work correctly. 

My guess is they wen't crazy with their `z-index`. I'll look into this more later and see if that's the case.

**Comment by someonehere15** [comment]
Hey, you were right. I just added the z-index to the tooltip class of ABT and it worked perfectly. Thanks a lot.

**Comment by dsifford** [comment]
Awesome. I think I'll bump up what I have set for my z-index so that these sorts of issues don't happen as often. I tried to keep it reasonable because there are some circumstances when you need stuff above the tooltip (eg, alert modals, etc).
