### ISSUE TITLE
Conference proceedings bug

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#63]
Just entered by first reference to a conference and it did not seem to parse the location and date that I manually entered. The reference is there, with the title and author. And the tool tip shows fine. But they are both just missing the date and location.

**Comment by dsifford** [comment]
Can you give me the details on what exactly you entered and for what citation type?

**Comment by metallikat36** [comment]
Try inputting the following reference as a Conference Proceeding:

International Conference on AIDS: Magnesium Level and Peripheral Neuropathy; S. Stroud, et al.; August 1994

**Comment by metallikat36** [comment]
Make up anything for the Location field.

**Comment by dsifford** [comment]
Which citation style?

**Comment by metallikat36** [comment]
Oh wow that's a lot of options. I have Academy of Management Review selected by default and have been using that. I noted that bug with that. Haven't tried with another style. My site is medical related so maybe I should have been selecting something else like American Medical Association for all my citations.

**Comment by dsifford** [comment]
Yep, give another one a shot and let me know... 

Some popular ones would be AMA (as you mentioned), nature, bmj, critical care, harvard, etc.

Once you find one you like, you can set it as the default on the options page

**Comment by metallikat36** [comment]
I tried AMA and the reference to a Conference Proceeding only shows the author and the content name. It is missing the name of the conference, the location, and that date. So AMA style is actually missing more information than the Academy of Management Review style is missing.

**Comment by metallikat36** [comment]
Just wanted to let you know I wrote my first real referenced article with your plugin, and it works like a charm:
http://www.earthmedresearch.org/neuropathy-natural-medicine/
The plugin is probably the single most irreplaceable component of my website.

Thank you...

**Comment by dsifford** [comment]
> I tried AMA and the reference to a Conference Proceeding only shows the author and the content name. It is missing the name of the conference, the location, and that date.

Do you know for sure that AMA format uses those fields for conference preceeding citations? (I'm not familiar, so just making sure). I do know that there are going to be a bunch of scenarios where there are more fields than needed for some citation types. Had to include all of the fields I could possibly think of so that it works across the board.

If you're certain that it should be there with AMA, then yeah it might be a bug. Thanks for letting me know. (please clarify!)

> The plugin is probably the single most irreplaceable component of my website.

Thanks for the complement! Glad the plugin is getting good use! Probably couldn't have made it as awesome as it is without your stellar feedback! 👍

**Comment by metallikat36** [comment]
I actually don't know the answer for sure. Though this link seems to suggest that location and date should be there when citing a conference presentation AMA style:
http://blogs.library.ucla.edu/biomedical/2011/10/26/cite-it-right-citing/

**Comment by dsifford** [comment]
Hmm.. Good to know. Not sure either. 

I'll mark this as a bug for now and check it out when I get some time. 👍 

Thanks for letting me know.

**Comment by dsifford** [comment]
@metallikat36 Fixed. It was indeed a bug. Good catch. 

Pushing out with the giant update sometime within the next few days
