### ISSUE TITLE
Consider Putting References List at bottom of sidebar

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#64]
Right now the references list is at the top of the sidebar in the Editor screen. Say I am adding some text at the bottom of an article. Then I want to insert a reference. I have to scroll to the top of the screen to reach the button to add a reference. If the References List was the bottom item rather than the top item, that might save users some scrolling up and down.

**Comment by dsifford** [comment]
You are able to move that with your mouse to wherever you'd like on the sidebar. Just click and drag.

**Comment by metallikat36** [comment]
Oh duh..Thanks.
