### ISSUE TITLE
Use with custom post types?

### ISSUE THREAD

**Issue by halatkins** [dsifford/academic-bloggers-toolkit#66]
We're using custom post types to organize article types for our journal (research, news, editorial, etc.). How do I get each of these custom post types to show the reference list in the editor?

**Comment by dsifford** [comment]
Interesting. That's not something I thought of. I'll see if I can add support for that on the next update. 👍

**Comment by halatkins** [comment]
Awesome! I'm testing your work out on a beta installation of our journal. Really, really impressed - and glad that you've come up with this.

**Comment by dsifford** [comment]
Sweet!

There's still a lot of work yet to be done. I'm working on a major update that will allow for the in-text citations to be correctly aligned with the chosen style. (right now it simply inserts a range of citation numbers surrounded by brackets).

Stay tuned.

**Comment by halatkins** [comment]
So a general question - is anything stored in the post database? I see that it writes the references to the post as nice and tidy HTML - but are you storing any of the DOIs or PMiDs in the post_meta?

**Comment by dsifford** [comment]
Not yet. The next update will require a single write to the database though. It'll be a JSON-encoded hidden field that will represent the current application "state" the moment the page was saved. That way you'll be able to come back and adjust citations at a later time without the processor state getting out of sync with the document.

The current version is completely stateless. This is the ideal scenario, but unfortunately it's not possible to keep it stateless with robust in-text citation processing.

**Comment by halatkins** [comment]
Understood (mostly). I was just wondering if there would be some means of integrating a custom field - we are moving toward importing our articles from XML. Most of the front matter will get imported into custom fields - and I've been trying to think of a good solution for the back matter - then I happened upon your work.

**Comment by dsifford** [comment]
Not super familiar with how your system works. Can you describe it in greater detail? What would the custom field be for exactly?

**Comment by halatkins** [comment]
Here's the basic workflow that we are working toward. The article, in its final form, is converted to JATS XML. From that XML, we can will produce a formatted PDF, metadata for repositories such as CrossRef and PubMed, deposit into PubMed Central - and finally (via an XML transform), and XML file that can get imported into Wordpress.

The XML that gets imported in to Wordpress will go in to several custom fields - all sorts of front matter elements such as author list, affiliations, title, DOI, etc., the article body, and then custom fields for back matter. The working principle I was starting to work from was to import each reference from the XML in to a repeating custom field. Given your work on this plugin, I would MUCH rather be importing DOIs or PMIDs into a custom field than formatted references. Plus, I love how you've got the reference showing up on mouseovers for the inline citations.

**Comment by dsifford** [comment]
Hmm.. very interesting. I've never heard to JATS XML, but after a google search it seems like that's what pretty much everyone needs to be using in the journal world. 

Unfortunately, I don't think importing identifiers into a custom field will work for this plugin. I have a deep, unadulterated hatred for PHP (PHP and I are total enemies!) and, because of that, all of the business logic happens on the frontend using JS. 

For your use case, it sounds like you'll need a server-side processor. Maybe KCite will be able to work with you?

You're free to grab some of the code from my repo to generate your tooltips if you'd like. I'm not making any money from this so I'm not afraid to share. The relevant file for that is [this one](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/lib/js/Frontend.ts).

Sorry I can't be more helpful. Once wordpress.org aligns with wordpress.com (and ditches PHP completely), it'll be a different story. I'm hoping that day comes soon.

**Comment by halatkins** [comment]
No - I'm not married to the use of custom fields for this at all. Actually, as far as I see it, things could work together. A custom field could simply store the identifiers, and a simple cut and paste into your work would do the job for the presentation layer.

Anyway, I've gotten way off track from my original question. But let me reiterate how excited I am for what you've got going - and I'd love to help however I can!

**Comment by dsifford** [comment]
I'd have to know a bit more about your workflow. Perhaps, if you'd like, open another issue about that specifically and when you get time give me a detailed description (as detailed as you can or are willing to be) on how you get your stuff into wordpress and what output (or result) you'd like to receive back from that input and we can go from there.

Glad you like what I've done so far! Makes me happy to hear that the plugin is getting good use!

**Comment by dsifford** [comment]
@halatkins Are you still interested in this feature?

If so, could you copy and paste your init scripts here for you custom post types so I can test the implementation. (specifically, your `register_post_type` scripts).

Thanks 👍

**Comment by dsifford** [comment]
@halatkins Scratch the request. I added support for all post types to the next major update. 

I'll be pushing it out soon (likely tomorrow).

**Comment by dsifford** [comment]
Done 9bd9d7274762b1f1a87dcc80647f0b94c779d205
