### ISSUE TITLE
Peer Review User Library

### ISSUE THREAD

**Issue by OllieCo** [dsifford/academic-bloggers-toolkit#67]
Hi, I really like the plugin, and after reading through some discussions in your issues area, look forward to seeing whats to come. I like the peer review component of the plugin and was wondering if you have any plans on further enhancing this component?

Ideally, it would be nice if the plugin could allocate peer reviewers automatically based of the native WP user library, and a defined user role (some setup from the user may be required I guess). I guess one issue might be that peer reviewers might have access to change author content unless there is a way of locking the editor to peer reviewers? 

I work for a University, and we may be able to collaborate on this project if you feel it would help or benefit. 

Cheers.

**Comment by dsifford** [comment]
Hi there!

Admittedly, I've been neglecting that component for some time now.

That's an interesting idea. You're correct that it would take some thought on getting all the implementation details in order. Happy to brainstorm about it though after I get this next update pushed out (adding full inline citation support - it's gonna be huge).

Re: collaboration -- I'd never turn down anybody that's willing to help. Feel free to fork the repo and send in some pull requests!

**Comment by dsifford** [comment]
@OllieCo Haven't heard back from you so I'm closing down this issue.

Feel free to open it back up.

**Comment by OllieCo** [comment]
Sorry, I have been trying to organise a developer to help take on this component. It appears everyone is keen, but it may take some time before we get someone to actually help. I'll reopen this when we have someone.

**Comment by dsifford** [comment]
@OllieCo FYI: I'm working on depreciating the peer review component in its current form so any feedback on how to improve would be encouraged.

The reason for the depreciation: The way it works currently is fundamentally against the beliefs of the plugin. As it currently stands, if you were to use the peer review component, that would introduce a dependency to this plugin on your site, meaning you'd never be able to uninstall the plugin without your posts breaking.

Additionally, the way that the peer reviews have to be added (by the post author) is flawed. This shouldn't fall on the author of the post. It should be the responsibility of the reviewer.

Anyway, just an FYI. If you can stop using the peer review boxes starting now, that would likely save you in the long-term if I can't figure out a way to replace how it currently works.

**Comment by dsifford** [comment]
@OllieCo Next update will remove the peer review boxes entirely. At least, until I can think of a better way of handling them (which may never happen).

To be able to still use this feature after the depreciation, you'll need to install this: 

https://github.com/dsifford/abt-depreciated-peer-review
