### ISSUE TITLE
Cite editing

### ISSUE THREAD

**Issue by fbennett** [dsifford/academic-bloggers-toolkit#70]
I've cloned and installed the project, and brought up the environment locally with `sudo docker-compose up -d`. I get a syntax error with `gulp` (I think because my version of `node.js` or `npm` lags behind that used for ABT development). I can connect to `localhost:8080` though, and WordPress comes up. I have a question and a couple of issues.

The question is about running with the local ABT source. I can log in as `root` as per `README.md`. ABT is not installed, so I installed in the usual way with search-and-install via the Plugins tab. I assume that does not install the source from the repo---would `gulp` install the local source to the WP instance?

The first issue is about the heading for the bibliography. None appears when a with-bibliography style is selected. I'm not sure if a default value is being missed, or if some further configuration is needed.

The second issue is about citation updates. I have been able to break citation updates---but possibly due to a bug that you have fixed in the source (which I may not yet be running), so I'll hold off on the details until I'm up to speed on the setup angle.

**Comment by fbennett** [comment]
Also, where in the top-level source code does manipulation of the DOM take place? If I come across glitches when I get things set up, the symptoms should turn up there, but I don't know where to look.

**Comment by dsifford** [comment]
> I get a syntax error with gulp

Can you copy and paste the error message?

One thing I may have forgotten to document is that after you build your docker environment for the first time, you have to run `npm run chown` which regains ownership of the directories that docker took hold of during build.

> ABT is not installed, so I installed in the usual way with search-and-install via the Plugins tab

The docker environment should be installing the plugin for you. It won't be activated though, so you'll have to just go into the plugin tab and click "activate" and then you should be good to go.

> The first issue is about the heading for the bibliography. None appears when a with-bibliography style is selected.

There is no heading set by default -- Some users don't want a heading so I couldn't set any by default. To set a heading, you just have to go into the plugin options page and type one in where it asks.

> where in the top-level source code does manipulation of the DOM take place?

All TinyMCE DOM manipulation happens in `utils/tinymceFunctions`. All other DOM manipulation is handled by React using virtual DOM.

This chrome extension might be helpful: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en

**Comment by dsifford** [comment]
@fbennett Were you able to get it figured out?

**Comment by dsifford** [comment]
@fbennett I noticed you've been hard at work with updates to citeproc, so I'd hate to bother you. 

If you still need help getting in, let me know. 

I'm going to close this issue for now. Feel free to reopen.

**Comment by fbennett** [comment]
Sorry for the silence. It was (and is) crazy-busy at work, with proofing of
student bibliographies. Juris-M is a great productivity tool, but all those
little decisions and tweaks take their toll...

**Comment by dsifford** [comment]
No apology necessary. I can only imagine how busy you must be!

Fire back on this when you get caught up and I'll walk you through it (if you haven't already figured out how to get it up and running). 👍
