### ISSUE TITLE
Ref list import - ordering and deleting

### ISSUE THREAD

**Issue by GAtherton** [dsifford/academic-bloggers-toolkit#73]
I have erroneously imported 620 references that are uncited via a imported Endnote library. 
All references in the uncited list are ordered by author rather than in the order in which they were uploaded (by year).

The combined effect of these two is that finding the references I want to cite is very time consuming - lots of slow scrolling and no search/filter of the uncited list. I only seem to be able to delete each one by one by citing, then deleting each article. 
Consequently I attempted to delete all records by uninstalling this plugin (clicking 'yes' to delete all files and records), then re-installing. Sadly all the records are still there.

How can I delete all 620 records?
Can you improve uncited locating by adding in search facility and allowing us to order the records according to our field of choice?

Thanks

Graham

**Comment by dsifford** [comment]
Good point. I'll see if I can set aside some time in the next week or so to work on this.

I didn't think anybody would be needing to import their entire library of citations, but I suppose if that's the case, finding what you're looking for could be difficult.

**Comment by dsifford** [comment]
@GAtherton I added a delete all feature to the last update. I'm going to assume that that was an acceptable solution to this issue.

If not, feel free to chime back with further suggestions.
