### ISSUE TITLE
Option for creating own custom citation style

### ISSUE THREAD

**Issue by bskienhvqy** [dsifford/academic-bloggers-toolkit#74]
Hi,

This plugin has many citation styles for choosing (very useful) but many means making confuse (also have some errors) !!!
(as my experience I couldn't choose the best one for my site)

Someone who just need some basic information insert into citation list with their own styles.

It's very helpful if we can have this function (or any chance to make our own style). It would make this plugin more powerful !!!

Regards,

Kien.

**Comment by dsifford** [comment]
Hi there,

I don't have the time right now to add custom styles, but an option for you for the meantime would be to use [this tool](http://editor.citationstyles.org/searchByExample/) to help you find a style that best fits what you're looking for. 

Hope that helps.

**Comment by bskienhvqy** [comment]
Thank you guys. That would be helpful !!!
