### ISSUE TITLE
how to cite reference in-text using JabRef with out DOI

### ISSUE THREAD

**Issue by sash3x** [dsifford/academic-bloggers-toolkit#77]
Hi there,

I have my BibTeX library imported into JabRef and when i try to use this reference list on WordPress, it asks for the PMID/DOI. However, most of my references are websites that do not have DOI's. 

How do i use this academic bloggers toolkit to upload my BibTeX library for in-text citation (i am trying to avoid having to do this manually)?

Many thanks in advance.

**Comment by dsifford** [comment]
@sash3x Currently, the only supported import type is RIS format.

JabRef should support exporting in that format (sometimes it's referred to as "Endnote" format, though that's technically a misnomer).

Hope that helps.
