### ISSUE TITLE
Font size of reference list

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#8]
To my eyes, it looks preferable to have font size of the references as being smaller size than the article.  Here is a mock article for you to judge for yourself:
http://www.earthmedresearch.org/wordpress-resources-at-siteground/
You can see I have three reference lists at the end.  

The first of these three lists is what it looks like if you add the following < span> tags inside *every* < li>< /li>  tag:

< ol >
< li >< span style="font-size: 8pt;"> LIST ITEM GOES HERE < / span></ li>
< li >< span style="font-size: 8pt;"> LIST ITEM GOES HERE < / span></ li>
< /ol >

The second list is what it looks like if you add the following < span> tag *only once*, inside the < ol>< /ol> tags.  I think this looks the best:

< ol>
< span style="font-size: 8pt;">
< li>LIST ITEM GOES HERE</ li>
< li>LIST ITEM GOES HERE < /li>
< /span>
< /ol>

The third list is the default appearance.  

I prefer the second of these three styling examples.  Though it is true I could manually add the <span> tags to every reference list I write without much effort, to do so I have to switch from the WYSIWYG editor to the text editor.  And it just makes me really nervous doing that, because I know sometimes when you then switch back to the WYSIWYG editor, your article may have been altered in ways you didn't want by some automatic filtering or something.  Hence I want to avoid any need to go to the text editor entirely.  

I previously tried solving this issue with a plugin called TinyMCE, which adds an option to edit font size while still in he WYSIWYG editor, but I did not like it as it made my headings in my WYSIWYG editor turn white (and therefore invisible) for no apparent reason.  

Not sure if you can think of any easy way to make this font size change happen.  Don't think too hard about this one as it is not crucial.  I imagine this has nothing to do with CSS and hence could not be solved with CSS override.

**Comment by metallikat36** [comment]
Dang, I did not mean for the span tags to actually render!  Ignore those failed attempts at posting code in my above post.  I will try again in a moment.

**Comment by metallikat36** [comment]
See my thread about "autogenerating" Reference Lists.  Such a feature might require implementing a new shortcode.  It such a shortcode were implemented, then font size could be another parameter of that shortcode.

**Comment by dsifford** [comment]
@metallikat36 As of right now, I won't be able to add styling changes to tweak the ordered list style because the plugin only pulls information from an ordered list, rather than generating one.

Having said that, a workaround for you for the time being is just using an ultra-specific css selector

```css
div[id$="content"] ol:last-of-type {
    font-size: 0.8em;
}
```

**Comment by metallikat36** [comment]
Thanks worked.  Thanks!

**Comment by dsifford** [comment]
@metallikat36 FYI: With release 2.4.0, a more reliable way of applying formatting to your references will be by using the css id `abt-smart-bib`

So, for example, to replace my workaround above, use this...

```css
#abt-smart-bib {
    font-size: 0.8em;
}
```

:+1:
