### ISSUE TITLE
"Autogenerate" Reference List feature

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#9]
This may be opening a can of worms, in which case just forget it.  But to me, here is the ideal way workflow should happen:

1.  I start writing the text of an article
2.  I insert an inline citation, not by inputting a number (as is currently the case with the plugin), but by inputting a PMID or a URL.  No number is manually inputted.  
3.  I keep writing my article like this and keep inputting citations.
5.  I finish my article.
6.  I click publish
7.  I view the article and am happy to see that the article has "autogenerated" numbers for my inline citations as 1, 2, 3, etc, according to the order in which they appear in the article.  I also am happy to see that the article also "autogenerated" a reference list at the bottom of the article, and has numbered it accordingly.  

Okay, that's the ideal, and would be less work for the user.  A few things to consider:

**1.There would be no more such thing as a user needing to create an ordered list at the end of their article, as is presently the case.**
Though this is a time saver, this might just be too different from the plugin you have now for you to want to mess with.  I don't know.  Though maybe what the plugin can do is have the user enter a shortcode [ ] at the end of the article, which will then be the cue to parse the info from the inline-citations, and print an ordered list once published.  

**2.  A reference might be cited inline more than once.**
Oh, I guess this is where time-savings for the user might disappear.  It might be easier to cite the same reference "3" several times in the article (as would presently be done with the plugin) than it would be to cite the same "PMID: 123456" several times in an article.  Though maybe not.  From my standpoint, citing a PMID or URL multiple times in an article is relatively rare.  

Another issue here is that when "autogenerating" the references list at the bottom, it would need to make sure not to include a repeatedly-cited reference more than once.  For a given list item, the logical checks would be:

If(it's a PMID), then check if that PMID already appears earlier in the list.  If so, skip placing it in the references list since it is already there.  B

If(it's a general URL), then check if that url already appears earlier in the list.   If so, skip placing it in the references list since it is already there.  

Similarly, the "autogeneration" of inline citation numbers also would need to check if a reference has already been cited, in which case a new unique citation number should not be assigned.  But rather, a number already assigned just needs to be repeated.  

**3.  User may wish to add references, but not cite them in the article**
I personally don't think I'd ever need this.  But others might.  This overall feature suggestion I am giving in this post would so far only create a reference list for items that were cited in the article.  Suppose I wanted to include a reference, but not cite it anywhere inline.  This might require something like as follows:

- First, have an input box where user inputs a list of "uncited" PMIDS and/or URLs
- Then also make the shortcode I mentioned earlier do a check and see if that box has any contents.  If it does, it parses that info and also prints those references.

**Comment by dsifford** [comment]
Interesting ideas. I'll have to think them over. I'll report back after giving this some thought.
