### ISSUE TITLE
What did last update do? Is biblio format correct?

### ISSUE THREAD

**Issue by metallikat36** [dsifford/academic-bloggers-toolkit#99]
Hi Derek.  I updated just now. Though the description did not have any info on what the update included.  Only thing I can notice is different is that the bibilography now seems to start a new line after each number:
http://www.earthmedresearch.org/neuropathy-review-natural-treatments-drug-risk-factors/
Personally I think this looks clunkier and was sleeker when those line breaks weren't there.

David

**Comment by dsifford** [comment]
@metallikat36 The last update fixed a handful of other citation styles. To fix the ones that you linked, try editing the page and clicking "refresh bibliography list" and they should fix themselves and go back to being on the same line.

Basically, the HTML was being generated slightly wrong which caused citation styles which should have flush indents to be reverse-hanging.

I also added a polyfill for older browsers that were having trouble rendering content using "newer" language features.

Sorry (again) for the inconvenience.

**Comment by metallikat36** [comment]
That fixed it. No problem. Thanks.
